### ISSUE TITLE
Half of cutorch tests fail with CUDA 7

### ISSUE THREAD

**Issue by szagoruyko** [torch/cutorch#129]
This is bad, the latest streams PR doesn't work with CUDA 7.
Errors:
https://gist.github.com/szagoruyko/31d59abf06ee32a396d4

**Comment by soumith** [comment]
Strange. I do test this with CUDA7 which is my default cuda now on my system.

**Comment by soumith** [comment]
Can you comment out the deviceReset function and see if the tests pass after that.

**Comment by soumith** [comment]
*tests for the deviceReset function

**Comment by szagoruyko** [comment]
passes fine without deviceReset, no errors

**Comment by soumith** [comment]
ok looks like deviceReset is AGAIN the issue. shall we remove deviceReset altogether as discussed in the last PR? It's already a function with very flaky semantics (all tensors get invalidated after deviceReset but are still kicking in lua land).

I can remove it, and stub it with a WARNING: Depreceated.

cc: @dominikgrewe @wickedfoo @clementfarabet

**Comment by wickedfoo** [comment]
yes, it's impossible to get to work with torch anyways unless as you imply
we track every single live memory allocation per device ourselves, and
ignore all operations to that memory after reset, which seems pointless.

**Comment by dominikgrewe** [comment]
Sounds good to me.

**Comment by soumith** [comment]
fixed via https://github.com/torch/cutorch/pull/131
