### ISSUE TITLE
Trouble with Tensor mul function

### ISSUE THREAD

**Issue by akashmehra** [torch/cutorch#135]
There is some issue with  ```CudaTensor mul```

The following code: 

```
require 'cudnn'

xCPU = torch.Tensor(2,5):fill(0):float()

x = torch.CudaTensor()

x:resize(xCPU:size()):copy(xCPU)

yCPU = torch.Tensor(2,1):fill(1):float()

y = torch.CudaTensor()

y:resize(yCPU:size()):copy(yCPU)

print(x:mul(y))

```

returns

``expected arguments: *CudaTensor* [CudaTensor] float``

What am I doing wrong?

**Comment by akashmehra** [comment]
Found what I was doing wrong!

**Comment by soumith** [comment]
mul is for vector-scalar multiplication. cmul is for element-wise multiplication.
