### ISSUE TITLE
Segfault as soon as I use cutorch

### ISSUE THREAD

**Issue by Alexis-Jacob** [torch/cutorch#140]
When I start torch, as soon as I ```require 'cutorch'``` I get a segfault
![segv](https://cloud.githubusercontent.com/assets/4202681/7275600/32e88274-e905-11e4-9c10-21fec306186a.png)

It was working before but today I have 3/4 GPU calculating stuff so maybe it can come from there. However I don't think it should segfault

**Comment by dominikgrewe** [comment]
The segfault happens deep within cuBLAS, so it's probably not a cutorch bug. Does it happen consistently? What if you don't have anything running on your GPUs?

**Comment by Alexis-Jacob** [comment]
It was the first time that this segfault happened. But if there is anything running on the GPUs I don't have any problem. 
As you said if it's a bug in cuBLAS I guess you can close the ticket

**Comment by dominikgrewe** [comment]
Yes, looks like a bug in cuBLAS to me.
