### ISSUE TITLE
CUDA 7.0

### ISSUE THREAD

**Issue by soumith** [torch/cutorch#148]
We should think about moving to CUDA7 soon. It has powerful features like streams support for Thrust, NVRTC (see @szagoruyko 's on the fly apply kernels, pretty powerful).

@clementfarabet @dominikgrewe what are your timelines to upgrade to CUDA7 internally? (It is fully backward-compatible with 6.5/5.5 afaik)

**Comment by dominikgrewe** [comment]
We're planning to upgrade to CUDA 7 soon.

**Comment by Kaixhin** [comment]
In relation to my [feature request](https://github.com/torch/torch7/issues/294) in `torch7`, it would be useful to implement a "CudaHalfTensor" with the upcoming CUDA 7.5, with or without a "HalfTensor" in the main library.
