### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by arashno** [torch/cutorch#153]
Hi All.
I am trying to install cuTorch on a cluster.
The cluster has CUDA lib but it is not in default (/usr/local) directory.
I am using this command:
luarocks install cutorch
and it gives me this error:

Installing https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec... switching to 'build' mode
Initialized empty Git repository in /tmp/luarocks_cutorch-scm-1-7917/cutorch/.git/
remote: Counting objects: 119, done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 119 (delta 45), reused 47 (delta 14), pack-reused 0
Receiving objects: 100% (119/119), 117.09 KiB, done.
Resolving deltas: 100% (45/45), done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/mnorouzz/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/mnorouzz/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/mnorouzz/torch/install
CMake Error at /usr/share/cmake/Modules/FindCUDA.cmake:548 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:7 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-7917/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

How can I fix this?
How can I set CUDA_TOOLKIT_ROOT_DIR ?
Thanks

**Comment by andymckenzie** [comment]
How did you solve this problem?

**Comment by arashno** [comment]
By setting this in my .bashrc file:
export CUDA_BIN_PATH=/path/to/CUDA/home

**Comment by andymckenzie** [comment]
thanks

**Comment by liamquin** [comment]
I set PATH=/usr/bin:$PATH because nvcc is in /bin here, and FindCUDA strips out a /bin/ from CUDA_HOE, leaving an empty string, and then says it has not found nvcc. (Mageia Linux) Luckily /bin and /usr/bin are the same thing these days.

**Comment by liamquin** [comment]
I set PATH=/usr/bin:$PATH because nvcc is in /bin here, and FindCUDA strips out a /bin/ from CUDA_HOE, leaving an empty string, and then says it has not found nvcc. (Mageia Linux) Luckily /bin and /usr/bin are the same thing these days.

**Comment by fighting41love** [comment]
I don't know how to find the path to CUDA...

**Comment by nightrome** [comment]
I fixed this problem by making sure that the default folder "/usr/local/cuda" exists. Somehow my system only had "/usr/local/cuda-8.0", so I created a symbolic link: "ln -s /usr/local/cuda-8.0 /usr/local/cuda"

**Comment by seindlut** [comment]
I agree with @liamquin . My solution is that using the following command:
export PATH=/usr/local/cuda-8.0/bin/:$PATH
Please make sure that "nvcc" works after you type this command.
