### ISSUE TITLE
TH_STORAGE_VIEW undeclared

### ISSUE THREAD

**Issue by fpgaminer** [torch/cutorch#166]
I just did a fresh install on a fresh EC2 instance (Ubuntu 14.04) of Torch and cutorch.  I used luarocks to install cutorch, but got this error during build:

```
Building C object CMakeFiles/cutorch.dir/TensorOperator.c.o
In file included from /vol/cutorch/Storage.c:32:0:
/vol/cutorch/torch/generic/Storage.c: In function ‘torch_CudaStorage_new’:
/vol/cutorch/torch/generic/Storage.c:46:45: error: ‘TH_STORAGE_VIEW’ undeclared (first use in this function)
     storage->flag = TH_STORAGE_REFCOUNTED | TH_STORAGE_VIEW;
                                             ^
/vol/cutorch/torch/generic/Storage.c:46:45: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/cutorch.dir/Storage.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/cutorch.dir/all] Error 2
make: *** [all] Error 2
```

It looks like the line throwing that error is new, appearing in this commit not too long ago: https://github.com/torch/cutorch/commit/a15d6be4eca74492b628c2ba3a65c4016f729c69#diff-b021d3ea3c9c9ad4df92e6421010ca1bR46

Probably an untested merge, unless I made a mistake during installation.

After working around the issue by changing TH_STORAGE_VIEW to 8, build passes and seems to work, so that appears to be the only bug introduced.

**Comment by soumith** [comment]
hey @fpgaminer , the cutorch commit required an updated torch as well. 

if you do:

luarocks install torch
luarocks install cutorch

you'll be all set.

**Comment by soumith** [comment]
the default torch distro install installs last known stable commits. however when you did "luarocks install cutorch", you installed the latest HEAD of cutorch, rather than the last stable commit that was recorded in distro: https://github.com/torch/distro/tree/master/extra

**Comment by fpgaminer** [comment]
Okay, good to know it was an issue on my end.  Is there a better way of installing torch + cutorch, etc. to bring a fresh machine up?  I, naturally, just followed the instructions given by Torch to install torch, and then assumed `luarocks install cutorch` was the next sensible step.

**Comment by soumith** [comment]
the default torch install comes with cutorch and all other essential cuda packages. https://github.com/torch/distro/blob/master/install.sh#L84

**Comment by fpgaminer** [comment]
Okay, thank you for the help, and sorry for the false issue.
