### ISSUE TITLE
installation build error

### ISSUE THREAD

**Issue by whitney** [torch/cutorch#168]
Ap[ologies if this is not the proper forum for this. I'm having problems installing cutorch on mavericks with CUDA 7:

$ luarocks install cutorch
...
...
CMake Warning at /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

Scanning dependencies of target THC
[ 67%] [ 67%] [ 70%] [ 73%] [ 76%] [ 79%] Building C object lib/THC/CMakeFiles/THC.dir/THCStorage.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCGeneral.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCAllocator.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCStorageCopy.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCTensor.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCTensorCopy.c.o
Linking CXX shared library libTHC.dylib
[ 79%] Built target THC
[ 82%] Generating TensorMath.c
Scanning dependencies of target cutorch
[ 85%] [ 88%] [ 91%] [ 94%] [ 97%] [100%] Building C object CMakeFiles/cutorch.dir/Storage.c.o
Building C object CMakeFiles/cutorch.dir/init.c.o
Building C object CMakeFiles/cutorch.dir/Tensor.c.o
Building C object CMakeFiles/cutorch.dir/TensorMath.c.o
Building C object CMakeFiles/cutorch.dir/TensorOperator.c.o
Building C object CMakeFiles/cutorch.dir/torch/utils.c.o
In file included from /tmp/luarocks_cutorch-scm-1-1111/cutorch/Storage.c:32:
/tmp/luarocks_cutorch-scm-1-1111/cutorch/torch/generic/Storage.c:46:45: error: use of undeclared identifier 'TH_STORAGE_VIEW'
    storage->flag = TH_STORAGE_REFCOUNTED | TH_STORAGE_VIEW;
                                            ^
1 error generated.
make[2]: *** [CMakeFiles/cutorch.dir/Storage.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/cutorch.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

Any suggestions would be much appreciated.

**Comment by kotrfa** [comment]
Same here:

```
...
Scanning dependencies of target THC
[ 64%] [ 67%] Building C object lib/THC/CMakeFiles/THC.dir/THCAllocator.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCGeneral.c.o
[ 70%] Building C object lib/THC/CMakeFiles/THC.dir/THCStorage.c.o
[ 73%] Building C object lib/THC/CMakeFiles/THC.dir/THCStorageCopy.c.o
[ 76%] Building C object lib/THC/CMakeFiles/THC.dir/THCTensor.c.o
[ 79%] Building C object lib/THC/CMakeFiles/THC.dir/THCTensorCopy.c.o
Linking CXX shared library libTHC.so
[ 79%] Built target THC
[ 82%] Generating TensorMath.c
Scanning dependencies of target cutorch
[ 88%] [ 88%] Building C object CMakeFiles/cutorch.dir/Storage.c.o
Building C object CMakeFiles/cutorch.dir/init.c.o
In file included from /tmp/luarocks_cutorch-scm-1-8406/cutorch/Storage.c:32:0:
/tmp/luarocks_cutorch-scm-1-8406/cutorch/torch/generic/Storage.c: In function ‘torch_CudaStorage_new’:
/tmp/luarocks_cutorch-scm-1-8406/cutorch/torch/generic/Storage.c:46:45: error: ‘TH_STORAGE_VIEW’ undeclared (first use in this function)
     storage->flag = TH_STORAGE_REFCOUNTED | TH_STORAGE_VIEW;
                                             ^
/tmp/luarocks_cutorch-scm-1-8406/cutorch/torch/generic/Storage.c:46:45: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/cutorch.dir/build.make:59:  „CMakeFiles/cutorch.dir/Storage.c.o“ failed
make[2]: *** [CMakeFiles/cutorch.dir/Storage.c.o] Error 1

...

Error: Build error: Failed building.

```

Versions:
```
nvidia-340xx 340.76-9
nvidia-340xx-libgl 340.76-2
nvidia-340xx-utils 340.76-2
```

Torch is just from master branch on github.

Thank you for any help

**Comment by dominikgrewe** [comment]
Looks like your version of Torch is not up-to-date.

**Comment by kotrfa** [comment]
It was installed 4 hours before by commands stated here https://github.com/torch/distro . What could be more up to date than this?

**Comment by dominikgrewe** [comment]
This installs the latest _stable_ version, I think. See #166 for more information.

**Comment by kotrfa** [comment]
Ok. Sorry for false issue and thank you for your help and work.
