### ISSUE TITLE
Rerunning make causes whole cutorch to rebuild again

### ISSUE THREAD

**Issue by hughperkins** [torch/cutorch#171]
modifying one tiny file (or even, not modifying anything...), and then rerunning `luarocks make rocks/cutorch-scm-1.rockspec` causes every file to be rebuilt again, which takes about 5 minutes each time.

I suspect this might be connected to https://github.com/torch/cutorch/issues/100 ?

**Comment by hughperkins** [comment]
Seems like this is something built into cmake's FindCUDA module perhaps?  There seems nothing in the cutorch lib/THC/CMakeLists.txt about this, and the error messages all mention /usr/share/cmake-2.8/Modules/FindCUDA.  (I'm waiting for cutorch to build again, hence have time to ponder this issue :-P )

**Comment by szagoruyko** [comment]
CUDA_ADD_LIBRARY rebuilds everything on any make call, to my experience

**Comment by hughperkins** [comment]
So, I had to rebuild cunn a few times this afternoon, so I hacked around a bit, to see if can prevent the whole-world-building experience, and had some success :-)  Using root, open `/usr/share/cmake-2.8/Modules/FindCUDA.cmake`, and scroll down to line 1295 approx, and modify the start of the sectoin there as follows:

```
      # Build the generated file and dependency file ##########################
      message("generated_file ${generated_file}")
      message("CUDA_NVCC_DEPEND ${CUDA_NVCC_DEPEND}")
      message("custom_target_script ${custom_target_script}")
      message("CMAKE_BINARY_DIR ${CMAKE_BINARY_DIR}")
      set(newdepend "")
      foreach(depend ${CUDA_NVCC_DEPEND})
          if(NOT ${depend} STREQUAL "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/${cuda_target}.dir")
              set(newdepend "${newdepend};${depend}")
          endif()
      endforeach()
      set(CUDA_NVCC_DEPEND "${newdepend}")
      add_custom_command(
        OUTPUT ${generated_file}
        # These output files depend on the source_file and the contents of cmake_dependency_file
        #${main_dep}
        DEPENDS ${CUDA_NVCC_DEPEND}
        #DEPENDS ${custom_target_script}
```

Now, if you build the first time, it of course has to build everyhting.  Bu tthe next time, it will just build hte files that have chnaged :-)

Tested using cunn.

**Comment by hughperkins** [comment]
This is fixed by installing https://github.com/hughperkins/FindCUDA
