### ISSUE TITLE
fresh install failing

### ISSUE THREAD

**Issue by louissmit** [torch/cutorch#172]
Running `luarocks install cutorch` on a fresh torch + deps install fails on Ubuntu 14.04 with the following message:

    In file included from /tmp/luarocks_cutorch-scm-1-5719/cutorch/Storage.c:32:0:
    /tmp/luarocks_cutorch-scm-1-5719/cutorch/torch/generic/Storage.c: In function
    ‘torch_CudaStorage_new’:
    /tmp/luarocks_cutorch-scm-1-5719/cutorch/torch/generic/Storage.c:46:45: error: ‘TH_STORAGE_VIEW’ undeclared (first use in this function)
     storage->flag = TH_STORAGE_REFCOUNTED | TH_STORAGE_VIEW;
                                             ^

**Comment by soumith** [comment]
reinstall torch7 as well.

luarocks install torch

**Comment by louissmit** [comment]
Ah, sorry, I didn't look at previous issues carefully enough. Appreciate the quick reply, though!
