### ISSUE TITLE
Global old torch installation is failing cutorch installation

### ISSUE THREAD

**Issue by yossibiton** [torch/cutorch#184]
Hi, 

I mentioned this problem in another issue (#175) but its still unsolved.
I have a global torch installation, which i dont want to delete (other users are using it).
I want to install the most updated packages of torch, and i'm using github.com/torch/distro.

When it gets to cutorch installation i get an error :

Linking CXX shared library libTHC.so
[70%] Built target THC
make: *** [all] Error 2

I believe this because wrong linking with the global torch installation but cant be sure.
Pay attention that the installation scripts in distro should not care about about any other torch installations on the same machine.

**Comment by YonatanGlassner** [comment]
Looking at the luarocks man page:
--to=<tree>
              Which tree to operate on.
In your case, you can use 
luarocks install <package> --to=/your/local/torch/path

**Comment by yossibiton** [comment]
Solve after giving up and deleting the global installation, and cleaning all its leftovers (runninh clean_old.sh from ezinstall repo).
