### ISSUE TITLE
indexselect requirees longtensor, even though just converts into cudatensor anyway

### ISSUE THREAD

**Issue by hughperkins** [torch/cutorch#202]
In char-rnn, onehot.lua, has to convert into longtensor, which causes unnecessary alloc https://github.com/karpathy/char-rnn/blob/master/util/OneHot.lua#L17-L18 , but we then simply reconvert this back into cudatensor https://github.com/torch/cutorch/blob/master/lib/THC/THCTensorIndex.cu#L253

I wll plausibly attempt to allow indexselect to receive a ClTensor in cltorch, though I havent tried this yet.

**Comment by dominikgrewe** [comment]
There are actually two versions of indexSelect. One takes a LongTensor and one takes a CudaTensor. This was only changed recently in #176, which is maybe why char-rnn isn't taking advantage of it.

**Comment by hughperkins** [comment]
Oh cool! Will update cltorch, and submit a PR to char-rnn.
