### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Fhrozen** [torch/cutorch#204]
Hi,

I just update a few minutes ago the libraries cunn & cutorch using "luarocks install cunn.. cutorch" and after the update when i try to run a program with cuda does not work.
I was wondering if is a problem of the update or something, because before that i had not any problem.

Best Regards

**Comment by dominikgrewe** [comment]
I'm not aware of any issues. Can you give us a bit more detail on how it crashes? Maybe you can post some code that reproduces the error?

**Comment by Fhrozen** [comment]
Sorry but I not sure the problem is, but it appears when i try to move data:

for i = t,math.min(t+opt.batchSize-1,#inset) do
         -- load new sample
         local input = inset[i]--[pos[i]]
         local target = outset[i]--[pos[i]]
         if opt.gpuid >= 0 then
            --cutorch.synchronize()
            input = input:cuda()
            target = target:cuda()
   --TensorType = 'torch.CudaTensor'
         end
         table.insert(inputs, input)
         table.insert(targets, target)
      end

**Comment by Fhrozen** [comment]
It is working, i just updated cunn and cutorch, and the problem doent not appears. 
However i was wondering why using a cutorch.sync() into a for loop, locating data into the gpu stocks the memory and didnt release the memory, that leave the gpu out of memory, anyway, i'm trying to avoid the use of sync into for and the computing speed is really fast.
