### ISSUE TITLE
For info, cltorch migrated to pass sizes and strides as scalar kernel parameters

### ISSUE THREAD

**Issue by hughperkins** [torch/cutorch#207]
For info, cltorch migrated to pass sizes and strides as scalar kernel parameters

This gives the following speedups on [char-rnn](https://github.com/karpathy/char-rnn):
- NVIDIA 940M: iteration time changes from 0.51s to 0.27s.  (cf cutorch time is 0.13s, so cltorch only twice as slow now, compared to three times slower before)
- AMD; three times faster than before
- Intel HD5500: no change, not faster or slower

I'm not sure this change is applicable to CUDA, since I *guess* that the structs are being passed in CUDA along with the kernel parameters anyway?  Also, this change is heavily based around Lua templating, so you'd need to entirely redo the implementation from scratch; only the concept is reusable essentially.

Relevant commits: https://github.com/hughperkins/cltorch/compare/debugging...53340a33

**Comment by dominikgrewe** [comment]
Does this mean you have different kernels for tensors of different dimensions? I guess you only compile them on-demand, do you?

As you said, CUDA probably does this already, but it means we have a fixed number of dimensions. No idea what the overhead is considering that we probably only need a small amount in most cases.

**Comment by hughperkins** [comment]
Both the cutorch and cltorch version are specializing on number of dimensions.  This change doesnt add any new specialization axes.  This change means that in the kernel parameters, instead of having:

```
__global__ somekernel(TensorInfo *infoA, ...
```
we have:
```
__global__ somekernel(long offsetA, long dimA_1, long strideA_1, long dimA_2, long strideA_2, ... )
```
... where the number of size and stride parameters is set according to the dimension specialization.

I tested with kernels up to 25 dimensions, ie about 150 parameters, and it seemed not to die, or take excessive time, using NVIDIA 940M, Intel HD5500, and AMD.  https://github.com/hughperkins/cltorch-benchmarking/blob/master/test_apply3_flat.cpp

**Comment by dominikgrewe** [comment]
cutorch doesn't specialise the kernel parameters on the number of dimensions though. We only specialise for a small number of dimensions in order to improve performance (enabling the compiler to unroll the loop for computing the index). Whereas in cltorch you generate a new kernel for each number of dimensions you encounter, right? 
I'm not saying that's a bad thing, in fact I quite like it :)

**Comment by hughperkins** [comment]
> I'm not saying that's a bad thing, in fact I quite like it :)

Ok :-)
