### ISSUE TITLE
mm/addmm fails with stride=0

### ISSUE THREAD

**Issue by avnermay** [torch/cutorch#213]
require 'cutorch'
torch.setdefaulttensortype('torch.CudaTensor')
A = torch.randn(100,3200)
B = torch.randn(1,10):expand(100,10)
C = torch.randn(10,3200)
torch.mm(B,C) -- THIS LINE THROWS ERROR
A:addmm(0,1,B,C) -- THIS LINE DOES TOO

This is the error I am getting:
 ** On entry to SGEMM  parameter number 10 had an illegal value
Segmentation fault (core dumped)

**Comment by soumith** [comment]
thanks. we fixed this for torch, I suppose I'll have to apply similar patches for cutorch. Will do now.

**Comment by avnermay** [comment]
Great thanks a lot!

**Comment by avnermay** [comment]
One additional comment: 
This issue was giving me trouble when doing a backward pass on a Linear node (line 66 of nn.Linear.lua: "self.gradInput:addmm(0, 1, gradOutput, self.weight)") -- Given that I have a decently sized code base, it was actually quite time consuming to figure out exactly what line of code was throwing this error.  It would be great if all BLAS/CUBLAS errors were logged to stderr with a stack trace.  Currently, the only thing that appears is the error message I copied above, without any info about what function was causing the error.

**Comment by fmassa** [comment]
I'm preparing a patch for it. Just finishing some tests

**Comment by soumith** [comment]
nice!

**Comment by avnermay** [comment]
Awesome thanks so much.  You guys are fast!  

Any comment on the debugging/stack-trace issue?

**Comment by avnermay** [comment]
(and one unrelated question: when does nn.oldSeed get set?)

**Comment by soumith** [comment]
@avnermay nn.oldSeed gets set manually. it's just for backward compatibility (and reproducibility) with really really old scripts.

**Comment by soumith** [comment]
wrt the debuggin/stack-trace issue, if we have an assertion, like THError or LuaL_check* functions, the stack trace gets printed. however, this was an error coming directly from cublas, which kinda caught us off-guard

**Comment by avnermay** [comment]
Great thanks a lot -- if there are other calls into blas/cublas (in other places in Torch) that may result in similarly hard to interpret error messages, it would be great to fix those as well.
