### ISSUE TITLE
require 'cunn' is not working after upgrading to CUDA 7.5 on ubuntu 14.04

### ISSUE THREAD

**Issue by jbansal** [torch/cutorch#226]
Hi All,
I have recently updated to CUDA 7.5 and then I am getting issue while loading cunn and cutorch shared library.
th> require 'cunn'

/usr/local/torch/install/share/lua/5.1/trepl/init.lua:363: /usr/local/torch/install/share/lua/5.1/trepl/init.lua:363: /usr/local/torch/install/share/lua/5.1/cutorch/init.lua:2: cannot load '/usr/local/torch/install/lib/lua/5.1/libcutorch.so'
stack traceback:
	[C]: in function 'error'
	/usr/local/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
	[string "_RESULT={require 'cunn'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406670	

I have libcutorch.so file in the given location.

Please let me know how to fix this issue.

Regards,
Jitendra

**Comment by jbansal** [comment]
Hi,
Issue seems to fix after installing torch with root permission and fixing the LD_LIBRARY_PATH.

Regards,
Jitendra Bansal

**Comment by soumith** [comment]
using root is actually worse, you'll have problems in the future. I recommend cleaning your torch install that you have (root installed) via: https://github.com/torch/ezinstall/blob/master/clean-old.sh and installing torch fresh as non-root.
