### ISSUE TITLE
cutorch hangs on ec2+centos

### ISSUE THREAD

**Issue by wiku** [torch/cutorch#237]
Hi,

I try to deploy cutorch on ec2 gpu instance with centos7. I've successfully installed latest nvidia drivers and cuda 7.5, also successfully compiled and executed some cuda examples. After installing torch and cutorch/cunn, when I run th and require 'cutorch' it just hangs. top shows 100% cpu usage on ksoftirqd, nothing more happens. Can someone help me with that?

==============NVSMI LOG==============
Timestamp                           : Wed Sep  9 17:30:20 2015
Driver Version                      : 352.39

Attached GPUs                       : 1
GPU 0000:00:03.0
    Product Name                    : GRID K520
    Product Brand                   : Grid

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
   63 root      20   0       0      0      0 R 100.0  0.0   0:07.50 ksoftirqd/5 
20914 centos    20   0 36.876g 224948  31092 D  90.7  1.5   0:09.34 luajit      
20902 centos    20   0  130024   1840   1308 R   0.3  0.0   0:00.15 top         
    1 root      20   0   56748   6640   3908 S   0.0  0.0   0:02.65 systemd     
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd   

Best regards,
Sebastian

**Comment by soumith** [comment]
it's usually the JIT compilation that hangs for 2-3 mins (probably longer on EC2 instances). Should only happen once (after that it caches).

http://devblogs.nvidia.com/parallelforall/cuda-pro-tip-understand-fat-binaries-jit-caching/

**Comment by levinboimtomer** [comment]
Another scenario which seems to replicate this is when multiple itorch instances are running (or sleeping). Killing these instances resolved the problem for me.
