### ISSUE TITLE
Can't share parameters between modules in cutorch, LSTM...

### ISSUE THREAD

**Issue by fantajeon** [torch/cutorch#238]
![download](https://cloud.githubusercontent.com/assets/1164150/9807390/94bc2044-588d-11e5-9df3-2125c975bbe6.png)

[Above code is image file, Do not confused!!]

When I used share_params function at line number 38, I'v got a error as follows:

/home/digits/torch/install/bin/luajit: /home/digits/torch/install/share/lua/5.1/nn/Module.lua:96: bad argument #1 to 'set' (expecting number or Tensor or Storage at /home/digits/torch/pkg/torch/generic/Tensor.c:1089)

I think this error occurred when I try to share parameters of a gModule:cuda() with that of another gModule:cuda().
I can't solve this problem?

Please help me...

**Comment by soumith** [comment]
if you could please reduce this to a 20 line code snippet for me to reproduce, and also paste it in text form (I cant copy the text from the image into my terminal), I will look into it.
