### ISSUE TITLE
cutorch.test() fails on multi_gpu_copy if GPUs don't support P2P

### ISSUE THREAD

**Issue by skelleher** [torch/cutorch#239]
cutorch.test() crashes on multi_gpu_copy_noncontig if there are GPUs which aren't identical / do not support peer access.  

If I limit the visible GPUs to 1 the test does not crash.

[cooper@titan]: export CUDA_VISIBLE_DEVICES=0,1                           
[cooper@titan]: th -lcutorch -e "cutorch.test{'multi_gpu_copy_noncontig'}"
seed: 	1442182014	
Running 1 tests	
|  ==> multi_gpu_copy_noncontigcuda runtime error (77) : an illegal memory access was encountered at /tmp/luarocks_cutorch-scm-1-4103/cutorch/lib/THC/THCStorage.c:122	

[cooper@titan]: export CUDA_VISIBLE_DEVICES=0                             
[cooper@titan]: th -lcutorch -e "cutorch.test{'multi_gpu_copy_noncontig'}"
seed: 	1442182030	
Running 1 tests	
_  ==> Done Completed 4 asserts in 1 tests with 0 errors	
--------------------------------------------------------------------------------

**Comment by soumith** [comment]
cc: @wickedfoo wrote patches for this, he has to push them upstream.

**Comment by soumith** [comment]
the patches are to enable non-p2p copies in general, when p2p isn't available..

**Comment by soumith** [comment]
should be fixed now i think.
