### ISSUE TITLE
can't build cutorch with nvidia's cuda-7.0 (on ubuntu 14.04)

### ISSUE THREAD

**Issue by jeffknerr** [torch/cutorch#250]
Hello. I am trying to build cutorch on an ubuntu machine, not using ubuntu's cuda packages. Everything seems to work when I use ubuntu's packages, but when I install cuda-7.0 from nvidia into /usr/local, I can't get it to build. Any ideas why one works and the other doesn't? Other things that use cuda (like caffe) seem to work.

I know I could just use the ubuntu packages, but this is for a lab, and we would rather install cuda into /usr/local and mount it via NFS to all lab machines.

-- jeff

DISTRIB_RELEASE=14.04
cuda-7.0 from nvidia
using https://github.com/torch/distro.git to install torch and cutorch
below is some of log from `luarocks install cutorch`
I think the `CMake Warnings` are harmless, as they also happen when using ubuntu's cuda pkgs
I don't know what the `cublas.h` errors mean, but am guessing they are the problem

```
Cloning into 'cutorch'...
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is Clang 3.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /local/torch/install
-- Found CUDA: /usr/local/stow/cuda-7.0 (found suitable version "7.0", minimum required is "5.5") 
-- Compiling with MAGMA support
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cutorch-scm-1-569/cutorch/build
[  4%] [  6%] [  9%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorSort.cu.o
[ 13%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
[ 16%] [ 18%] Generating TensorMath.c
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorCopy.cu.o
Scanning dependencies of target cutorch_static
[ 20%] Building C object CMakeFiles/cutorch_static.dir/Storage.c.o
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h


CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h
...
.../usr/local/stow/cuda-7.0/include/cublas.h(90): error: more than one instance of overloaded function "cublasGetVersion_v2" has "C" linkage

/usr/local/stow/cuda-7.0/include/cublas.h(102): error: more than one instance of overloaded function "cublasSnrm2_v2" has "C" linkage

/usr/local/stow/cuda-7.0/include/cublas.h(103): error: more than one instance of overloaded function "cublasDnrm2_v2" has "C" linkage
...
...
Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00000606_00000000-7_THCTensorMathMagma.cpp1.ii".
Compilation terminated.
CMake Error at THC_generated_THCTensorMathMagma.cu.o.cmake:264 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-569/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathMagma.cu.o
```

**Comment by soumith** [comment]
hey Jeff. What you are seeing here is that the includes of the found CUDA version (in /usr/local/stow/cuda-7.0) are cross-referencing the includes from some other CUDA version. Do you have any other versions of CUDA on your machine? any headers in /usr/local/include or /usr/include etc...?

**Comment by jeffknerr** [comment]
Thanks for the info. I am closing this, since I've found a workaround. cutorch seems to build fine
if I use the ubuntu/cuda packages. As I mentioned on the torch list, I was trying to use *stow* to
install cuda into /usr/local and then NFS-mount that to my lab machines. If I do that, I get the above
errors. If I skip stow and NFS and just install locally, it all works.
