### ISSUE TITLE
cutorch/torch reference counting

### ISSUE THREAD

**Issue by dxyzab** [torch/cutorch#252]
I wrote a simple program to print out the tensor and associated storage reference counts:

```C
extern "C" void cudaTensorInfo(lua_State* L) {
    THCudaTensor *input = (THCudaTensor*) luaT_checkudata(L, 1, "torch.CudaTensor");

    {
        printf("input refcount %d\n", input->refcount);
        if (input->storage) {
            printf("input refcount storage %d\n", input->storage->refcount);
        } else {
            printf("Tensor has no associated storage\n");
        }
    }
}
```

The function is made visible as curnn_tensorInfo()

I then did an experiment:
th> torch.setdefaulttensortype( 'torch.FloatTensor');
                                                                      [0.0001s]	
th> z = torch.rand(2,2)
                                                                      [0.0002s]	
th> w = torch.Tensor()
                                                                      [0.0001s]	
th> curnn_tensorInfo(z)
input refcount 1
input refcount storage 1
                                                                      [0.0001s]	
th> curnn_tensorInfo(w)
input refcount 1
Tensor has no associated storage
th> w:set(z)
 0.3301  0.7529
 0.2356  0.9333
[torch.FloatTensor of size 2x2]

                                                                      [0.0004s]	
th> curnn_tensorInfo(w)
input refcount 1
input refcount storage 2

which is as expected, since w and z share the storage. What puzzles me is then

th> z = torch.rand(2,2)
                                                                      [0.0001s]	
th> curnn_tensorInfo(w)
input refcount 1
input refcount storage 2
         
Shouldn't setting z to a new tensor cause the reference count of the storage of w to be decreased?
(It does actually decrease if I explicitly call z:free())

**Comment by hughperkins** [comment]
- as far as your question, have you tried calling `collectgarbage()`, after the `z = torch.rand(2,2)` line? Per my understanding, lua uses mark-and-sweep stop-the-world garbage collection, like Java, rather than reference counting, like Python
- as far as the reference count method, not sure if will be accepted into core, but if you do want it in core, I reckon you'd want to factorize it into something like:
```
> w:refcount()
3
> w:storage():refcount()
5
```
In torch7, I think you could implement such methods in generic/Tensor.c and generic/Storage.c, because independent of tensor type, and avoids having to figure out how TensorMath.lua works.  There's probably something similar in cuda.

**Comment by dxyzab** [comment]
I suppose I was missing how Lua itself interacts with the ref counting for Cuda/FloatTensors.
I was thinking that the reference counting for the torch objects would not be affected by Lua.
Does lua access foo->storage->refcount?

**Comment by hughperkins** [comment]
When you define a torch class, you pass in a `new` method, and a `free` method.  The `new` method gets called when someone allocates the object in lua.  The `free` method gets called once that object falls off the edge of the mark-sweep tree, and garbage collection runs.

**Comment by hughperkins** [comment]
(example of creating a new lua class: https://github.com/hughperkins/cltorch/blob/master/src/UserKernel.cpp#L391-L392

```
  luaT_newmetatable(L, "torch.ClKernel", NULL,
                    ClKernel_new, ClKernel_free, ClKernel_factory);
```
free then looks in this case like:
```
static int ClKernel_free(lua_State *L) {
  ClKernel *self = (ClKernel*)THAlloc(sizeof(ClKernel));
  if(!self) {
    return 0;
  }
  if(THAtomicDecrementRef(&self->refCount))
  {
    delete self->kernel;
    self->~ClKernel();
    THFree(self);
  }
  return 0;
}
```
)
