### ISSUE TITLE
System freezing on CUDA call

### ISSUE THREAD

**Issue by etrulls** [torch/cutorch#257]
I've been experiencing random crashes that freeze the whole system and force a hard reboot. I don't know what happens; CPU load skyrockets (on root processes I cannot see) and everything becomes unresponsive very fast.

We upgraded the system to a newer distro version and installed CUDA 7.5 (up from 7.0). Same thing happens but at least I get somewhat more informative messages now:
```
cuda runtime error (30) : unknown error at /home/trulls/soft-gpu/torch-distro/extra/cutorch/lib/THC/THCStorage.c:122
```
That's a call to [THCudaFree](https://github.com/torch/cutorch/blob/master/lib/THC/THCStorage.c#L122) inside THCudaStorage_free. Vanilla torch. The only change was compiling cunn (and cutorch, just in case) with a compute capability of 3.5 rather than 2.0. This system is running four Titan-Z, and the same code with the same installation works without a hitch on another system with two Titan X.

I don't have root access on this server and it's a shared computer that I can't "crash" at will, so I'm having a hard time debugging anything. (I don't expect a solution, but it would be great to know if anyone has pointers or has experienced similar problems.)

**Comment by hughperkins** [comment]
It seems like the torch code is the same on both platforms, and it seems like the GPUs are the same.  What about the GPU drivers?  What is the output from `nvidia-smi` on each platform?

**Comment by etrulls** [comment]
Both my code and the torch installation are the same (dependencies aside). System installation might vary a little but they are both running Ubuntu 14.04.3. They are using the same drivers as far as I can tell.

The good one:
```
+------------------------------------------------------+
| NVIDIA-SMI 352.39     Driver Version: 352.39         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:04:00.0     Off |                  N/A |
| 22%   39C    P8    28W / 250W |     23MiB / 12286MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:83:00.0     Off |                  N/A |
| 22%   57C    P2    85W / 250W |    523MiB / 12287MiB |     12%      Default |
+-------------------------------+----------------------+----------------------+
```

The bad one:
```
+------------------------------------------------------+
| NVIDIA-SMI 352.39     Driver Version: 352.39         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:08:00.0     Off |                  N/A |
| 27%   35C    P0    70W / 189W |     15MiB /  6143MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:09:00.0     Off |                  N/A |
| 28%   44C    P0    95W / 189W |     15MiB /  6143MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
[...]
```
I've also "lost contact" with the GPUs after a reboot (this is new), they are not showing up on lspci. (I don't have physical or root access to this computer, so I'll get in touch with IT and see if we can get them back.)

**Comment by njsm87** [comment]
I'm having the same issue on ubuntu 14.04 (on ec2). What's even more bizarre is that I've uninstalled 7.5 and dropped back down to 7.0, and the code still hangs as soon as it starts doing CUDA operations.

**Comment by etrulls** [comment]
Apparently the problem only happens when you do certain things (not sure what though) on both GPUs on dual-GPU cards such as the Titan-Z, which explains why it worked on the Titan-X (it also works running a single instance on each card separately). Paraphrasing from our correspondence with internal IT services: running on two GPUs within the same card, after a while (minutes) there is an interrupt tempest on the server, with up to 500 kworker processes deadlocked in uninterruptible wait I/O on one GPU board or more. The server freezes up and needs to be restarted. The error message we get seems to be part of data storage management on the GPU board, which indicates that there's probably a problem in the simultaneous access to GPU memory on both cards which creates the deadlock.

I have a piece of code that can reproduce it. It's barebones, don't expect it to make sense:
https://dl.dropboxusercontent.com/u/34854207/26killer.zip
My torch installation is a standard "distro" pull from Nov 18 (I don't think I can give a commit hash for this). Stock CUDNN v3 (release). I have no idea how to go forward, I'll just report my findings in hopes they can be of help for someone else at some point.

Some log/traces:
https://gist.github.com/etrulls/d55c21cafdb9585633dd

We have seen the same behaviour with Theano, but we were not able to reproduce it consistently.

**Comment by soumith** [comment]
If the behavior also occurs in theano, i'd suggest escalating it to NVIDIA. You can file a bug report with them via https://developer.nvidia.com
At the moment does not look like a cutorch-exclusive bug, so closing.
