### ISSUE TITLE
How to do averaging of models which is loaded on different GPUs

### ISSUE THREAD

**Issue by jbansal** [torch/cutorch#263]
Hi,
I have 4 GPUs and I am loading each GPU with same model by using multi-threading.
I am training each model with different data set on separate threads. 
Now I want to do use all 4 models for each GPUs in the main thread and do the averaging of weights and gradients.
Is there any method to do averaging of models weight and gradients on GPU side.

I try to use cutorch.withDevice(GPUid, fun) to copy model from 1 GPU to another GPU, but it is slow process and taking lot of time and I have to write my function to do copy, which is not optimize.

Regards,
Jitendra

**Comment by soumith** [comment]
Have you looked at our DataParallelTable in cunn? https://github.com/torch/cunn/blob/master/doc/cunnmodules.md

cutorch.withDevice is the right way to copy one model to another. You can also simply copy the parameters / gradParameters over, after getting them via getParameters

**Comment by jbansal** [comment]
Hi Soumith,
Thanks for the update.
However I am getting following error when I use DataParallelTable .

/usr/local/share/lua/5.1/cunn/DataParallelTable.lua:414: type() not supported fo
r DataParallelTable.
stack traceback:
        /usr/local/share/lua/5.1/fb/util/error.lua:76: in function </usr/local/s
hare/lua/5.1/fb/util/error.lua:72>
        [C]: in function 'error'
        /usr/local/share/lua/5.1/cunn/DataParallelTable.lua:414: in function 'cu
da'
        [string "_RESULT={model:cuda()}"]:1: in main chunk
        [C]: in function 'real_xpcall'
        /usr/local/share/lua/5.1/fb/util/error.lua:85: in function 'xpcall'
        /usr/local/share/lua/5.1/trepl/init.lua:630: in function 'repl'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
        [C]: at 0x00406260

In my Model, I am using two sequential conv_Net, which is added in parallelTable. After that I am passing this to 1 fully connected network. I guess this DataParallelTable will work when we use only nn.Sequential  conv_networks.
When we add nn.ParallelTable, then it won't work.
Please let me know if I am wrong.

Regards,
Jitendra Bansal
