### ISSUE TITLE
CUDA 7.5 seems to not be supported

### ISSUE THREAD

**Issue by rjzak** [torch/cutorch#267]
I just checked out cutorch, and built it without problems.
However, running: luajit -l libcutorch
Yields:
Error: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /home/user/Downloads/cutorch/lib/THC/THCGeneral.c:16.

I'm using CUDA 7.5 on Ubuntu 14.04 LTS with a Titan X.

**Comment by albanD** [comment]
If you have the `nvidia-<version>` driver installed (latest version at the time of the writing is 355), you must make sure that you also have the `libcuda1-<version>` (with the latest driver it would be `libcuda1-355`). Do you have it?

**Comment by rjzak** [comment]
The version is 352. It's the latest from the Nvidia deb repo at:
http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64

**Comment by soumith** [comment]
this also usually happens if you have some really old CUDA libs lying around on your machine.

**Comment by rjzak** [comment]
This is a fairly fresh installation of Ubuntu without a prior installation of CUDA.

**Comment by albanD** [comment]
So you do have the `libcuda1-352` package installed?

**Comment by rjzak** [comment]
Correct.

**Comment by albanD** [comment]
Does the cuda samples works (test also as sudo)? or is it just when using cutorch?

**Comment by soumith** [comment]
cant reproduce this.
