### ISSUE TITLE
Bug in sort when falling back to Thrust

### ISSUE THREAD

**Issue by fmassa** [torch/cutorch#268]
This bug appeared when generalizing sort to handle all input cases, https://github.com/torch/cutorch/pull/262.
Indeed, it seems that `THCudaTensor_sortImplThrust` can't handle some cases properly.

```lua
a = torch.rand(192000,2):float() 
b = a:sort(1,false)
ac = a:cuda()
-- the following did not to work before #262
-- asserting CUTORCH_DIM_WARNING
bc = ac:sort(1,false)
bcc = bc:float()

print(b:eq(bcc):all())
-- prints false

print((b-bcc):abs():max())
-- prints 0.99831330776215 in my test
```

I'm using CUDA 6.5.
Can you reproduce this problem ?
cc @dominikgrewe

**Comment by fmassa** [comment]
Just tested it using CUDA 7.0 (both on Ubuntu 14.04 latest cutorch), and it also fails.
(I'm mentioning CUDA versions because of [those](https://github.com/torch/cutorch/blob/master/lib/THC/THCTensorSort.cu#L414) checks).

**Comment by szagoruyko** [comment]
can reproduce

**Comment by dominikgrewe** [comment]
Yes, looks like the Thrust function cannot handle non-contiguous slices. I suggest for now we just abort in this case (as we did before) and then think of a better solution, unless someone has a better idea.

**Comment by wickedfoo** [comment]
the fallback is still broken along with other broken sort issues, see https://github.com/torch/cutorch/issues/291

I think it can be fixed though. I have the other things except the Thrust fallback fixed locally.

**Comment by wickedfoo** [comment]
this is fixed now

**Comment by wickedfoo** [comment]
please close this issue
