### ISSUE TITLE
Segmentation fault      (core dumped) 

### ISSUE THREAD

**Issue by Alex-zhai** [torch/cutorch#270]
when  I write require 'cutorch' in a file ,then returned Segmentation fault (core dumped).

**Comment by soumith** [comment]
without anymore details, cant do much about this.

**Comment by Alex-zhai** [comment]
my environment is Centos 6.5 ,Gpu is tesla k20c ,cuda-7.0 was installed.

**Comment by albanD** [comment]
You can try running the following commands to get more insight on what is happening:
Do not copy paste since you will go from bash to torch interpreter!

```bash
# start lua in a debugger
gdb luajit
# wait for gdb to start
# start luajit
r
# you should now see the luajit command prompt
# run the code that cause the segfault
require 'torch'
require 'cutorch'
# this should crash and get you back to gdb
# print the backtrace
bt
# send us this backtrace.
```

**Comment by Alex-zhai** [comment]
I sloved it ,because someone else is using the gpu when I running the codes.The ram is not enough so  Segmentation fault came.Anyway,thank you guys so much!!!

**Comment by atefeh-f** [comment]
Hi,
i encounter with the same error and i run command of aldben:
****
gdb luajit
GNU gdb (Ubuntu 8.0.1-0ubuntu1) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from luajit...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/luajit 
LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
****
require 'torch'
error loading module 'libpaths' from file '/home/atefe/torch/install/lib/lua/5.2/libpaths.so':
	/home/atefe/torch/install/lib/lua/5.2/libpaths.so: undefined symbol: luaL_setfuncs
stack traceback:
	[C]: at 0x004525b0
	[C]: in function 'require'
	/home/atefe/torch/install/share/lua/5.2/paths/init.lua:1: in main chunk
	[C]: in function 'require'
	/home/atefe/torch/install/share/lua/5.2/torch/init.lua:12: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: at 0x004044a0
