### ISSUE TITLE
THCudaShutdown is never called

### ISSUE THREAD

**Issue by mavenlin** [torch/cutorch#280]
`void THCudaShutdown(THCState* state)` is defined in https://github.com/torch/cutorch/blob/master/lib/THC/THCGeneral.c#L81. It is never called, because `_state` is stored as a lightuserdata in `cutorch` and there's no associated `__gc` handle.

Although this might not cause runtime problems.

**Comment by soumith** [comment]
that's a good point cc: @dominikgrewe @wickedfoo

It does not cause runtime problems in Torch itself, but if you embed Torch into another C++ project (for example), it is definitely bad and wrong behavior.
