### ISSUE TITLE
require('cutorch','cunn','cudnn') does not work 

### ISSUE THREAD

**Issue by zhunzhon** [torch/cutorch#282]
Hi,

My system is Ubuntu 14.04, CUDA 7.0, and I have update the Cmake to 3.2.2
I have install 'cutorch','cunn','cudnn', but when I require('cutorch','cunn','cudnn') ,it give this error:

require'cutorch'
/home/sky/torch/install/share/lua/5.1/trepl/init.lua:378: cuda runtime error (30) : unknown error at /home/sky/torch/extra/cutorch/lib/THC/THCGeneral.c:16
stack traceback:
	[C]: in function 'error'
	/home/sky/torch/install/share/lua/5.1/trepl/init.lua:378: in function 'require'
	[string "_RESULT={require'cutorch'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/sky/torch/install/share/lua/5.1/trepl/init.lua:645: in function 'repl'
	.../sky/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	

require'cunn'
/home/sky/torch/install/share/lua/5.1/trepl/init.lua:378: /home/sky/torch/install/share/lua/5.1/trepl/init.lua:378: loop or previous error loading module 'cutorch'
stack traceback:
	[C]: in function 'error'
	/home/sky/torch/install/share/lua/5.1/trepl/init.lua:378: in function 'require'
	[string "_RESULT={require'cunn'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/sky/torch/install/share/lua/5.1/trepl/init.lua:645: in function 'repl'
	.../sky/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	

 require'cudnn'
/home/sky/torch/install/share/lua/5.1/trepl/init.lua:378: /home/sky/torch/install/share/lua/5.1/trepl/init.lua:378: loop or previous error loading module 'cutorch'
stack traceback:
	[C]: in function 'error'
	/home/sky/torch/install/share/lua/5.1/trepl/init.lua:378: in function 'require'
	[string "_RESULT={require'cudnn'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/sky/torch/install/share/lua/5.1/trepl/init.lua:645: in function 'repl'
	.../sky/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	

require('nn') just works fine, only 'cutorch' ,'cudnn'and 'cunn'.

I installed CUDA 7.0 driver and samples could be compiled correctly.

Anyone know how to solve this problem? Thanks

**Comment by albanD** [comment]
Your CUDA runtime is not initialized.
Run one of the CUDA samples as root (for example the deviceQuery) then you will be able to use CUDA based packages.

**Comment by zhunzhon** [comment]
Thanks, 'cunn' and 'cutorch' works!


But the 'cudnn' still have the error,it give the erros:

require'cudnn'
/home/sky/torch/install/share/lua/5.1/trepl/init.lua:378: loop or previous error loading module 'cudnn'
stack traceback:
	[C]: in function 'error'
	/home/sky/torch/install/share/lua/5.1/trepl/init.lua:378: in function 'require'
	[string "_RESULT={require'cudnn'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/sky/torch/install/share/lua/5.1/trepl/init.lua:645: in function 'repl'
	.../sky/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670

**Comment by albanD** [comment]
From your command line run:
`luajit -lcudnn`

does that work? if no what is the error message?

**Comment by zhunzhon** [comment]
The result is:

luajit -lcudnn
/home/sky/torch/install/share/lua/5.1/cudnn/ffi.lua:574: libcudnn.so: cannot open shared object file: No such file or directory
luajit: /home/sky/torch/install/share/lua/5.1/cudnn/ffi.lua:577: 'libcudnn.so not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure all the files named as libcudnn.so* are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

stack traceback:
	[C]: in function 'error'
	/home/sky/torch/install/share/lua/5.1/cudnn/ffi.lua:577: in main chunk
	[C]: in function 'dofile'
	/home/sky/torch/install/share/lua/5.1/torch/init.lua:49: in function 'include'
	/home/sky/torch/install/share/lua/5.1/cudnn/init.lua:4: in main chunk
	[C]: at 0x0046ac00
	[C]: at 0x00406670

**Comment by albanD** [comment]
@zhunzhon it does not find your cudnn lib, how did you installed it properly? is it in your path (see the [install](https://github.com/soumith/cudnn.torch#installation) guide for cudnn)

Also in the future, you should post installation related questions on the forum https://groups.google.com/forum/#!forum/torch7

**Comment by zhunzhon** [comment]
@albanD  Thanks! I have solve this problem after install Cudnn and add the lib.
