### ISSUE TITLE
Torch with require'cunn'

### ISSUE THREAD

**Issue by zhunzhon** [torch/cutorch#283]
Why I must run one of the  CUDA samples as root (for example the deviceQuery), then I can able to use CUDA based packages in Torch.
But when I  restart the computer, the CUDA will not be initialized, I must do that again to enable CUDA based packages in Torch.
@albanD

**Comment by albanD** [comment]
@zhunzhon use the google group for this kind of question not related to cutorch please.
The problem is with CUDA, this is broadly discussed on the internet: one part of the CUDA runtime require root to initialize.
