### ISSUE TITLE
cutorch setup error : Formal parameter space overflowed (256 bytes max)

### ISSUE THREAD

**Issue by hijeffery** [torch/cutorch#284]
Hi, 
has anyone meet this error before ?

nvcc warning : The 'compute_11', 'compute_12', 'compute_13', 'sm_11', 'sm_12', and 'sm_13' architectures are deprecated, and may be removed in a future release.
/home/lran/torch/pkg/cutorch/lib/THC/THCApply.cuh(50): Error: Formal parameter space overflowed (256 bytes max) in function _Z28THCudaTensor_pointwiseApply2I6CopyOpIfEjLin2ELin2EEv10TensorInfoIT0_ES4_S3_T_
CMake Error at THC_generated_THCTensorCopy.cu.o.cmake:264 (message):
  Error generating file
  /home/lran/torch/pkg/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorCopy.cu.o

**Comment by hijeffery** [comment]
Platform: Ubuntu 14.04
Cuda: 6.5 
Hardware: Tesla c1060 *4

**Comment by soumith** [comment]
@hijeffery that graphics card is very old, and has a compute capability of 1.3
We only support CUDA compute capability 2.0 and above (and for performance, 3.0 and above)
