### ISSUE TITLE
Does not Support TitanX

### ISSUE THREAD

**Issue by wangjiangb** [torch/cutorch#287]
Hi, 
  I am trying to use cutorch on TitanX GPU. I manually added the sm50 argument in CMAKEList: 
  >> LIST(APPEND CUDA_NVCC_FLAGS " -gencode arch=compute_35,code=sm_50 ") 
   
  However, I still get the error message:
  >> invalid device function  at     /mnt/home/jiang/code/torch/extra/cutorch/lib/THC/THCGeneral.c:586

  Does anyone have a way to compile it to run on TitanX GPU?

  Thanks.

**Comment by soumith** [comment]
@wangjiangb i think titan-x is sm_52

**Comment by soumith** [comment]
Also, by default it auto-detects your GPUs and sets those flags...

**Comment by wangjiangb** [comment]
@soumith  Unfortunately, it seems it cannot detect TitanX, and that is the reason I am adding the command line argument.

 I am using CUDA 6.5 right now, and it does not support sm52. Compiling other applications with sm50 argument works. I wonder whether there are some other dependencies that could lead to the error.

**Comment by soumith** [comment]
You need at least cuda 7.0

**Comment by wangjiangb** [comment]
After upgrading to Cuda 7.5 and change sm50 to sm52, it is still not working. Returning the same error.

**Comment by soumith** [comment]
As part of installing cuda 7.5 did you upgrade your nvidia driver and restart your machine? Your cuda issues are related to titanx and driver outdated. Nothing to do with cutorch
