### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by jarmstrong2** [torch/cutorch#299]
I'm getting this error: 
torch/install/bin/luajit: cuda runtime error (77) : an illegal memory access was encountered at /tmp/luarocks_cutorch-scm-1-7941/cutorch/lib/THC/generic/THCStorage.c:147
not sure if it's my code or yours...

**Comment by soumith** [comment]
@jarmstrong2 if you are using ClassNLLCriterion, check that your class indices are all within acceptable range. For example, if you have 3 classes, make sure you dont have a class index of 4.
If that doesn't help, please give a script to reproduce the error.
