### ISSUE TITLE
addbmm() method for CudaTensor

### ISSUE THREAD

**Issue by borislavsm** [torch/cutorch#307]
In torch there is a ```:addbmm()``` method for CPU tensors. I was wondering whether it is likely that such method will be implemented also for CudaTensor?

**Comment by albanD** [comment]
can't you use `:baddbmm()` ?

**Comment by soumith** [comment]
One could do baddbbmn followed by a sum, but it's a lot of extra memory. 
Internally we've thought a lot about this and the only feasible way is to just do a for loop and call it a day.

**Comment by soumith** [comment]
We can prepare a PR with that simple Implementation.

**Comment by borislavsm** [comment]
I can used ```:baddbmm()``` and then sum over the batches but if the number of batches is large that will require a lot of memory.

**Comment by zhangxiangxiao** [comment]
In need of addbmm() for cutorch too here!

**Comment by ebetica** [comment]
Should be added here: https://github.com/torch/cutorch/pull/342
