### ISSUE TITLE
luarocks_cutorch-scm-1-3737/cutorch/lib/THC/THCGeneral.c:16

### ISSUE THREAD

**Issue by LeeHwa** [torch/cutorch#308]
gimboseog-ui-MacBook-Air:neuraltalk2 JewelryKIM$ th eval.lua
/Users/JewelryKIM/torch/install/bin/luajit: ...rs/JewelryKIM/torch/install/share/lua/5.1/trepl/init.lua:383: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-3737/cutorch/lib/THC/THCGeneral.c:16
stack traceback:
	[C]: in function 'error'
	...rs/JewelryKIM/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
	eval.lua:58: in main chunk
	[C]: in function 'dofile'
	...yKIM/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010e84fbc0

how to solve this problem...

**Comment by albanD** [comment]
Does the CUDA samples work?
The problem seems to come from CUDA and not cutorch.

**Comment by LeeHwa** [comment]
gimboseog-ui-MacBook-Air:release JewelryKIM$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL

CUDA does not working... how to fix this..

**Comment by soumith** [comment]
please refer to the CUDA manual, and/or google search.
