### ISSUE TITLE
when require 'cutorch', it use all gpus in one machine, and killed my other training job, how to fix this?

### ISSUE THREAD

**Issue by tornadomeet** [torch/cutorch#310]
Hello,

i'm newbie of torch, and after i installed torch,  i try run some code, all is ok, but i find when i run:
```python
require 'cutorch';
```
then it will start all of my k80s in one machine, because there is som traning job of some gpus with almost full memeory,  when torch starts with gpu, it killed all of the other job. so how to fix this probem?that to say, when i start torch with gpu, it use the gpu 0 default?
thank you very much!

**Comment by fmassa** [comment]
Start torch using
```
CUDA_VISIBLE_DEVICES=n th
```
where `n` is the gpu (or gpus in a comma-separated list) that you want to use.

**Comment by tornadomeet** [comment]
thanks

**Comment by wickedfoo** [comment]
I'm thinking about making cutorch lazily initialize all GPUs except the first one visible to the program. If you have 8 GPUs in the system, it's responsible for a huge (10-20+ second) delay in startup.

**Comment by soumith** [comment]
10-20+ second delay sounds like a problem regardless of the lazy initialization right? usually it's instant.

**Comment by szagoruyko** [comment]
it's probably compiling kernels for Maxwell in runtime as they were not compiled before.

**Comment by jnhwkim** [comment]
What is the difference with `cutorch.setDevice(i)` comparing with `CUDA_VISIBLE_DEVICES=n th`?

**Comment by ajdroid** [comment]
@jnhwkim, if you `require 'cutorch'` and check `nvidia-smi` the difference is visible.

**Comment by jnhwkim** [comment]
@ajdroid Thanks, I got the difference now.
