### ISSUE TITLE
Terminal freezing after using "cutorch/cunn/cudnn" or any other GPU related application.

### ISSUE THREAD

**Issue by codeAC29** [torch/cutorch#313]
I recently updated my NVIDIA drivers using `NVIDIA-Linux-x86_64-352.79.run` and `cuda_7.5.7_rc_linux.run`

But now whenever I try to use my GPU either through Torch (say: `require 'cunn'`) or for any other system related application (say: `nvidia-smi`); my terminal is freezes.
Can anyone help me in finding a solution to this?

Thanks.

**Comment by soumith** [comment]
this is unfortunately a driver relate issue, not related to cutorch/cunn. Try google search.

**Comment by jnhwkim** [comment]
@codeAC29 In my case, freeze after ctrl+c, sometimes (within 10 trials). `352.79` and `352.63` confirmed. Do you think it's related to with your case? And I wonder if two GFX cards with SLI may introduce this issue.

**Comment by adamist521** [comment]
Same problem happens on my machine too...
Using K-80 and Ubuntu 14.04 with `NVIDIA-Linux-x86_64-346.96.run`, `cuda-linux64-rel-7.0.28-19326674.run`.
Get's screwed up after calling cutorch. I can use it only once after rebooting. I can't even exit `th` after requiring cutorch. Think it's problem with cutorch...

**Comment by adamist521** [comment]
Maybe found a solution... Will try it tomorrow
https://groups.google.com/forum/#!topic/torch7/kLusyLEj4oc

**Comment by codeAC29** [comment]
Thanks @adamist521 for the link. Let me know if you find a solution. I have this issue with K-40c on Ubuntu 14.04

**Comment by adamist521** [comment]
@codeAC29 installed latest driver for K80 (352.79 installed from NVIDIA dev. page, which isn't included in cuda-...-7.5.run or neither cuda-..-7.5.deb) and still did not work... 
This is making me crazy... I'll try sending issue to NVIDIA... Got no more clue :cry:

**Comment by adamist521** [comment]
Solution was to install the latest driver 361.28 even if it is not supported.
https://groups.google.com/forum/#!topic/torch7/kLusyLEj4oc
