### ISSUE TITLE
CUDA driver version is insufficient on mac

### ISSUE THREAD

**Issue by rafalkowalski** [torch/cutorch#318]
Hi,
When I've tried run a command:

>  $ luajit main.lua.

 
I have got an error: 

> luajit: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-384/cutorch/lib/THC/THCGeneral.c:16
> stack traceback:
> 	[C]: at 0x0898b920
> 	[C]: in function 'require'
> 	/Users/rafal/torch/install/share/lua/5.1/cutorch/init.lua:2: in main chunk
> 	[C]: in function 'require'
> 	/Users/rafal/torch/install/share/lua/5.1/cunn/init.lua:1: in main chunk
> 	[C]: in function 'require'
> 	main.lua:52: in main chunk
> 	[C]: at 0x010826ebd0 

How can I solve this problem?
System 
OS X Yosemite 10.10.5
CUDA CUDA Driver Version: 7.5.20

**Comment by soumith** [comment]
have you tried..., ummm, upgrading your driver?

**Comment by soumith** [comment]
cuda version is separate from nvidia driver. google on how you can upgrade your nvidia driver.
