### ISSUE TITLE
indexCopy and indexAdd are broken

### ISSUE THREAD

**Issue by soumith** [torch/cutorch#320]
X = torch.rand(4, 500):cuda()
C = torch.CudaTensor(2, 500):zero()
indices = torch.LongTensor({1,2,2,2})
C:indexCopy(1, indices, X);
C[1]:eq(X[1]):sum()

256

C[1]:eq(X[1]):sum() should be 500.
This problem also affects indexAdd too (since they use the same indexing logic) ...

Looks like nothing is getting copied beyond the first 256 elements.
cc: @dominikgrewe

**Comment by soumith** [comment]
possibly indexFill as well.

Allan Jabri is prepping a fix.

**Comment by soumith** [comment]
Fix might be in the lines of https://github.com/torch/cutorch/pull/285

**Comment by wickedfoo** [comment]
this should be fixed now
