### ISSUE TITLE
Error while installing cutorch

### ISSUE THREAD

**Issue by nishantsharmajecrc** [torch/cutorch#322]
I'm trying to install cutorch. I've tried almost everything and cannot understand why this is failing!
can anyone help with it? 

nishant@nishant-home:/tmp/newcu2/cutorch$ ~/dqn/DeepMind-Atari-Deep-Q-Learner/torch/bin/./luarocks make rocks/cutorch-scm-1.rockspec
Warning: unmatched variable LUALIB
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/nishant/dqn/DeepMind-Atari-Deep-Q-Learner/torch/bin/.." -DCMAKE_INSTALL_PREFIX="/home/nishant/dqn/DeepMind-Atari-Deep-Q-Learner/torch/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/nishant/dqn/DeepMind-Atari-Deep-Q-Learner/torch
-- Found CUDA: /usr (found suitable version "5.5", minimum required is "5.5") 
-- Compiling for CUDA architecture: 1.2
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/newcu2/cutorch/build
[  2%] [  5%] [ 10%] [ 10%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorTopK.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THCStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THCTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THCStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THCStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THCTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THCStorage.cu

/tmp/newcu2/cutorch/lib/THC/THCBlas.cu(255): error: argument of type "const float **" is incompatible with parameter of type "float **"

1 error detected in the compilation of "/tmp/tmpxft_00007605_00000000-6_THCBlas.cpp1.ii".
CMake Error at THC_generated_THCBlas.cu.o.cmake:264 (message):
  Error generating file
  /tmp/newcu2/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCBlas.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/tmp/newcu2/cutorch/lib/THC/THCTensorTopK.cu(74): error: identifier "__ballot" is undefined
          detected during:
            instantiation of "void radixSelect<DataType,BitDataType,IndexType,RadixConverter,Order>(const RadixConverter &, DataType *, IndexType, IndexType, IndexType, int *, DataType *) [with DataType=float, BitDataType=unsigned int, IndexType=unsigned int, RadixConverter=FloatToSortedInt, Order=true]" 
(291): here
            instantiation of "void gatherTopK<IndexType,Dim,Order>(TensorInfo<IndexType>, IndexType, IndexType, IndexType, IndexType, TensorInfo<IndexType>, IndexType, IndexType, TensorInfo<IndexType>, IndexType) [with IndexType=unsigned int, Dim=1, Order=true]" 
(497): here

/tmp/newcu2/cutorch/lib/THC/THCScanUtils.cuh(61): error: identifier "__ballot" is undefined
          detected during:
            instantiation of "void exclusiveBinaryPrefixSum<T,KillWARDependency>(T *, __nv_bool, T *, T *) [with T=int, KillWARDependency=true]" 
/tmp/newcu2/cutorch/lib/THC/THCTensorTopK.cu(323): here
            instantiation of "void gatherTopK<IndexType,Dim,Order>(TensorInfo<IndexType>, IndexType, IndexType, IndexType, IndexType, TensorInfo<IndexType>, IndexType, IndexType, TensorInfo<IndexType>, IndexType) [with IndexType=unsigned int, Dim=1, Order=true]" 
/tmp/newcu2/cutorch/lib/THC/THCTensorTopK.cu(497): here

2 errors detected in the compilation of "/tmp/tmpxft_00007621_00000000-6_THCTensorTopK.cpp1.ii".
CMake Error at THC_generated_THCTensorTopK.cu.o.cmake:264 (message):
  Error generating file
  /tmp/newcu2/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorTopK.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorTopK.cu.o] Error 1
ptxas /tmp/tmpxft_00007620_00000000-5_THCStorage.ptx, line 923; warning : Double is not supported. Demoting to float
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by albanD** [comment]
Which GPU are you using?

**Comment by nishantsharmajecrc** [comment]
01:00.0 VGA compatible controller: NVIDIA Corporation GT216M [GeForce GT 230M] (rev a2)

**Comment by albanD** [comment]
The problem is that this is a very old GPU that has a compute capability of 1.2, from your error message, it seems that some CUDA functions like `__ballot` did not exist at that time and some other problems with the CuBLAS interface.
I think torch is only supporting GPUs with compute compatibility >= 2.0 ( @soumith can you confirm that?)

That being said, the cards you have were not made for computations (the GT230M has only 48 CUDA cores) and it may be actually slower than running your code on CPU.

**Comment by soumith** [comment]
i can confirm alban's statements. Also, we should've caught this at the cmake level and fatal-ed out with an error.

**Comment by zhangxiangxiao** [comment]
Is it really a good idea to detect this at cmake level? I even doubt whether it's a good idea to detect CUDA computing capacity at compile time at all (it apparently does this currently). IMO the best default behaviour is just to compile for all compatible computing capacities (I know one can choose to do this by hacking CMAKE variables), so that in mixed GPU or NFS environments it can run on any compatible GPU.

In an actual deployment we may even want to compile CUDA code on a machine without GPU. Running NVCC and linking CUDA library do not require a machine to have a GPU at all; only running those program does. Runtime error should be fine IMO.

**Comment by keerthiskating** [comment]
I have the cuda architecture 2.0 . But still i got the same error

**Comment by albanD** [comment]
@keerthiskating is it the same error with "__ballot"? Because it was introduced in 2.0, so you should not have this problem.
