### ISSUE TITLE
Failure detected in __THCudaCheck might not survive stack unwind

### ISSUE THREAD

**Issue by hughperkins** [torch/cutorch#329]
I got a seg fault something like the following.  The cause of this seg fault is outside the scope of htis issue:
```
luajit: cuda runtime error (77) : an illegal memory access was encountered at /home/ubuntu/git/cutorch/lib/THC/generic/THCStorage.c:170
```
(Note that line number might not exactly match master THCStorage.c, because I added a ton of `printf`s whilst trying to debug the issue.)

After instrumenting THCStorage.c a bit, it looked like it was crashing during a Storage_free:
```
Storage_free x self=171492384
...cudafree 30136074240
```
After this line, the seg fault occurred, so it seemed maybe some issue with the free.

In fact, the error happened about 15,000 lines of debug earlier, inside THCTensorMath.cu:
```
thcudacheck FAIL file=/home/ubuntu/git/cutorch/lib/THC/THCTensorMath.cu line=303
```
Unfortunately, this error message was swallowed, because the program segfaulted before printing it.  It appears above after adding some instrumentation to __THCudaCheck:
```
void __THCudaCheck(cudaError_t err, const char *file, const int line)
{
  if(err != cudaSuccess)
  {
    printf("thcudacheck FAIL file=%s line=%i\n", file, line );
    _THError(file, line, "cuda runtime error (%d) : %s", err,
             cudaGetErrorString(err));
  }
}
```
After adding this code, it became obvious that the error was not during the free, but much earlier.  Actually, it was about 15,000 lines of debug statements earlier, but swallowed by the segfault during stack unwind.

I think it could be worth ensuring that the error is printed during __THCudaCheck, in case it doesnt survive subsequent unwind.

**Comment by soumith** [comment]
@hughperkins when you are debugging CUDA errors, the first thing one should do is to switch to synchronous calls, so that you can identify the point of failure.

CUDA_LAUNCH_BLOCKING=1 th [yourscript.lua]

This triggers a THCudaCheck exactly at the point of error.
If the launches are asynchronous, THCudaCheck is only triggered when the launched kernel finally computes, which might be much later.

**Comment by hughperkins** [comment]
Good info. Thanks!
