### ISSUE TITLE
sort() broken when total # elements is > 2^24 and sorting dimension > 2048 but <= 2^24

### ISSUE THREAD

**Issue by wickedfoo** [torch/cutorch#339]
:(

Another victim of using float as an index.

The fallback Thrust sort doesn't work in this case, as there is a stage in the sorting where we have a global index.

Fix coming.

The real fix is to change the API to return a CudaLongTensor.

**Comment by soumith** [comment]
@dominikgrewe are you guys okay with the change in the API (in a longer-term PR) to return a CudaLongTensor?

**Comment by dominikgrewe** [comment]
I'm certainly in favour of moving to CudaLongTensor in the long term. As long as we keep things consistent with Torch it hopefully won't cause too many disruptions.
