### ISSUE TITLE
Feature requests: CNMeM

### ISSUE THREAD

**Issue by iamalbert** [torch/cutorch#341]
Hi, 
Released last year by Nvidia, [CNMem](https://github.com/NVIDIA/cnmem) can provide faster CUDA memory allocation by kind of memory pool techniques. As both Caffe and Theano have already implemented this, we can consider adding it as well.

I am interested in developing this feature, but I need some assistance about the allocation parts in cutorch.

**Comment by soumith** [comment]
@iamalbert we've looked into CNMem, and it is unnecessary in the context of torch, as we pre-allocate and reuse buffers as we need (our layers are stateful). Hence, we do not have the issues of statelessness and greedy allocation that plague(d) Theano.

**Comment by iamalbert** [comment]
Got it!

**Comment by bartvm** [comment]
Although this is true for Torch's `nn` package, it's not true for `torch-autograd`. I tried using CNMeM there, and it leads to a 2x speedup in some cases... Given that, would there be interest in adding CNMeM support? I believe it's relatively straightforward: bartvm/cutorch@2d2338e1ac8e714f9bddc0fb7ab8b10b4dce1bff

**Comment by soumith** [comment]
Interesting. Okay will review and integrate
