### ISSUE TITLE
Headless CUDA hanging

### ISSUE THREAD

**Issue by mrharicot** [torch/cutorch#346]
I had issues with my headless (no monitor connected) Ubuntu 14.04 multi-gpu setup.
Running anything using cutorch would hang when finished or interruped and I would have to reboot the machine.
However the same code would finish fine if a monitor was connected to the machine.
The solution (which took me a while to figure out...) is to enable the persistence mode which keeps the gpu drivers loaded even when no process is running.

You can do this by running **nvidia-smi -pm 1**

You can also run it at startup by editing cron
**sudo crontab -e** then add **@startup nvidia-smi -pm 1**

I hope this help if anyone has the same problem!

**Comment by soumith** [comment]
Thanks! This is good to know.
