### ISSUE TITLE
cuda runtime error (77)

### ISSUE THREAD

**Issue by as1986** [torch/cutorch#354]
I encountered the following error message after some training loops:
torch/extra/cutorch/lib/THC/THCGeneral.c line=591 error=77 : an illegal memory access was encountered

I can work around this problem by pre-allocating tensor space for a function that returns tensor:t():contiguous() outside of the loop. Regrettably I may not be able to re-produce the issue in some succinct code. But my program originally looked like this:

```
function foo(x, y)
   -- do something on x, y
   return x:t():contiguous(), y:t():contiguous()
end

for i=1, #examples do 
   local x_t, y_t = foo(x[i], y[i])
end
```

And now it looks roughly like this

```
function foo(x, y, x_t, y_t)
   -- do something on x, y
   x_t:copy(x:t()), y_t:copy(y:t())
end

local x_t = torch.Tensor()
local y_t = torch.Tensor()
for i=1, #examples do 
   foo(x[i], y[i], x_t, y_t)
end
```

So I think there may be a bug in torch.Tensor.contiguous().

**Comment by soumith** [comment]
i tried doing some variants of your code, and I cant reproduce it either. Without a proper repro, unfortunately cant take a look at it. :(

**Comment by amujika** [comment]
I also get the same error when training on my laptop. It can happen any time between 5 minutes and 10 hours into the training. I think it can happen when your GPU overheats, because I don't get that error with the same code, when training on CPU or Amazon Web Services.
