### ISSUE TITLE
luarocks install cutorch can't build

### ISSUE THREAD

**Issue by robinmeier** [torch/cutorch#356]
i'm on os x 10.10.5
NVIDIA GeForce GT 750M 2048 MB

what am i doing wrong?
thank you for your help

In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' fIinl ef inloet  ifnoculnudd
e#di nfcrloumd e< b<usitlrti-nign.>h:>3
3 2 : 
 I n   f i l^e
 included from <command line>:13:
In file inIcnl ufdielde  firnocml u/duesdr /flroocma l</bcuuidlat/-iinnI>cn:l 3uf3di2el:/e
c Iuindn acf_liruludene tdii nmfcerl.ouhmd: e1<d1b 2uf:ir
lo/tmu- si<rnc/>ol:mo3mc3aa2nl:d/
 cIlunid nafe/i>il:ne1c 3li:un
dcIeln/u cdfoeimdlm eof nri_onfmcu ln<uccdtoeimdom nafsnr.doh m:l 6i/5nu:es1>r0:/:1l 3of:ca
atIlan/l c fueidrlare/o irin:nc cl'lusudtdere/idcn ugfd.raho_'mr  uf/niutlsierm /enl.oohtc: a1fl1o/2uc:nu
dd/
au#/siirnn/cclllouucddaeel //<ccsuutddraai_/nrigun.nchtl>iu
md ee ./ hc :o 1m 1m 2o :n 
_^/f
uusnrc/tlioocnasl./hc:u6d5a:/1i0n:c lfuadtea/lc oemrmroonr_:f u'nscttriionngs..hh': 6f5i:l1e0 :n ofta tfaolu nedr
r#oirn:c l'usdter i<nsgt.rhi'n gf.ihl>In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
e not found
#include <string.h>
         ^
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^

         ^
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
1 error generated.
CMake Error at THC_generated_THCBlas.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-3311/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
CMake Error at THC_generated_THCStorageCopy.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-3311/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o] Error 1
1 error generated.
CMake Error at THC_generated_THCReduceApplyUtils.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-3311/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o] Error 1
1 error generated.
CMake Error at THC_generated_THCTensor.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-3311/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensor.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o] Error 1
1 error generated.
CMake Error at THC_generated_THCTensorCopy.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-3311/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorCopy.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o] Error 1
1 error generated.
CMake Error at THC_generated_THCTensorMath.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-3311/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o] Error 1
1 error generated.
1 error generated.
CMake Error at THC_generated_THCStorage.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-3311/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o] Error 1
CMake Error at THC_generated_THCTensorTopK.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-3311/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorTopK.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorTopK.cu.o] Error 1
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by robinmeier** [comment]
reinstalled everything but still getting same errors, starting with this one:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^

any help would be highly appreciated


[ 20%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
In file included from <built-in>:332:
In file included from <command line>:13:
In file included from /usr/local/cuda/include/cuda_runtime.h:112:
/usr/local/cuda/include/common_functions.h:65:10: fatal error: 'string.h' file not found
#include <string.h>
         ^
1 error generated.
CMake Error at THC_generated_THCBlas.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-7072/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o


make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
1 error generated.
1 error generated.
CMake Error at THC_generated_THCReduceApplyUtils.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-7072/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o


make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o] Error 1
CMake Error at THC_generated_THCTensor.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-7072/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensor.cu.o


CMake Error at THC_generated_THCStorageCopy.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-7072/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o


make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o] Error 1
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o] Error 1
1 error generated.
CMake Error at THC_generated_THCTensorCopy.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-7072/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorCopy.cu.o


make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o] Error 1
1 error generated.
CMake Error at THC_generated_THCTensorMath.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-7072/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o


make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o] Error 1
1 error generated.
1 error generated.
CMake Error at THC_generated_THCStorage.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-7072/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o


make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o] Error 1
CMake Error at THC_generated_THCTensorTopK.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-7072/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorTopK.cu.o


make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorTopK.cu.o] Error 1
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by robinmeier** [comment]
running  xcode-select --install fixed this particular error. have a new error instead now -

1 warning generated.
[ 79%] Linking CXX shared library libTHC.dylib
ld: file not found: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/THC/libTHC.dylib] Error 1
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by szagoruyko** [comment]
that's a weird issue, seems that you can symlink libBLAS to libSparseBLAS to fix, check here https://github.com/szagoruyko/loadcaffe/issues/55

**Comment by robinmeier** [comment]
thank you szagoruyko!!
this fixed it indeed:

went into /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/
and duplicated libBLAS.dylib / renamed it to libSparseBLAS.dylib
