### ISSUE TITLE
Crash: TestSuite error

### ISSUE THREAD

**Issue by efva** [torch/cutorch#358]
Hi all, 
After installing torch and cutorch/ cunn /cudnn I try to load the library with 

require('cutorch') 

but I get this error message 
" _install/share/lua/5.1/torch/TestSuite.lua:15: Test atan2 is already defined.  "
Has anyone encountered something similar before? 

This was after a clean installation, never had the problem before. I've noticed after installing
cudnn. 

Thanks,

**Comment by soumith** [comment]
this is probably because of a change that I made yesterday. i'll fix it in a sec.

**Comment by soumith** [comment]
fixed via https://github.com/torch/cutorch/commit/1c8012af3bae22c377101600fc00153076484403
