### ISSUE TITLE
New indexCopy not working with non-contiguous tensor

### ISSUE THREAD

**Issue by Saulzar** [torch/cutorch#36]
Simple example to demonstrate:

require 'cutorch'
function testCopy(tensor)
  ones = tensor {1}:expand(3)
  indices = torch.LongTensor {1, 3, 5}

  copy = tensor (5):zero()
  copy:indexCopy(1, indices, ones)

  return copy
end

print( testCopy(torch.Tensor), testCopy(torch.CudaTensor) )

Output should be:
 1
 0
 1
 0
 1
[torch.DoubleTensor of dimension 5]

But for CudaTensor it gives:

 1.0000
 0.0000
 0.0023
 0.0000
 0.0833
[torch.CudaTensor of dimension 5]

(presumably the 0.0023 and 0.0833 are uninitialized memory)

**Comment by edouardoyallon** [comment]
Hi, there might be again an issue with non-contiguous tensor, I'm not sure to understand why I'm getting a different output with the following code:

require 'cutorch'
idx=torch.LongTensor{1}
n=4
x1=torch.rand(1,1,n,n):float()
x2=x1:cuda()

z1=x1:narrow(n,n,1)
tmp1=x1:narrow(n,2,1):clone()
h1=z1:indexCopy(n,idx,tmp1)


z2=x2:narrow(n,n,1)
tmp2=x2:narrow(n,2,1):clone()
h2=z2:indexCopy(n,idx,tmp2)

x2=x2:float()
print(x2-x1)

(1,1,.,.) = 
  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000 -0.3561
  0.0000  0.0000  0.0000  0.4706
  0.0000  0.0000  0.0000 -0.1601
[torch.FloatTensor of size 1x1x4x4]

The behavior of FloatTensor is correct. I've already tried to do 'luarocks install torch' and 'luarocks install cutorch'.
Thanks for any support.

**Comment by soumith** [comment]
we found this recently as well. we are prepping a fix for this.

**Comment by soumith** [comment]
I think should be fixed via https://github.com/torch/cutorch/pull/285
