### ISSUE TITLE
Error install cutorch: THCBlas.cu(255): error: argument of type "const float **" is incompatible with parameter of type "float **"

### ISSUE THREAD

**Issue by AlexBYin** [torch/cutorch#363]
Hi,

I tried to install torch on my EC2 machine (g2.2xlarge). The machine has a compatible GPU card:
lspci | grep -i nvidia
00:03.0 VGA compatible controller: NVIDIA Corporation GK104GL [GRID K520] (rev a1)

But the installation failed due to the error 
THCBlas.cu(255): error: argument of type "const float **" is incompatible with parameter of type "float **"
Could I get some directions from you guys?
I would greatly appreciate any hints and help.

A similar issue was reported earlier (https://github.com/torch/cutorch/issues/322) but it was caused by a old GPU card that's not supported. That's not the case here. 

Detailed errors:
--------------------------------------
Found CUDA on your machine. Installing CUDA packages
Warning: unmatched variable LUALIB
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/bingyin/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/bingyin/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 4.4.6
-- The CXX compiler identification is GNU 4.4.6
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/bingyin/torch/install
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/nvidia/cuda (found suitable version "5.5", minimum required is "5.5") 
-- MAGMA not found. Compiling without MAGMA support
-- **Compiling for CUDA architecture: 3.0**
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bingyin/torch/extra/cutorch/build
[  2%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
[  5%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
[  7%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
[ 12%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
[ 12%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
[ 15%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorTopK.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
[ 20%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorage.h
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCStorage.h
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCStorageCopy.h
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCStorageCopy.cu
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorage.h
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorage.h
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensor.h
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensor.h
CMake Warning at /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h
/home/bingyin/torch/extra/cutorch/lib/THC/THCBlas.cu(255): error: argument of type "const float **" is incompatible with parameter of type "float **"
1 error detected in the compilation of "/tmp/tmpxft_00007ccf_00000000-6_THCBlas.cpp1.ii".
CMake Error at THC_generated_THCBlas.cu.o.cmake:266 (message):
  Error generating file
  /home/bingyin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2
Error: Build error: Failed building.

**Comment by szagoruyko** [comment]
looks like the issue is CUDA 5.5, too old, you should update it. We bumped cunn to 6.5, should do the same with cutorch.

**Comment by tswett** [comment]
Does this mean that in CMakeLists.txt, line 7 should be changed from "FIND_PACKAGE(CUDA 5.5 REQUIRED)" to "FIND_PACKAGE(CUDA 6.5 REQUIRED)"?

**Comment by AlexBYin** [comment]
Thanks for the suggestion!
I updated CUDA version to 6.5 and it fixes the issue. 
+1 for update the CMakeLists.txt to bump up minimal version requirement since CUDA 5.5 is no longer compatible any more. I'll see if I can contribute to the change. Now sure about the procedure of CodeReview for Torch source code changes.
