### ISSUE TITLE
Dead code in torch/generic/Tensor.c

### ISSUE THREAD

**Issue by apaszke** [torch/cutorch#366]
[This piece](https://github.com/torch/cutorch/blob/master/torch/generic/Storage.c#L172-L189) is never generated, since only `THC_REAL_...` macros are defined. Also, it uses `memmove` on a CUDA pointer, so it's probably a remnant of a CPU implementation. Should I remove it or fix it?

**Comment by soumith** [comment]
prob remove it for now.
