### ISSUE TITLE
enable to require "cutorch"

### ISSUE THREAD

**Issue by mlakhal** [torch/cutorch#368]
I have installed cuda7.5 and "cutorch", but can't `require 'cutorch'`. I have tried several solutions that I've found on the web, but, with no success.
This is what I get:
`modprobe: ERROR: could not insert 'nvidia_352': No such device
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-8998/cutorch/lib/THC/THCGeneral.c line=16 error=38 : no CUDA-capable device is detected
/usr/local/share/lua/5.1/trepl/init.lua:383: cuda runtime error (38) : no CUDA-capable device is detected at /tmp/luarocks_cutorch-scm-1-8998/cutorch/lib/THC/THCGeneral.c:16
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/trepl/init.lua:383: in function 'require'
	[string "_RESULT={require 'cutorch'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/trepl/init.lua:650: in function 'repl'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406260	`

**Comment by soumith** [comment]
this is not cutorch specific, if you run the CUDA provided samples, you'll have the same error. The error is exactly what it says.
