### ISSUE TITLE
require 'cutorch' issue

### ISSUE THREAD

**Issue by ffayssal** [torch/cutorch#373]
hello guys,
I got this error when I try to do a require 'cutorch'
knowing that cuda is installed and I have a GTX 980.
and it was working for me before.
thank you.

th> require 'cutorch'
/usr/local/share/lua/5.1/trepl/init.lua:384: /usr/local/share/lua/5.1/trepl/init.lua:384: /usr/local/share/lua/5.1/cutorch/test.lua:3013: attempt to call a nil value
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/trepl/init.lua:384: in function 'require'
	[string "_RESULT={require 'cutorch'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/trepl/init.lua:651: in function 'repl'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406260

**Comment by fmassa** [comment]
You need to update `torch` as well as `nn` and `cunn`, because there was a new tester that was recently added
