### ISSUE TITLE
Tests break on luajit undefined symbol THCFloat2Half

### ISSUE THREAD

**Issue by szagoruyko** [torch/cutorch#376]
luajit terminates here:
```36/151 cudaTypeCopy .................................................... [WAIT]/opt/rocks/distro/install/bin/luajit: symbol lookup error: /opt/rocks/distro/install/lib/libTHC.so: undefined symbol: THCFloat2Half```

Update:
same happens on initiliazing HalfTensor
```
th> torch.CudaHalfTensor{8}
/opt/rocks/distro/install/bin/luajit: symbol lookup error: /opt/rocks/distro/install/lib/libTHC.so: undefined symbol: THC_float2half
```

**Comment by soumith** [comment]
hmmm, is this with CUDA 7.5 or with 7.0 / 6.5? I suspect below 7.5 and maybe some guards are missing. cc: @apaszke

**Comment by szagoruyko** [comment]
this is with 7.5

**Comment by soumith** [comment]
hmmm ok strange. let me check. if i can repro it, will revert.

**Comment by soumith** [comment]
i'm not able to reproduce :-/

**Comment by soumith** [comment]
i think i might know. it is getting libTHC.so from /opt/rocks/distro/install/lib/libTHC.so for you

**Comment by soumith** [comment]
so it is picking up the wrong libTHC.so probably?

**Comment by szagoruyko** [comment]
no able to repro on another 7.5 machine too :/ no, I keep my torch installation there, that's the right one

**Comment by szagoruyko** [comment]
```
luarocks remove --force cutorch
luarocks install cutorch
```
helped. weird stuff happening to my machines again, sorry for the false alarm
