### ISSUE TITLE
require ('cutorch') doesn't work

### ISSUE THREAD

**Issue by bentzinir** [torch/cutorch#378]
Hi, 
I recently reinstalled torch and I can't require the cutorch package. 
I am using ubuntu 14.04 and I have cuda 7.5 installed and working on the machine.

The error that I am getting is:

/home/tom/torch/install/bin/luajit: /home/tom/torch/install/share/lua/5.1/trepl/init.lua:384: /home/tom/torch/install/share/lua/5.1/trepl/init.lua:384: /home/tom/torch/install/share/lua/5.1/trepl/init.lua:384: /home/tom/torch/install/share/lua/5.1/cutorch/test.lua:3081: attempt to call a nil value
stack traceback:
	[C]: in function 'error'
	/home/tom/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	test.lua:1: in main chunk
	[C]: in function 'dofile'
	.../tom/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405e40

Thanks for the help!

**Comment by albanD** [comment]
Hi,

Could you please use the google group for installation issue please https://groups.google.com/forum/#!forum/torch7

Also following these instructions should fix your problem https://groups.google.com/forum/#!topic/torch7/wv-L-RPGcM0
