### ISSUE TITLE
Memory allocation/leak issue

### ISSUE THREAD

**Issue by buckohfive** [torch/cutorch#379]
This is a weird one, and took me a while to track down. I believe cutorch has a memory leak that survives the process ending (?!). Specifically, the memory leak happens at the time 'require "cutorch"' is executed.

Here's how I ran into the issue:

  1.  Using jcjohnson/train-rnn (or karpathy/char-rnn), train a network, any network, using a gpu (either opencl or cuda - this evidences in both)

  2.  In a terminal, run top and slabtop.

  3.  Create a loop of hundreds or thousands of sample actions (I was running 'th sample.lua -checkpoint words/20160323-0001/cv/cp_w512_d2_s3_b10_1000.t7 -start_text "hgiusdhss unwiieorw 99jsowlr4 " -length 135 -temperature 1' and comparing subtle variations in output)

  4.  Watch memory use creep up, as well as kmalloc-32 use rise. On my system, it takes about 100 sample iterations for total memory usage to creep from less than 1 GB to 8 GB, and to start using swap. In the same period of time, slabtop reports over 1.7M objects in tens of thousands of slabs for kmalloc-32.  This happens in under two minutes.

I've waited hours and days for the allocated memory to free up, and it doesn't. Luajit/Lua is not running in any way. If I let this go on long enough, Ubuntu starts killing processes due to lack of memory - eventually the system halts or I reboot it.

My system has 8 GB of RAM and a Nvidia GTX 750 Ti GPU, is running Ubuntu 15.10, and is using gcc/g++ 4.9.3 with NVIDIA 352.63, Cuda 7.5.18 and CudNN 4.0. I installed torch7 from the git repo, and installed it with alternately luajit 2.1rc1 and lua52 - both display this issue.  I also downgraded to Cuda 6.5 and CudNN 2.0, without change.

I can cause this memory leak running cutorch/test/test.lua in a similar loop. In jcjohnson/train-rnn, if I cause an error() immediately after 'require "cutorch"' the same issue occurs.  No model needs to be implemented for this leak, as far as I can tell.

Note that the memory leak is consistent - 110 kmalloc-32 objects (ish - sometimes 111, sometimes 109) of 128 bytes each, regardless of network size trained or modeled.

Testing using cuda-memcheck reveals no memory leaks.

Coding a similar network using keras with a Theano back end does not cause the same symptoms, leading me to believe this isn't inherent in the NVidia driver.

This is important to me.  During test, I often run train and sample thousands of disparate networks, and right now I have to reboot every hundred or so training sessions (not so bad) or sample runs (bad).

Thanks!
Mike

**Comment by szagoruyko** [comment]
looks like linux malloc + luajit problem. Try starting th as
```bash
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so th
```

**Comment by fmassa** [comment]
This might be related to https://github.com/torch/torch7/issues/229

**Comment by apaszke** [comment]
I ran `for x in {1..100}; do luajit -e "require 'cutorch'; cutorch.test()"; done` and there are no issues on OS X. Memory is properly reclaimed on process exit. I'll try to see how it goes on Ubuntu.

**Comment by apaszke** [comment]
No issues after 100 runs on Ubuntu without `LD_PRELOAD`. Neither `slabtop` nor `htop` report anything suspicious. Memory usage is at the same level as before.

**Comment by soumith** [comment]
I'm not able to reproduce it either. @buckohfive

**Comment by apaszke** [comment]
Hm, I think I might be running into the same issue. All tools report that I have only around 7 out of 32GB free. `htop` says that running processes have hardly any resident memory, there are only around 2GB of caches and buffers, slab usage is at around 490MB and there is another chunk of 490MB of inactive memory. I have no idea where is it used :confused:

Any ideas for other places I should check? I won't reboot the machine for some time so we can hopefully find what's going on.

Output from `/proc/meminfo`:
```
MemTotal:       32805988 kB   
MemFree:         7586876 kB   
MemAvailable:    7566940 kB   
Buffers:           10940 kB   
Cached:           275364 kB   
SwapCached:        29856 kB   
Active:           141704 kB   
Inactive:         493568 kB   
Active(anon):      88048 kB   
Inactive(anon):   470044 kB   
Active(file):      53656 kB   
Inactive(file):    23524 kB   
Unevictable:          32 kB   
Mlocked:              32 kB   
SwapTotal:       3998716 kB   
SwapFree:        1407288 kB   
Dirty:                28 kB   
Writeback:             0 kB   
AnonPages:        319004 kB   
Mapped:           192536 kB   
Shmem:            209120 kB   
Slab:             480444 kB   
SReclaimable:      51884 kB   
SUnreclaim:       428560 kB   
KernelStack:        9984 kB   
PageTables:        40164 kB   
NFS_Unstable:          0 kB   
Bounce:                0 kB   
WritebackTmp:          0 kB   
CommitLimit:    20401708 kB   
Committed_AS:    7048888 kB   
VmallocTotal:   34359738367 kB
VmallocUsed:      482680 kB   
VmallocChunk:   34359123340 kB
HardwareCorrupted:     0 kB   
AnonHugePages:     28672 kB   
CmaTotal:              0 kB   
CmaFree:               0 kB   
HugePages_Total:       0      
HugePages_Free:        0      
HugePages_Rsvd:        0      
HugePages_Surp:        0      
Hugepagesize:       2048 kB   
DirectMap4k:    31352016 kB   
DirectMap2M:     2060288 kB   
DirectMap1G:     1048576 kB   
```

**Comment by buckohfive** [comment]
What does your kmalloc-32 look like under slabtop?

**Comment by apaszke** [comment]
I have 6kk of these. Anyway, that's only 183MB, so it's still a minor fraction of all used memory. As you can see above, all slabs take around 470MB.

**Comment by apaszke** [comment]
Also, previous runs with my batch size were doing just fine, now when I try to use the same size they crash with an out of memory error (CPU side) or are killed by the kernel.

**Comment by apaszke** [comment]
Aaaaand I have 6,4kk kmalloc-32 slabs

**Comment by buckohfive** [comment]
In the past three days, I have completely started over on my test system.  Installed Ubuntu 15.10, gcc-4.8, Nvidia CUDA 7.5 from the runtime, and torch from git.  Ran the test above (for i in 100; do test.lua) and get exactly the same kmalloc-32 leak issue.

For those who could not reproduce this error, what is the difference between your test setup and mine? @apaszke is using OS X ... @soumith?

**Comment by apaszke** [comment]
@buckohfive That issue was on Ubuntu 14.04, not on OS X. I had to restart the machine, because it ran out of memory and froze.

**Comment by ton4eg** [comment]
I have the same issue on aws grid520 ubuntu 14.04

**Comment by buckohfive** [comment]
Something recently has changed, I suspect in the Nvidia drivers (no proof however).  I upgraded to Ubuntu 16.04 and Nvidia drivers 367.27, and the memory leak no longer occurs as far as I can tell.

**Comment by buckohfive** [comment]
Closing.  Issue does not evidence with latest NVidia drivers (and/or Ubuntu 16.04).
