### ISSUE TITLE
identifier "__shfl_down" is undefined

### ISSUE THREAD

**Issue by VeyDlin** [torch/cutorch#397]
Ubuntu 15.10 mate

> -- Build files have been written to: /tmp/luarocks_cunn-scm-1-4731/cunn/build
> [  2%] [  8%] [  8%] [  8%] [ 10%] [ 12%] [ 14%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialAdaptiveMaxPooling.cu.o
> [ 16%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialConvolutionLocal.cu.o
> Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_PReLU.cu.o
> Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SoftMax.cu.o
> Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_DistKLDivCriterion.cu.o
> Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_AbsCriterion.cu.o
> Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_L1Cost.cu.o
> Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_Sigmoid.cu.o
> [ 18%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SmoothL1Criterion.cu.o
> [ 20%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialAveragePooling.cu.o
> [ 22%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_VolumetricConvolution.cu.o
> [ 24%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_VolumetricAveragePooling.cu.o
> [ 26%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_BatchNormalization.cu.o
> [ 28%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SoftPlus.cu.o
> [ 30%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_VolumetricMaxPooling.cu.o
> [ 32%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_RReLU.cu.o
> [ 34%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialCrossMapLRN.cu.o
> [ 36%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_Abs.cu.o
> [ 38%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SoftMarginCriterion.cu.o
> [ 40%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_MSECriterion.cu.o
> [ 42%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialDilatedConvolution.cu.o
> [ 44%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SoftShrink.cu.o
> [ 46%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_LookupTable.cu.o
> [ 48%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialClassNLLCriterion.cu.o
> [ 50%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_TemporalConvolution.cu.o
> [ 52%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_HardTanh.cu.o
> /tmp/luarocks_cunn-scm-1-4731/cunn/lib/THCUNN/SpatialClassNLLCriterion.cu(16): error: identifier "__shfl_down" is undefined
> 
> 1 error detected in the compilation of "/tmp/tmpxft_00003a0b_00000000-6_SpatialClassNLLCriterion.cpp1.ii".
> CMake Error at THCUNN_generated_SpatialClassNLLCriterion.cu.o.cmake:266 (message):
>   Error generating file
>   /tmp/luarocks_cunn-scm-1-4731/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialClassNLLCriterion.cu.o
>

**Comment by soumith** [comment]
fixed now.
