### ISSUE TITLE
Adding -D_FORCE_INLINES for ubuntu 16.04?

### ISSUE THREAD

**Issue by hughperkins** [torch/cutorch#401]
This is either a question, or an issue, depending on the answer to the question.  I have a feb 21 fork of torch, and to get cutorch to build, I have to add the following to flags.  ie, `cd build`, `ccmake ..`, press `t` for advanced options, and change `CMAKE_CXX_FLAGS` to `-D_FORCE_INLINES`
- question: is there an existing commit somewhere (should it be in my FindCUDA???) to address this?
- if not, should there be?

References:
- http://www.eenyhelp.com/answer/bug-822783-eztrace-contrib-ftbfs-libc-2-23-memcpy-was-not-declared-scope-help-216024095.html
- https://github.com/tensorflow/tensorflow/issues/1346

**Comment by soumith** [comment]
a couple of people have reported this. i think we need to add that flag.

**Comment by hughperkins** [comment]
(tested this also on ubuntu 14.04. builds ok, and tests run ok for: torch, nn, cutorch, cunn . So I'll submit a PR onto distro for the rocks change. Though you may want to make it a bit less across-the-board possibly)
