### ISSUE TITLE
How to use CudaHalfTensor

### ISSUE THREAD

**Issue by shuzi** [torch/cutorch#403]
Hi ,  it seems CudaHalfTensor is already in the codebase.
torch.FloatTensor(5):cuda()   this will give a CudaTensor
how can I make a half tensor in a similar way , is there something like 
torch.FloatTensor(5):cuda_half() ?

**Comment by apaszke** [comment]
You're looking for `:cudaHalf()`. Still, keep in mind that CudaHalfTensors don't support most of the operations CudaTensors do (e.g. all mathematical ops).

**Comment by borisfom** [comment]
CUDNN has arithmetic for half, can we do a CUDNN-only full-featured HalfTensor ?

**Comment by apaszke** [comment]
@borisfom yes, definitely. There was already some discussion in soumith/cudnn.torch#170.

**Comment by borisfom** [comment]
How can I help moving forward ?

**Comment by apaszke** [comment]
I wasn't following after that discussion, so I guess it's best to ask @soumith, @szagoruyko, or @lukasc-ch if there was any progress.

**Comment by wickedfoo** [comment]
This is coming, I've been adding full support for CudaHalfTensor and other types over the past week or two.

**Comment by soumith** [comment]
This is now in Master.

**Comment by Atcold** [comment]
@apaszke, `cudaHalf()` does not exist.
I'm getting an `attempt to call method 'cudaHalf' (a nil value)`.

**Comment by apaszke** [comment]
[It does.](https://github.com/torch/cutorch/blob/56aa9141bdee3d3c2be21bbd601583a3b3335169/Tensor.lua#L43) I don't have a CUDA installation of torch on my laptop right now, so I can't make sure it works right now, however I'd be surprised if it wasn't.

**Comment by Atcold** [comment]
@apaszke, I can give you access to a machine with the latest Torch installation.
Actually, check your inbox 😉
