### ISSUE TITLE
Difference in the outputs of FloatTensor and CudaTensor for torch.mm

### ISSUE THREAD

**Issue by sourabhd** [torch/cutorch#407]
I am seeing difference in the outputs of matrix multiplication (torch.mm), in FloatTensor and CudaTensor. (Cuda version: 7.5, GPU: Titan X, Ubuntu 14.04 LTS)
Here is the test code along with output:
https://gist.github.com/sourabhd/f422969c00f0ea4310e8365bc2e254d6

**Comment by soumith** [comment]
i dont see a problem here. it's somewhat expected....

**Comment by sourabhd** [comment]
Can you elaborate ? The difference gets significant as the dimensions increase. Is there any alternative/workaround for accurate calculations ?

**Comment by soumith** [comment]
both are being accurate to float precision. the order of accumulations is different on CPU and GPU, that's all (and hence the difference).
