### ISSUE TITLE
Cannot build with GCC6

### ISSUE THREAD

**Issue by vzhong** [torch/cutorch#408]
Noticed this problem on Arch Linux after a recent update. `luarocks install` gives a giant log of errors that look like:

![image](https://cloud.githubusercontent.com/assets/1855260/15317270/9b6dd5de-1bd5-11e6-9a9b-a36ba7aa4ecc.png)

**Comment by soumith** [comment]
nvidia's nvcc does not support anything more than gcc 4.9 (yet).

**Comment by vzhong** [comment]
Ah ok, my mistake!
