### ISSUE TITLE
Issues installing cutorch with "luarocks install" 

### ISSUE THREAD

**Issue by btcoffma** [torch/cutorch#416]
I have CUDA toolkit 7.5 installed, but the make process fails with the following error when I run "luarocks install cutorch" from the comand line on Ubuntu 14.04:

```
-- Compiling for CUDA architecture: 2.0 2.1(2.0) 3.0 3.5 5.0 5.2
CMake Error at lib/THC/CMakeLists.txt:123 (IF):
  if given arguments:

    "OR" "NOT" "7.5" "LESS" "7.5"

  Unknown arguments specified
```

Appreciate any insight!

----

**Comment by satwikkottursc** [comment]
I had similar problems with CUDA toolkit 6.5 and 7.0 as well (re-installing torch every time I change the version).

It outputs:
```
-- Compiling for CUDA architecture: 2.0 2.1(2.0) 3.0 3.5 5.0 5.2
CMake Error at lib/THC/CMakeLists.txt:123 (IF):
  if given arguments:

    "OR" "NOT" "7.0" "LESS" "7.5"

  Unknown arguments specified
```
```
-- Compiling for CUDA architecture: 2.0 2.1(2.0) 3.0 3.5 5.0 5.2
CMake Error at lib/THC/CMakeLists.txt:123 (IF):
  if given arguments:

    "OR" "NOT" "6.5" "LESS" "7.5"

  Unknown arguments specified
```
respectively.

**Comment by genekogan** [comment]
i am also receiving this now -- only since the last commit i believe.

**Comment by ekce** [comment]
I can confirm this as well, on two different computers.

**Comment by soumith** [comment]
I'm really sorry about that. I reverted the PR that caused this!

**Comment by soumith** [comment]
Now the issue should be resolved.

**Comment by btcoffma** [comment]
Verified resolved, thanks for addressing!

**Comment by borisfom** [comment]
My bad: apparently some cmake versions react to emptry result of i${var} evaluation inside if() differently. Resubmitted fixed version: https://github.com/torch/cutorch/pull/420
