### ISSUE TITLE
invalid device ordinal problem

### ISSUE THREAD

**Issue by arwhirang** [torch/cutorch#418]
Hello, 
I came here looking for the invalid device ordinal problem appeared in ["NAMAS"](https://github.com/facebook/NAMAS) during the excution of test.sh file.

Below are the console error messages I received : 

THCudaCheck FAIL file=/root/torch/extra/cutorch/init.c line=698 error=10 : invalid device ordinal
/root/torch/install/bin/luajit: summary/run.lua:26: cuda runtime error (10) : invalid device ordinal at /root/torch/extra/cutorch/init.c:698
stack traceback:
	[C]: in function 'setDevice'
	summary/run.lua:26: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

I think the sentence below is the most important message.
/root/torch/extra/cutorch/init.c line=698 error=10 : invalid device ordinal

My system is Ubuntu 14.04 and I installed and tested samples of CUDA-7.5 with no problems.
It is weird that usual(google-searched) invalid device ordinal problem was solved by blacklisting nouveau, however, in my case, it does not work.

Any help please?

**Comment by arwhirang** [comment]
Ok.. it seems that the problem is derived from the test.sh file not from the cutorch.

**Comment by magic282** [comment]
Hi @arwhirang , I am also trying to run the summarization code and got the exactly the same error as you.
Even the command ```th summary/run.lua --help``` does not work. I also changed the code in run.lua to 
```cutorch.setDevice(0)```, still got the same error.
Could you please help about this error?

Thanks!

**Comment by arwhirang** [comment]
Hi @magic282 ! I actually solved the problem, and posted it on the url
[https://github.com/facebook/NAMAS/issues/11](url)

Thanks!
