### ISSUE TITLE
no Nvidia Device found

### ISSUE THREAD

**Issue by yadrimz** [torch/cutorch#423]
Hi, I have successfully installed NVIDIA 361 drivers, cutorch and cunn on my machine (which runs ubuntu 16.04 LTS) but I keep getting the following error: 
`th> require 'cutorch'
NVIDIA: no NVIDIA devices found
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-2188/cutorch/lib/THC/THCGeneral.c line=20 error=30 : unknown error
/home/yadrimz/torch/install/share/lua/5.1/trepl/init.lua:384: cuda runtime error (30) : unknown error at /tmp/luarocks_cutorch-scm-1-2188/cutorch/lib/THC/THCGeneral.c:20
stack traceback:
	[C]: in function 'error'
	/home/yadrimz/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	[string "_RESULT={require 'cutorch'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/yadrimz/torch/install/share/lua/5.1/trepl/init.lua:651: in function 'repl'
	...rimz/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00405d50	
                                                                      [0.0146s]
`
Does anyone know why this happens and how to fix it?
Thanks in advance.

**Comment by albanD** [comment]
Hi,

Please only use the github issues for bug.
You can ask questions on the forum https://groups.google.com/forum/#!forum/torch7

For your question, these posts should help https://groups.google.com/forum/#!search/error$2030/torch7/ZHWiE7Xz5X8/dbLGph2cEgAJ and https://groups.google.com/forum/#!searchin/torch7/(30)/torch7/DHN6oRma8BY/BX1Tsv1JBAAJ
