### ISSUE TITLE
Install  cutorch fail , " Specify CUDA_TOOLKIT_ROOT_DIR "

### ISSUE THREAD

**Issue by xiestone1992** [torch/cutorch#425]
xie@xie-K30AD-M31AD-M51AD:~$ luarocks install cutorch
Installing https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cutorch'...
remote: Counting objects: 107, done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 107 (delta 4), reused 65 (delta 1), pack-reused 0
Receiving objects: 100% (107/107), 171.38 KiB | 224.00 KiB/s, done.
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/xie/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/xie/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/xie/torch/install
CMake Error at /usr/share/cmake-3.2/Modules/FindCUDA.cmake:586 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:7 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-8899/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

---

**Operation System:**

Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily

**Things installed**

xie@xie-K30AD-M31AD-M51AD:~$ luarocks  list
## Installed rocks:

argcheck
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

audio
   0.1-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

cwrap
   scm-1 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

dok
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

env
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

fex
   0.1-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

fftw3
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

fn
   0-0 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   0-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

gnuplot
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

graph
   scm-1 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

graphicsmagick
   1.scm-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

hdf5
   20-0 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   20-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

image
   1.1.alpha-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

imgraph
   1.0-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

itorch
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

lbase64
   20120820-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

loadcaffe
   1.0-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

logroll
   0-0 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   0-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

lua-cjson
   2.1devel-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

luacrypto
   0.3.2-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

luaffi
   scm-1 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

luafilesystem
   1.6.3-2 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   1.6.3-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

luasocket
   3.0rc1-2 (installed) - /home/xie/torch/install/lib/luarocks/rocks

lub
   1.1.0-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

lzmq
   0.4.3-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

matio
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

mobdebug
   0.63-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

nn
   scm-1 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

nngraph
   scm-1 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

nnx
   0.1-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

optim
   1.0.5-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

paths
   scm-1 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

penlight
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks
   1.3.2-2 (installed) - /home/xie/.luarocks/lib/luarocks/rocks

pprint
   0-0 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   0-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

qtlua
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

qttorch
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

signal
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

sundown
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

sys
   1.1-0 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   1.1-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

threads
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

torch
   scm-1 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

totem
   0-0 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   0-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

trepl
   scm-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

util
   0-0 (installed) - /home/xie/.luarocks/lib/luarocks/rocks
   0-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

uuid
   0.2-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

xlua
   1.1-0 (installed) - /home/xie/torch/install/lib/luarocks/rocks

xml
   1.1.3-1 (installed) - /home/xie/torch/install/lib/luarocks/rocks

---

Before installing cutorch, do I need to install any other necessary thing?  

Can anyone tell me how to fix it and install cutorch?

**Comment by soumith** [comment]
did you install CUDA on your system?
https://developer.nvidia.com/cuda-downloads

**Comment by xiestone1992** [comment]
@soumith 

WOW

no one tell me to install CUDA !

I try it now.

THANK BRO.

**Comment by xiestone1992** [comment]
@soumith 
# hi, it's me, i am back now.

I already installed CUDA and try to install cutorch again.

HOWEVER, fail.  

see the following information.

xie@xie-K30AD-M31AD-M51AD:~/Downloads$ luarocks install cutorch
Installing https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cutorch'...
remote: Counting objects: 107, done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 107 (delta 4), reused 65 (delta 1), pack-reused 0
Receiving objects: 100% (107/107), 171.44 KiB | 233.00 KiB/s, done.
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/xie/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/xie/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/xie/torch/install
-- Found CUDA: /usr/local/cuda (found suitable version "7.5", minimum required is "6.5") 
-- Found gcc >=5 and CUDA <= 7.5, adding workaround C++ flags
-- MAGMA not found. Compiling without MAGMA support
-- Automatic GPU detection failed. Building for all known architectures.
-- Compiling for CUDA architecture: 2.0 2.1(2.0) 3.0 3.5 5.0 5.2
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cutorch-scm-1-8579/cutorch/build
[ 10%] [ 10%] [ 10%] [ 10%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
In file included from /usr/local/cuda/include/cuda_runtime.h:76:0,
In file included from /usr/local/cuda/include/cuda_runtime.h:76:0,
In file included from /usr/local/cuda/include/cuda_runtime.h:76:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
 #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
  ^
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
 #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
  ^
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
 #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
  ^
In file included from /usr/local/cuda/include/cuda_runtime.h:76:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
 #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
  ^
CMake Error at THC_generated_THCBlas.cu.o.cmake:206 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-8579/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:63: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at THC_generated_THCReduceApplyUtils.cu.o.cmake:206 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-8579/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:55: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o] Error 1
CMake Error at THC_generated_THCHalf.cu.o.cmake:206 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-8579/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCHalf.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:247: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o] Error 1
CMake Error at THC_generated_THCStorage.cu.o.cmake:206 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-8579/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:71: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o] Error 1
CMakeFiles/Makefile2:156: recipe for target 'lib/THC/CMakeFiles/THC.dir/all' failed
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by fmassa** [comment]
@xiestone1992 your issue is probably the same as https://github.com/torch/cutorch/issues/413

**Comment by xiestone1992** [comment]
@fmassa 
thanks for informing.
I read the #413 and tried the following solution:

cd /tmp
git clone https://github.com/torch/cutorch
cd cutorch
export CMAKE_CXX_FLAGS="-std=c++98"
luarocks install rocks/cutorch-scm-1.rockspec

-------------------------------------------------------------------------------------------
it did not work for me.   SAD

then I tried another one:


-----------------------------------------------------------------------------------------------------
xie@xie-K30AD-M31AD-M51AD:~$ sudo luarocks build ./rocks/cutorch-scm-1.rockspec
sudo: luarocks: command not found


-----------------------------------------------------------------------------------------------

it did not work .

**Comment by shuzi** [comment]
![image](https://cloud.githubusercontent.com/assets/6613848/16140667/1fdae72c-3421-11e6-91d5-e7344b0770b4.png)
same here

**Comment by soumith** [comment]
Hey minwei, the error is that it cannot find libcudart . Did you install the latest nvidia driver?
Also, are the cudart examples building? (Provided in cuda samples)

**Comment by shuzi** [comment]
@soumith   our admin recently upgrade cuda 7.0 --> 7.5
I only find libcudart.so.7.5.18  in the /usr/local/cuda/lib64
maybe because the soft link
libcudart.so ------> libcudart.so.7.5.18   is missing 
Thanks , I will speak with the Admin.

**Comment by IgnoreSilence** [comment]
@xiestone1992 
I have the same problem.Did you solve it ?

**Comment by xiestone1992** [comment]
@IgnoreSilence 

EM....I DID NOT FIX IT.

I just got a new PC, re-install ubuntu, install GPU driver and done.

I suggest you to check your GPU driver.Some of them are not supported by CUDA.

**Comment by IgnoreSilence** [comment]
@xiestone1992 
thank you～

**Comment by Demonicowl** [comment]
I updated CUDA toolkit, worked for me:/

**Comment by rraallvv** [comment]
Has anyone successfully installed cutorch on [Google Colab](https://colab.research.google.com)?

This is what I get when trying one of the options suggested in a previous post:

```
! CMAKE_CXX_FLAGS="-std=c++98" ; \
  . /content/torch/install/bin/torch-activate ; \
  luarocks install /content/torch/extra/cutorch/rocks/cutorch-scm-1.rockspec

Using /content/torch/extra/cutorch/rocks/cutorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cutorch'...
remote: Counting objects: 229, done.
remote: Compressing objects: 100% (184/184), done.
remote: Total 229 (delta 62), reused 90 (delta 43), pack-reused 0
Receiving objects: 100% (229/229), 241.83 KiB | 5.37 MiB/s, done.
Resolving deltas: 100% (62/62), done.
Warning: unmatched variable LUALIB

jopts=$(getconf _NPROCESSORS_CONF)

echo "Building on $jopts cores"
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DLUA_INCDIR=/content/torch/install/include -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/content/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/content/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$jopts install

Building on 2 cores
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /content/torch/install
CMake Error at /usr/share/cmake-3.9/Modules/FindCUDA.cmake:649 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:7 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-292/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.
```

**Comment by dufferzafar** [comment]
@rraallvv Did you find a solution to this problem? I'm trying build XGBoost with GPU support on Google Colab, but am stuck at this CUDA_TOOLKIT_ROOT_DIR error.

**Comment by rraallvv** [comment]
@dufferzafar there is a notebook [here](https://drive.google.com/file/d/14OyDrmxzBmkJ8H51iodPE2aXHzCduKJP/view?usp=sharing) that might be of some help, the related discussion is [here](https://github.com/NVIDIA/FastPhotoStyle/issues/22#event-1492603486). Cheers!

**Comment by SonicCodes** [comment]
Try this. it might help.
#for Torch with Lua 5.3:
import os
os.environ['LUA_PATH'] = '/root/.luarocks/share/lua/5.3/?.lua;/root/.luarocks/share/lua/5.3/?/init.lua;/root/torch/install/share/lua/5.3/?.lua;/root/torch/install/share/lua/5.3/?/init.lua;/root/torch/install/lib/lua/5.3/?.lua;/root/torch/install/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua'
os.environ['LUA_CPATH'] ='/root/.luarocks/lib/lua/5.3/?.so;/root/torch/install/lib/lua/5.3/?.so;/root/torch/install/lib/lua/5.3/loadall.so;./?.so'
os.environ['PATH'] += ':/root/torch/install/bin'

if 'LD_LIBRARY_PATH' not in os.environ.keys():
  os.environ['LD_LIBRARY_PATH'] = ''
else:
  os.environ['LD_LIBRARY_PATH'] += ':'
os.environ['LD_LIBRARY_PATH'] +='/root/torch/install/lib'

if 'DYLD_LIBRARY_PATH' not in os.environ.keys():
  os.environ['DYLD_LIBRARY_PATH'] = ''
else:
  os.environ['DYLD_LIBRARY_PATH'] += ':'
os.environ['DYLD_LIBRARY_PATH'] +='/root/torch/install/lib'

if 'LUA_CPATH' not in os.environ.keys():
  os.environ['LUA_CPATH'] = ''
else:
  os.environ['LUA_CPATH'] += ';'
os.environ['LUA_CPATH'] += '/root/torch/install/lib/?.so'
