### ISSUE TITLE
How to use the 'fex' package in torch ?

### ISSUE THREAD

**Issue by xiestone1992** [torch/cutorch#426]
I spent a lot of time to find out how to use the 'fex' package but no one can clearly tell me.

I saw Github wiki https://github.com/torch/torch7/wiki/Cheatsheet , the 'fex' page https://github.com/koraykv/fex , but I found nothing useful.

In the 'fex' page, There is only a simple example:
-----------------------------------------------------------------------------
Feature Extractor Library for Torch7

To use SIFT feature extractor
lena = fex.lena()
slena = fex.dsift(lena)

-------------------------------------------------------------------------

I tried it and the result is not what I expect.

I want to use SIFT or other feature detection method to find out the object contour but not object detection.

Can anyone tell me how to use the 'fex' package to detect feature points in an image?

THANKS FOR READING

**Comment by xiestone1992** [comment]
@soumith 

Can you explain the function  " fex.imshow(im,params) " to me ?

I don't understand the meaning of 'params'.  

What 's 'params'? What kind of data is it?  What is its function?

**Comment by fmassa** [comment]
@xiestone1992 this kind of question is better suited for the Google Groups https://groups.google.com/forum/#!forum/torch7
For this particular problem, `fex` main function is `dsift`, which computes dense sifts over the image, and the package doesn't do much more. The `fex.imshow` is an early version of `image.display`, but with less options.
If you want to do some image processing in torch. try [`torch-opencv`](https://github.com/VisionLabs/torch-opencv).
