### ISSUE TITLE
Multi-GPU training 

### ISSUE THREAD

**Issue by zhongzho** [torch/cutorch#434]
Hi Soumith, 

There is a multi-GPU problem, I tried to set -DISABLE_CHECK_GPU and reinstall cutorch, it does not work either. Please let me know what would help. Thanks!

using CUDA on GPU 1...
using CUDA on second GPU 2...
loading data...
done!
/home//util/torch/install/bin/luajit: /home/util.lua:46: Assertion `THCudaTensor_checkGPU(state, 4, r_, t, m1, m2)' failed. at /tmp/luarocks_cutorch-scm-1-7585/cutorch/lib/THC/THCTensorMathBlas.cu:79
stack traceback:
[C]: in function 'addmm'
/home/util.lua:46: in function 'func'
.../util/torch/install/share/lua/5.1/nngraph/gmodule.lua:333: in function 'neteval'
.../util/torch/install/share/lua/5.1/nngraph/gmodule.lua:368: in function 'forward'
train.lua:367: in function 'train_batch'
train.lua:622: in function 'train'
train.lua:871: in function 'main'
train.lua:874: in main chunk
[C]: in function 'dofile'
...util/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00406670

Cheers, 
Zhong

**Comment by zhongzho** [comment]
Hi Soumith, 

Using your other example here: 
cutorch.setDevice(1)
matrix1 = torch.CudaTensor(10):fill(1)
print(matrix1) -- printing is a synchronous call, so you dont have to explicitly call cutorch.synchronize()
cutorch.setDevice(2)
matrix2 = torch.CudaTensor(10):fill(2)
print(matrix2) 
matrix2:add(matrix1) -- matrix1 is seamlessly copied onto GPU2 and added to matrix2
print(matrix2)

I have the following error
th> matrix2:add(matrix1)
[string "_RESULT={matrix2:add(matrix1) }"]:1: Assertion `THCTensor_(checkGPU)(state, 3, self_, src1, src2)' failed.  at /home/util/cutorch/lib/THC/generic/THCTensorMathPointwise.cu:8
stack traceback:
        [C]: in function 'add'
        [string "_RESULT={matrix2:add(matrix1) }"]:1: in main chunk
        [C]: in function 'xpcall'
        .../util/torch/install/share/lua/5.1/trepl/init.lua:651: in function 'repl'
        ...util/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
        [C]: at 0x00406670

Thank you! 

Cheers, 
Zhong

**Comment by soumith** [comment]
hi @zhongzho . To make the above example work, you have to modify it like this:

```lua
require 'cutorch'
cutorch.setDevice(1)
matrix1 = torch.CudaTensor(10):fill(1)
print(matrix1) -- printing is a synchronous call, so you dont have to explicitly call cutorch.synchronize()
cutorch.setDevice(2)
matrix2 = torch.CudaTensor(10):fill(2)
print(matrix2) 
matrix2:add(matrix1:clone()) -- matrix1 is seamlessly copied onto GPU2 and added to matrix2
print(matrix2)
```

If you want to disable cross-GPU checks, you have to add this line:
```bash
cutorch.setKernelPeerToPeerAccess(true)
```

So the final example is:

```lua
require 'cutorch'
cutorch.setKernelPeerToPeerAccess(true)
cutorch.setDevice(1)
matrix1 = torch.CudaTensor(10):fill(1)
print(matrix1) -- printing is a synchronous call, so you dont have to explicitly call cutorch.synchronize()
cutorch.setDevice(2)
matrix2 = torch.CudaTensor(10):fill(2)
print(matrix2) 
matrix2:add(matrix1) -- matrix1 is seamlessly copied onto GPU2 and added to matrix2
print(matrix2)
```
