### ISSUE TITLE
CUDA driver version is insufficient

### ISSUE THREAD

**Issue by pefi9** [torch/cutorch#435]
Hi,

I would need an advice how to make run cutorch. 
I have mac osx El Capitan and external GPU GTX 980ti. 
Installed Nvidia driver : http://www.nvidia.com/object/macosx-cuda-7.5.29-driver.html
Nvidia Cuda toolkit: https://developer.nvidia.com/cuda-downloads
Used luarocks for installing cunn and cutorch which outputted :

-- **Found CUDA: /usr/local/cuda (found suitable version "7.5", minimum required is "6.5")** 

However when I run 'require cunn' I receive this error:

THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-5612/cutorch/lib/THC/THCGeneral.c line=20 error=35 : **CUDA driver version is insufficient for CUDA runtime version**
/Users/petrfiala/torch/install/bin/lua: ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:384: ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:384: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-5612/cutorch/lib/THC/THCGeneral.c:20

**Comment by mryellow** [comment]
I was getting those with Debian Bumblebee and hybrid Optimus card. When running with the driver included in `bumblebee-nvidia` it would fail with that error, although the version number is sufficient. 

It worked when I uninstalled everything and installed the Nvidia driver included in the CUDA run file installer, although this driver was older and had some ugly screen tearing issues. Apparently you could get it working with Bumblebee, but involves using that official driver and putting up with Bumblebee not automatically turning it off when finished.

**Comment by jameh** [comment]
I'm hitting this roadblock on Mac OSX El Capitan (10.11.6). My GPU is a NVIDIA 9600m. I'm running the command:

```bash
$ th -e "require 'cutorch'"
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-9157/cutorch/lib/THC/THCGeneral.c line=20 error=35 : CUDA driver version is insufficient for CUDA runtime version
...torch/install/share/lua/5.1/trepl/init.lua:384: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-9157/cutorch/lib/THC/THCGeneral.c:20
```

I had installed CUDA 7.5 and driver from https://developer.nvidia.com/cuda-downloads

Check CUDA driver status

```bash
$ kextstat | grep -i cuda
  132    0 0xffffff7f82537000 0x2000     0x2000     com.nvidia.CUDA (1.1.0) 5AFE550D-6361-3897-912D-897C13FF6983 <4 1>
```

Check version of nvcc

```bash
$ cd /Developer/NVIDIA/CUDA-7.5/bin 
$ ./nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Apr_11_13:23:40_CDT_2016
Cuda compilation tools, release 7.5, V7.5.26
```

Compile and run sample CUDA application
```bash
$ cd /Developer/NVIDIA/CUDA-7.5/samples
$ sudo make -C 0_Simple/vectorAdd
Password:
/Developer/NVIDIA/CUDA-7.5/bin/nvcc -ccbin clang++ -I../../common/inc  -m64  -Xcompiler -arch -Xcompiler x86_64  -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -o vectorAdd.o -c vectorAdd.cu
/Developer/NVIDIA/CUDA-7.5/bin/nvcc -ccbin clang++   -m64  -Xcompiler -arch -Xcompiler x86_64  -Xlinker -rpath -Xlinker /Developer/NVIDIA/CUDA-7.5/lib  -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -o vectorAdd vectorAdd.o
mkdir -p ../../bin/x86_64/darwin/release
cp vectorAdd ../../bin/x86_64/darwin/release
$ ./bin/x86_64/darwin/release/vectorAdd
[Vector addition of 50000 elements]
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
```
Compilation works, fails during runtime with same error as above.

Download latest driver from [here](http://www.nvidia.com/object/mac-driver-archive.html) (7.5.30 at time of writing) and reboot - I'll continue this comment after my reboot

**Comment by wanghaisheng** [comment]
same here  need help

**Comment by jameh** [comment]
I wrote to NVIDIA about this error, and they wrote me back:

> Last comment from NVIDIA (Kevin Kang - 08/03/2016 3:07 AM):
> Hi Jamie,

> Thanks for the reporting!

> As noted in CUDA 6.0 release notes below(in "Chapter 3. Unsupported Features), the GPU based on "MacBook Pro Mid 2009" is not supported any more from the CUDA 6.0 toolkit and r331 driver.

> To continue developing or running CUDA applications, please use the CUDA 5.5 toolkit or r319 driver, as appropriate. Sorry for the inconvenience.

> http://developer.download.nvidia.com/compute/cuda/6_0/rel/docs/CUDA_Toolkit_Release_Notes.pdf

So, check the release notes linked, and use an earlier version if your chipset is not supported. The error message could be more clear, lol.

**Comment by jameh** [comment]
Well, I'm getting compiler errors when using CUDA 5.5 toolkit, 5.5.28 CUDA driver installed from the 10.9 pkg on OSX 10.11.6 El Capitan. I guess I wouldn't expect that to work anyway. There might be a way to use a legacy version of `clang` that would fix this issue? I might try in a bit... I don't want to downgrade my OS for CUDA compatibility...

**Comment by jameh** [comment]
But maybe close this bug since it is not an issue with cutorch, rather an issue with CUDA chipset support

**Comment by aug2uag** [comment]
Can cltorch be run without CUDA only on OpenCL ? I'm looking through docs now

**Comment by Mina1368** [comment]
Hi Jameh,

Did you fix this problem, I have the same error!

Thank You!

**Comment by pixelou** [comment]
Same error here: nvidia samples and theano both work perfectly on the same setup.

**Comment by MaffooBristol** [comment]
My nvidia samples work fine; `luarocks install cutorch` works fine (even says `Found CUDA: /Developer/NVIDIA/CUDA-7.5 (found suitable version "7.5", minimum required is "6.5")`); but then this error still occurs when trying to use char-rnn or the like

**Comment by raftx24** [comment]
same issue!

**Comment by brando90** [comment]
someone know how to solve this for pytorch?
