### ISSUE TITLE
x:sum() and x:cuda():sum() not equal

### ISSUE THREAD

**Issue by aaron-xichen** [torch/cutorch#444]
Sorry I am new to torch, and I found these two examples, which really confuse me so much. As far as I known, the output should be equal, shouldn't they?

```
x = torch.FloatTensor(3, 3):uniform(-1, 1)
print(x:sum())
print(x:cuda():sum())
--output -1.787772808224	
--output -1.7877726554871	

y = torch.CudaTensor(3, 3):uniform(-1, 1)
print(y:sum())
print(y:float():sum())
--output -1.2519686222076	
--output -1.2519686818123
```

**Comment by fmassa** [comment]
This behaviour is expected. Check the non-associativity of floating points in https://en.m.wikipedia.org/wiki/Floating_point in the accuracy tab for an explanation.

**Comment by aaron-xichen** [comment]
Thanks, but x is float32 and x:cuda() is also float32, it is normal that they are different? If so, it means that convert float data from cpu to gpu is not identical?

**Comment by fmassa** [comment]
The order of the summation is not the same in cuda and in cpu. Converting to cuda doesn't change its value.

**Comment by aaron-xichen** [comment]
I see, thanks so much!
