### ISSUE TITLE
Install torch with cuda 8 on ubuntu 16.04

### ISSUE THREAD

**Issue by codevui** [torch/cutorch#448]
I try to install torch on ubuntu 16.04 with cuda 8 and got fails with "./install.sh"
detail:
Found CUDA on your machine. Installing CUDA packages
Warning: unmatched variable LUALIB
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/lucky/Workspace/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/lucky/Workspace/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- Found Torch7 in /home/lucky/Workspace/torch/install
-- MAGMA not found. Compiling without MAGMA support
-- Autodetected CUDA architecture(s): 
-- got cuda version 8.0
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lucky/Workspace/torch/extra/cutorch/build
[  2%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
[  5%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
[  7%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
[ 10%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
[ 12%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
[ 15%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
[ 20%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
In file included from /usr/local/cuda-8.0/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda-8.0/include/host_config.h:114:2: error: #error -- unsupported GNU version! gcc versions later than 5.3 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5.3 are not supported!
  ^
In file included from /usr/local/cuda-8.0/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda-8.0/include/host_config.h:114:2: error: #error -- unsupported GNU version! gcc versions later than 5.3 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5.3 are not supported!
  ^
In file included from /usr/local/cuda-8.0/include/cuda_runtime.h:78:0,
                 from <command-line>:0:

Does anyone have solutions ?

**Comment by soumith** [comment]
Please read the error message.

> #error -- unsupported GNU version! gcc versions later than 5.3 are not supported!

**Comment by zhangxiangxiao** [comment]
I always edit out that line in /usr/local/cuda-8.0/include/host_config.h and replace
` #error -- unsupported GNU version! gcc versions later than 5.3 are not supported!`
with
` #warning -- unsupported GNU version! gcc versions later than 5.3 are not supported!`

It's a ugly hack but has always worked well for me. I have been using Fedora and kept my gcc version the latest always.

**Comment by atique81** [comment]
hi @codevui , 
were you finally able to install torch with cuda 8?

**Comment by codevui** [comment]
@atique81 Official cuda 8 has been released, and work with torch without extra jobs.
