### ISSUE TITLE
Latest changes broke Half

### ISSUE THREAD

**Issue by borisfom** [torch/cutorch#463]
Here's what I am getting now, on both Pascal and Maxwell.
I believe those actually uncover larger issue ; there should be CPU type HalfTensor with type half (Also HalfStorage etc). 
@soumith : if you are not on it already, I would like to take a stab on it.

th -lcutorch -e "cutorch.test()"
seed:   1470949968
Running 154 tests
  1/154 tan2 ............................................................ [PASS]
 ...
  8/154 acos2 ........................................................... [PASS]
  9/154 zero ............................................................ [ERROR]
 10/154 logNormal ....................................................... [PASS]
... 
 18/154 sign1 ........................................................... [PASS]
 19/154 min ............................................................. [ERROR]
 20/154 prod ............................................................ [PASS]
... 
 37/154 cudaTypeCopy .................................................... [PASS]
 38/154 cmul ............................................................ [ERROR]
 39/154 streamBarrier ................................................... [PASS]
... 
 56/154 cosh1 ........................................................... [PASS]
 57/154 csub ............................................................ [ERROR]
 58/154 index ........................................................... [PASS]
 59/154 log1p2 .......................................................... [PASS]
 60/154 viewAs .......................................................... [PASS]

**Comment by soumith** [comment]
I'm on it, along with: #461

**Comment by soumith** [comment]
fixed now

**Comment by borisfom** [comment]
Thanks @soumith! How about "there should be CPU type HalfTensor with type half (Also HalfStorage etc). " part - that's what I meant to take a stab on! I will open another issue - please let me know if you are on that one, too :)

**Comment by soumith** [comment]
i dont see a reason for putting a humongous effort on CPU HalfTensor. We dont have native CPU instruction types for half, and compared to the effort needed, I dont see how we will benefit from it.

**Comment by borisfom** [comment]
What effort? There is already emulation libraries we can just reuse. What I am worried about is not to improve CPU calculations efficiency, but to avoid any unnecessary conversions. Are you sure now when in GPU mode, half is not being converted to and from float just to be passed between layers etc. ?

**Comment by borisfom** [comment]
And on TX1, gcc actually does have native instructions (well, __fp16 is a storage-only type, but still, no conversion necessary).

**Comment by soumith** [comment]
It's a substantial effort (actually writing it without any dependencies, writing unit tests, etc.). If you want to take a crack at it, feel free to. I just dont see any benefits to do this on the CPU.

**Comment by borisfom** [comment]
Also, 'short float' will be a new fundamental type in C++ (and hopefully, C)  2020: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2016.pdf

**Comment by borisfom** [comment]
Thanks Soumith! As I said, I don't really care about CPU operations cost. But I would really like to see fp16 passed around without any conversions.
