### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by xternalz** [torch/cutorch#464]
I encountered  these errors with the latest commit [https://github.com/torch/cutorch/commit/5511782637984f521597c9aaa078cc1ee5d4a49f](https://github.com/torch/cutorch/commit/5511782637984f521597c9aaa078cc1ee5d4a49f)

> /tmp/luarocks_cutorch-scm-1-5347/cutorch/lib/THC/THCTensorMathPairwise.cu(81): error: "fval" is not a nonstatic data member or base class of class "TensorSubConstantOp<half>"
> 
> /tmp/luarocks_cutorch-scm-1-5347/cutorch/lib/THC/THCTensorMathPairwise.cu(81): error: "TensorSubConstantOp<half>::TensorSubConstantOp(half)" provides no initializer for:
>             const member "TensorSubConstantOp<half>::val"

**Comment by soumith** [comment]
hmmm, seems to build fine for me. what CUDA version are you on?

nvcc --version

**Comment by xternalz** [comment]
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2016 NVIDIA Corporation
> Built on Wed_May__4_21:01:56_CDT_2016
> Cuda compilation tools, release 8.0, V8.0.2

**Comment by soumith** [comment]
cc: @apaszke

**Comment by soumith** [comment]
sorry about that, fixed via: https://github.com/torch/cutorch/commit/19310cc29dec76d2fc93e55bce5bb367a003be5ba

**Comment by soumith** [comment]
didn't notice it because the builds were being tested on CUDA 7.5
