### ISSUE TITLE
nn.Max

### ISSUE THREAD

**Issue by shuzi** [torch/cutorch#468]
In the latest version I got following error
![image](https://cloud.githubusercontent.com/assets/6613848/17679440/6c500ada-6309-11e6-84ea-7bb0a2bcd6b9.png)
how should I use nn.Max in the latest version?

The old version still works.

**Comment by szagoruyko** [comment]
there is indeed a problem, we should keep `_indices` as a `torch.CudaLongTensor`

**Comment by shuzi** [comment]
I want to use previous version for the time being.
two branches : 1.0-0  and 1.0    which one I should use?

**Comment by soumith** [comment]
1.0-0

**Comment by jayleicn** [comment]
The same issue is also in nn.Min():cuda,  as is shown below
![image](https://cloud.githubusercontent.com/assets/15768405/17715318/27c79b92-63c9-11e6-8443-f25729b624ca.png)

**Comment by jayleicn** [comment]
Early version of cutorch works fine for nn.Min() and nn.Max(). If there is anyone else who want to use this temporarily, try the following command

```bash
git clone https://github.com/torch/cutorch.git
cd cutorch
git checkout aa9dd6e08ac3d5aea5643ef26f2fcf10d9b076a6
luarocks make rocks/cutorch-scm-1.rockspec
```

**Comment by soumith** [comment]
sorry for the delay in fixing this guys. had been not near my computer last 2 days. fixing it now.

**Comment by soumith** [comment]
see https://github.com/torch/nn/pull/933 for fix.

**Comment by soumith** [comment]
pulling in the latest nn fixes this. sorry about overlooking this. I'll add tests for nn.Min / nn.Max now as well, looks like there are none in cunn.
