### ISSUE TITLE
squeeze not defined

### ISSUE THREAD

**Issue by xdever** [torch/cutorch#472]
:squeeze() is undefined for all cuda tensor types except torch.CudaTensor(). For example:
```
torch.CudaLongTensor():squeeze()
```
fails with `attempt to call method 'squeeze' (a nil value)`

**Comment by blackyang** [comment]
Similar problem here. cutorch version:
```
commit 6d4e3c2132dba27874dcac0585dc532940a93edd
Merge: 19310cc 2c22745
Author: Soumith Chintala <soumith@gmail.com>
Date:   Sat Aug 13 00:46:46 2016 -0400
```

torch.CudaByteTensor() also miss lots of methods, e.g. :index(), :scatter(), :expandAs()

**Comment by soumith** [comment]
@blackyang  :index(), :scatter(), :expandAs() are existing for torch.CudaByteTensor in the current master commit. I added them.

**Comment by soumith** [comment]
@xdever added squeeze in master now.

**Comment by blackyang** [comment]
@soumith  thank!

**Comment by xdever** [comment]
thanks!
