### ISSUE TITLE
require 'cutorch' takes long time

### ISSUE THREAD

**Issue by DmitryUlyanov** [torch/cutorch#475]
Hello, can you please explain why the initialization  takes so long? 

![](https://s4.postimg.io/t470u877v/Screenshot_from_2016_08_20_08_08_29.png)

Previously, I noticed, that it takes long only when there are no GPU processes at all. In this case even `nvidia-smi` works quite long. So I was opening torch with `require cutorch` and moving it to background, so there was always something on GPU. In this case all other torch scripts required cutorch fast. But now this trick does not work. I also moved to different server, so it can be the reason, but can you please specify, maybe there is a way not to wait for 10 sec every time?  

I updated torch and cutorch just yesterday.

Thank you.

**Comment by szagoruyko** [comment]
it takes so long because of https://github.com/torch/cutorch/pull/431
takes less than 2s if you start it with CUDA_VISIBLE_DEVICES=0.

**Comment by DmitryUlyanov** [comment]
@szagoruyko 5 sec for me :( Hope it will be better in CUDA 8.0. Thank you!

**Comment by soumith** [comment]
i'm working on somewhat fixing it this week by lazy initializing devices in cutorch.
