### ISSUE TITLE
Weird nvidia-smi behaviour

### ISSUE THREAD

**Issue by DmitryUlyanov** [torch/cutorch#478]
I do not have anything but torch to prove that it is related to torch, so I ask if it reproduces on your system. 

Issue: if I run process with `CUDA_VISIBLE_DEVICES=0` `nvidia-smi` does not show the `GPU-Util` load for the GPU. 

Without setting device: 
![](https://s14.postimg.io/6hmzeoaox/image.png)

With:
![](https://s13.postimg.io/5tmwrb9ev/image.png)

Setup: torch and cutorch from master branch, latest cuda and drivers for Titan X, ubuntu 14.04.

**Comment by soumith** [comment]
Hi dimitry. This seems like correct behavior...

**Comment by DmitryUlyanov** [comment]
Why is it? At least it was not working like that until recently. 

More, if in the second case I do `th -e "require 'cutorch'"` in other tab, I immediately see correct GPU-Util in `nvidia-smi`.

**Comment by apaszke** [comment]
What you see in `nvidia-smi` is correct. When specifying `CUDA_VISIBLE_DEVICES` you're constraining cutorch to work only on these GPUs. It won't allocate a single byte on any others.

**Comment by DmitryUlyanov** [comment]
@apaszke But the question is not about memory, look at `GPU-Util` column. In both cases GPU is working, but in the second case you don't see it.

**Comment by apaszke** [comment]
It's just a momentary load estimate. Try running `nvidia-smi` a couple times and it will probably keep giving you different results.

**Comment by DmitryUlyanov** [comment]
@apaszke no, always 0%

**Comment by soumith** [comment]
Oh if its about gpu-util, then no idea. I thought you were asking about Memory usage. We didn't change anything that would affect that on our side

**Comment by soumith** [comment]
I suspect an nvidia tooling bug

**Comment by DmitryUlyanov** [comment]
Thanks! I'll try to reinstall everything.
