### ISSUE TITLE
Better integration of CudaHalfTensor proposal

### ISSUE THREAD

**Issue by jorditg** [torch/cutorch#484]
Hi,

I'm trying to port my FP32 models to FP16 in torch and I'm finding some problems doing it. 
I propose a minor modification of the Cuda types, doing something similar of the done in the nn package: renaming the CudaTensor to CudaFloatTensor and using CudaTensor as a default type with initial value equal to CudaFloatTensor. We could create a function like setdefaultcudatensortype() to switch CudaTensor to other types like for example CudaHalfTensor. In this way, using the :cuda() function present in other packages would make the transformation easier, maintaining the backward compatibility.

I've tried to post a modification of the code but I have some compilation issues due to my lack of understanding of the automatically generated code scripts.

**Comment by soumith** [comment]
Hi Jordi,

The plan is not too unreasonable except for two changes that break existing code. torch.type will now break depending upon setdefaultcudatensortype.
The semantics around :cuda() are now unclear...

**Comment by borisfom** [comment]
Why  setdefaultcudatensortype ? As soon as we have working HalfTensor, setdefaulttensortype should be sufficient - @soumith please confirm you are working on that one!

**Comment by borisfom** [comment]
@soumith: can you please confirm HalfTensor is in the making? I have opened related issue here: https://github.com/torch/cutorch/issues/492

**Comment by soumith** [comment]
@borisfom we could introduce a cpu torch.HalfTensor i guess, but with just a copy function and constructor. It makes sense.

**Comment by borisfom** [comment]
@soumith: Yes absolutely, to avoid conversion when passing parameters at least. Also, on ARM (TX1) , __fp16 is fully supported on CPU (storage-only).
Do you want me to do a pass on it or would you rather do it yourself ?

**Comment by borisfom** [comment]
@jorditg, @soumith: check out https://github.com/torch/torch7/pull/826, https://github.com/torch/cutorch/pull/578
