### ISSUE TITLE
nn.LookupTable - cannot convert THCudaTensor to THCudaLongTensor

### ISSUE THREAD

**Issue by dDua** [torch/cutorch#485]
In the latest version I got following error
![lookuptable_issue](https://cloud.githubusercontent.com/assets/5347217/17984354/b5b54064-6ade-11e6-9701-6ad1db14b069.png)

Can you please let me know what is wrong with this usage?

Thanks,
Dheeru

**Comment by shuzi** [comment]
I have the same problem.  The LookupTable in latest Torch does not work anymore.

![image](https://cloud.githubusercontent.com/assets/6613848/17985159/90b381d2-6ae2-11e6-9db5-d4e9030fede1.png)

**Comment by soumith** [comment]
for now pass your input tensor as cudaLong. I am fixing it in master with some unit tests:

```
output = nn.LookupTable(10,2):cuda():forward(torch.Tensor{2, 3}:cudaLong())
nn.LookupTable(10, 2):cuda():backward(torch.Tensor{2,3}:cudaLong(), output)
```

**Comment by soumith** [comment]
actually, @shuzi and @dDua your test case is wrong.

This works fine:

```lua
require 'cunn'
m=nn.LookupTable(10,2)
input = torch.Tensor{2, 3}:cuda()
output = m:cuda():forward(input)
m:backward(input, output:clone())
```

```lua
require 'cunn'
require 'rnn'
m=nn.LookupTableMaskZero(10,2)
input = torch.Tensor{2, 3}:cuda()
output = m:cuda():forward(input)
m:backward(input, output:clone())
```

**Comment by soumith** [comment]
@dDua i think you have to reinstall nn and cunn

**Comment by dDua** [comment]
Thanks @soumith  for your reply. Even after reinstalling nn and cunn I get the same error. I did a fresh installation of torch as well still I can reproduce this error. Any idea as to why that might be happening?

**Comment by soumith** [comment]
@dDua did you try my test? Does my test fail?

**Comment by soumith** [comment]
Also, can you switch the inputs to LookupTable to cudaLong() instead of cuda()? (Though it's not necessary)

**Comment by dDua** [comment]
Thanks Soumith. This works now. I had to reinstall cutorch as well.
