### ISSUE TITLE
A very strange problem about indexing cuda tensor.

### ISSUE THREAD

**Issue by lymhust** [torch/cutorch#493]
The time of indexing a cuda tensor changes significantly after call the forward function of an arbitrary neural network. Here is my code:

```
tensor = torch.CudaLongTensor(20)

-- Calculate the time
sys.tic()
a = tensor[1]
print('Time: '..(sys.toc()*1000)..'ms')

-- Call an arbitrary NN
input = torch.CudaTensor(1,3,48,48)
model:forward(input)

-- Calculate the time again
sys.tic()
a = tensor[1]
print('Time: '..(sys.toc()*1000)..'ms')
```
Result is very strange:
Time: 0.5948ms
Time: 27.2789ms

Can anybody provide me some help about this problem? Thanks!

**Comment by albanD** [comment]
Hi,

When using a GPU, we make as much use as possible of the asynchronousity of the GPU.
So `model:forward(input)` is actually an asynchronous call that return before the forward pass ends.
But to be able to access a Tensor, we want to make sure that you are reading the proper data, so we wait for the computations to be finished.
If you add a `cutorch.synchronize()` just after the `forward` call and before the `sys.tic()`, the time for accessing will be the same as before.

**Comment by lymhust** [comment]
Thanks so much for your reply. Your solution is perfect!
