### ISSUE TITLE
Inverse produces integers for large matrices

### ISSUE THREAD

**Issue by jonathanasdf** [torch/cutorch#507]
In particular, for anything larger than 16x16.

```
-- No cuda, works fine.
m = torch.rand(17, 17)
print(torch.inverse(m))
print(torch.trace(m*torch.inverse(m)))

require 'cutorch'
m = torch.rand(17, 17):cuda()
print(torch.inverse(m))
print(torch.trace(m*torch.inverse(m)))
```

**Comment by sefira** [comment]
I meet the same problem. 
I just trans cuda into float before inverse() like this: torch.inverse(m:float()):cuda()

**Comment by soumith** [comment]
i investigated this. it seems like a bug in cublas. 
While I find a workaround for this, If you install torch with MAGMA support, you wont see this issue.

**Comment by sefira** [comment]
installing MAGMA and reinstalling cutorch really works, thanks a lot!

**Comment by soumith** [comment]
fixed on master!
