### ISSUE TITLE
Is it possible to read data of a CudaTensor from its pointer?

### ISSUE THREAD

**Issue by suryabhupa** [torch/cutorch#523]
If I have multiple matrix multiplies that I want to parallelize over different streams, my methodology has been as such:

1) Create tensor (a = torch.rand(5, 5):cuda())
2) Get pointer (aptr = torch.data(torch.rand(5, 5):contiguous(), false)
3) Move pointer to another class, that aggregates pointers together, dispatches them to a local CUBLAS C library, where the computation is done in parallel, or with batched_gemm, and the answer is written to a pointer that the Lua code knows about.

However, I'm getting segmentation faults or "Command terminated" whenever I access these pointers. Is it possible that the pointers are getting garbage collected, or otherwise just unknown?

**Comment by suryabhupa** [comment]
In other words, is there a way to get the GPU pointer of a CudaTensor, or should I just default to using cutorch and not write my own local CUBLAS library?

**Comment by albanD** [comment]
I don't know exactly what you're doing but given your example, `aptr` is definitely not valid.
Since you keep no reference to the Tensor you create with `torch.rand`, it is garbage collected and `aptr` points to a garbage collected object.
I don't know what else you're trying to do so there can be other problems somewhere.

Why do you want to write your own CUBLAS library? This is already what `cutorch` is using for every tensor operation.

**Comment by suryabhupa** [comment]
My mistake, I meant to say aptr = torch.data(a, false). Would aptr still be invalid? 

The problem I'm having is that I have a n-ary tree-based model and I want to parallelise multiplies that happen at each depth, because these are independent. I was thinking of taking my model, collecting the pointers for input, weight, bias, and output and passing these to a batched_gemm call or to multiple streams in CUBLAS. However, I was finding that the pointers I was collecting seemed to lead to invalid memory locations.

**Comment by albanD** [comment]
In this case I think the pointer would be valid as long as `a` is in the scope.

Then again why don't you use the [`baddbmm`](https://github.com/torch/torch7/blob/master/doc/maths.md#res-torchbaddbmmres-v1-m-v2-batch1-batch2) method directly?  If you look in `cutorch`, it is implemented with the batched gemm from cublas ([here](https://github.com/torch/cutorch/blob/90322051782cb01c8905def414b41708aa376075/lib/THC/THCBlas.cu#L311-L314)).

**Comment by suryabhupa** [comment]
I'm under the (probably wrong) impression that passing these raw pointers to CUBLAS would lead to some marginal performance gain, but I'm open to suggestions that make life easier/faster. 

I may end up using the baddbmm method from cutorch. Do you have any heuristics about whether batched_gemm or using multiple streams would be faster? The matrix multiplies have minimum size (1 x 256) x (256 x 256), but can be as large as (1 x 1024) x (1024 x 1024). 

Lastly, now out of curiosity, is there any reasonable way to get the GPU pointer of a CudaTensor? For example, something like this fails:

```
a = torch.rand(5, 5):cuda()
aptr = torch.data(a, false)
print(a) -- this will work because Torch will copy the tensor to the CPU to print
for i=0,24 do
  print(aptr[i])
end -- this does not work presumably because I can't access GPU pointers the same way I access CPU pointers
```

**Comment by soumith** [comment]
b*mm* are always faster than manually overlapping with streams. They call cublasEx API that does batching in the implementation directly.

There's no way to get the GPU pointer and access it from a CPU instruction.
to get the gpu pointer:

a = torch.randn(5,5):cuda()
a_ptr = a:data()

print(a_ptr[0]) # WILL FAIL.
