### ISSUE TITLE
MAGMA 2.1 + Torch installation failed

### ISSUE THREAD

**Issue by DmitryUlyanov** [torch/cutorch#532]
Hello, I try to build torch with magma support. Downloaded the latest MAGMA version and installed it with CMake (although it is recommended to configuring with make.inc).

When I install torch I get 

```
Linking CXX shared library libTHC.so
/usr/bin/ld: /usr/local/lib/libmagma.a(error.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmagma.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/THC/libTHC.so] Error 1
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
```

What can be the problem? Thank you!

**Comment by soumith** [comment]
when you compile magma, you have to compile it with -fPIC flag. 

this is what i used against magma 2.1.

First apply this patch to CMakeLists.txt: https://gist.github.com/soumith/3f01555f6b90b5029521c0652094181d

Then build using:

```bash
mkdir build
cd build
cmake .. -DUSE_FORTRAN=OFF -DGPU_TARGET="All" -DCMAKE_INSTALL_PREFIX=$PREFIX
make -j40
make install
cd ..
```

**Comment by DmitryUlyanov** [comment]
Thank you @soumith! Super fast answer.

**Comment by soulslicer** [comment]
How do you do this for Magma 2.3?
