### ISSUE TITLE
Odd inconsistent resize() behavior with CudaTensors

### ISSUE THREAD

**Issue by suryabhupa** [torch/cutorch#536]
The following behavior is exhibited in the lua interactive shell:
```
require 'cutorch'

weight1 = torch.rand(6, 6)
a = torch.CudaTensor()
a:resize(weight1:size(1))
```
results in:
```
 0.0767
-0.6191
-0.1262
-0.2997
 1.2027
 0.1726
[torch.CudaTensor of size 6]
```
however, if we try to do the same with another tensor, we get a different result:
```
b = torch.CudaTensor()
b:resize(weight1:size(1))
```
which results in:
```
 0
 0
 0
 0
 0
 0
[torch.CudaTensor of size 6]
```
If we create a few more CudaTensors like this, we sometimes get a tensor of 0's, and sometimes a tensor of random floats. Is this expected? It seems like for other kinds of tensors, they are always 0 initialized.

**Comment by soumith** [comment]
you are looking at uninitialized memory. You're lucky that they are 0s sometimes

**Comment by suryabhupa** [comment]
Ah okay, this is expected behavior then. Thanks!
