### ISSUE TITLE
torch.ByteTensor and nonzero() method

### ISSUE THREAD

**Issue by SergeyMalashenko** [torch/cutorch#538]
Can I apply nonzero() method to torch.ByteTensor object? or do I need to convert to torch.FloatTensor at first?

**Comment by fmassa** [comment]
Yes, you can apply `nonzero` to `torch.ByteTensor`s.

**Comment by SergeyMalashenko** [comment]
Ok. Can I apply the same method to torch.CudaByteTensor?

**Comment by fmassa** [comment]
There is unfortunately no `nonzero()` implementation for CUDA yet (just realized the issue was opened in the `cutorch` repo)

**Comment by JoostvDoorn** [comment]
Some time ago @soumith mentioned that Facebook implemented nonzero for CUDA in #70

**Comment by soumith** [comment]
this is now pushed into master
