### ISSUE TITLE
THCCachingAllocator does not always work with sharedserialize'd threads

### ISSUE THREAD

**Issue by ngimel** [torch/cutorch#539]
A situation that arises, e.g.,  when using optnet + DataParallelTable + THC_CACHING_ALLOCATOR, minimum example with comments below:
```lua
      require 'cunn'
      require 'cutorch'
      require 'cudnn'
      local nGPU = 2
      --allocate something
      local a = torch.CudaTensor(1000,1000):fill(1)
      --create a simple model
      local model = nn.Sequential()
      local l1 = cudnn.SpatialConvolution(32,32,3,3)
      model:add(l1)
      model:cuda()
      local input = torch.CudaTensor(32,32,14,14)
      --prop model forward, as in optnet      
      local out = model:forward(input)
--now, wrap model in dpt   
      local gpus = torch.range(1, nGPU):totable()
      local fastest, benchmark = cudnn.fastest, cudnn.benchmark

      local dpt = nn.DataParallelTable(1, true, true)
         :add(model, gpus)
         :threads(function()
            local cudnn = require 'cudnn'
            cudnn.fastest, cudnn.benchmark = fastest, benchmark
         end)
--at this point, there are 3 THCCachingAllocators, and they do not share allocated_blocks      
--and there are 3 lua_States that share storages due to sharedserialize, 
--so storage from the main thread can be garbage-collected in the spawned thread
--which has its own THCCachingAllocator and won't find this storage in its allocated_blocks
--leading to cudaError. 
      dpt.gradInput = nil
      model = dpt:cuda()
      model:forward(input)
```
when run with THC_CACHING_ALLOCATOR set to 1, the output is
THCudaCheck FAIL file=/workspace/ALL/torch-distro/extra/cutorch/lib/THC/generic/THCStorage.c line=147 error=17 : invalid device pointer
W/o caching allocator, runs without problem.

**Comment by colesbury** [comment]
Oops, this isn't good. I had forgotten that each Lua thread has it's own THC state (and THCCachingAllocator). 

I think the simplest fix might be to share the THCCachingAllocator instance across threads (such as in a static/global variable). This would be a little ugly, since we generally avoid global variables in THC, but I don't have any better ideas.

@soumith

**Comment by soumith** [comment]
go for the global variable. i think as an allocator this is an unavoidable situation.
