### ISSUE TITLE
cutorch install failed (error: more than one instance of overloaded function "min" matches the argument list)

### ISSUE THREAD

**Issue by hellodrx** [torch/cutorch#551]
Hi, I'm trying to install torch, but failed with these errors,
`[ 81%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathReduceDouble.cu.o
/home/ruoxi/torch/extra/cutorch/lib/THC/THCTensorRandom.cu(250): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

/home/ruoxi/torch/extra/cutorch/lib/THC/THCTensorRandom.cu(264): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

/home/ruoxi/torch/extra/cutorch/lib/THC/THCTensorRandom.cu(278): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

/home/ruoxi/torch/extra/cutorch/lib/THC/THCTensorRandom.cu(293): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

/home/ruoxi/torch/extra/cutorch/lib/THC/THCTensorRandom.cu(308): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

/home/ruoxi/torch/extra/cutorch/lib/THC/THCTensorRandom.cu(323): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

/home/ruoxi/torch/extra/cutorch/lib/THC/THCTensorRandom.cu(338): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

7 errors detected in the compilation of "/tmp/tmpxft_000065bb_00000000-16_THCTensorRandom.compute_52.cpp1.ii".
CMake Error at THC_generated_THCTensorRandom.cu.o.cmake:267 (message):
  Error generating file
  /home/ruoxi/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorRandom.cu.o`

It's like something is wrong with my CUDA. My CUDA version is 7.0.

I'm no expert of Torch. Could someone help me solve these errors. Many thanks.

**Comment by hellodrx** [comment]
Maybe not CUDA's fault,  just the headers' name don't match the name of .cu files or something else. Still trying to solve the issues ^_^.

**Comment by BTNC** [comment]
There is a PR to fix the issue which is under evaluation and not merged yet. Temporarily, could you change line 241 in file cutorch/lib/THC/THCTensorRandom.cu to:
#define NUM_BLOCKS min((int)THCCeilDiv(size, (ptrdiff_t) BLOCK_SIZE), MAX_NUM_BLOCKS) and retry?

**Comment by soumith** [comment]
hi there. this issue should now be fixed in master. the PR to fix this has been merged.

**Comment by hellodrx** [comment]
Thx, guys~

**Comment by Wyntor** [comment]
Could you please tell me how to solve it? I am facing the same problem...
