### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by angelleng** [torch/cutorch#557]
Hi there, I was ran into this error when trying to install ctorch and ran into this error: 

`Scanning dependencies of target THC
[ 80%] Building C object lib/THC/CMakeFiles/THC.dir/THCAllocator.c.o
[ 81%] Building CXX object lib/THC/CMakeFiles/THC.dir/THCCachingAllocator.cpp.o
[ 82%] Building C object lib/THC/CMakeFiles/THC.dir/THCGeneral.c.o
[ 85%] Building C object lib/THC/CMakeFiles/THC.dir/THCStorage.c.o
[ 85%] Building C object lib/THC/CMakeFiles/THC.dir/THCStorageCopy.c.o
[ 86%] Building C object lib/THC/CMakeFiles/THC.dir/THCStream.c.o
[ 89%] Building C object lib/THC/CMakeFiles/THC.dir/THCTensor.c.o
[ 89%] Building C object lib/THC/CMakeFiles/THC.dir/THCTensorCopy.c.o
[ 89%] Building C object lib/THC/CMakeFiles/THC.dir/THCThreadLocal.c.o
make[2]: *** No rule to make target`/usr/lib/x86_64-linux-gnu/libpthread.so', needed by `lib/THC/libTHC.so'.  Stop.
make[2]: **\* Waiting for unfinished jobs....
/tmp/luarocks_cutorch-scm-1-8687/cutorch/lib/THC/THCGeneral.c: In function ‘applyHeapDelta’:
/tmp/luarocks_cutorch-scm-1-8687/cutorch/lib/THC/THCGeneral.c:755:3: error: implicit declaration of function ‘THAtomicAddPtrdiff’ [-Werror=implicit-function-declaration]
   ptrdiff_t newHeapSize = THAtomicAddPtrdiff(&heapSize, state->heapDelta) + state->heapDelta;
   ^
cc1: some warnings being treated as errors
make[2]: **\* [lib/THC/CMakeFiles/THC.dir/THCGeneral.c.o] Error 1
make[1]: **\* [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: **\* [all] Error 2

Error: Build error: Failed building.`

Any idea how it can be fixed? 
And I am using the conda integrated lua and luarocks. Could that be the problem?

**Comment by BTNC** [comment]
Please have a try to sync torch and rebuild torch and cutorch.
