### ISSUE TITLE
THCudaCheck FAIL an illegal memory access was encountered

### ISSUE THREAD

**Issue by sahasuman** [torch/cutorch#559]
I am working on the Faster RCNN object detector and trying to modify the ROIPooling layer in Torch. I am trying to take the element wise summation of the two feature maps obtained from two successive images. I am writing the code in the: function:
 ROIPooling:updateGradInput(input,gradOutput) 
 more specifically, the following line I introduced:
 local data = torch.add(data_1[1], data_1[2], 1) -- data_1[1]=[256 x 39 x 51]  data_1[2]=[256 x 39 x 51] 

Basically, data_1[1] and data_1[2] are the two conv feature maps obtained from the last conv layer of AlexNet for two successive images, now I want to fuse the feature maps using element wise summation [*]. When I am running my training code, I get the following error:

THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-8406/cutorch/lib/THC/generic/THCStorage.c line=147 error=77 : an illegal memory access was encountered
$ Error: cuda runtime error (77) : an illegal memory access was encountered at /tmp/luarocks_cutorch-scm-1-8406/cutorch/lib/THC/generic/THCStorage.c:147

[*] Convolutional Two-Stream Network Fusion for Video Action Recognition: https://www.robots.ox.ac.uk/~vgg/publications/2016/Feichtenhofer16/feichtenhofer16.pdf

**Comment by gooshan** [comment]
I get the same error when converting a tensor to a CudaTensor in the same layer on backprop.

**Comment by sahasuman** [comment]
I have somehow managed to get rid of this error by computing the the element wise sum using nn.Sum() module,i.e., instead of computing the  element wise sum within the ROIPooling:updateGradInput(input,gradOutput) function, I have added a nn.Sum() layer in the FRCNN.lua.

`local conv5_3 = backend.SpatialConvolution(512, 512, 3, 3, 1, 1, 1, 1, 1)
	conv5_3.name = 'conv5_3'
	--conv5_3.accGradParameters = function() end
	shared:add(conv5_3)
	shared:add(backend.ReLU(true))
shared:add(nn.Sum(1))
`
