### ISSUE TITLE
 no CUDA-capable device is detected

### ISSUE THREAD

**Issue by OanaCamburu** [torch/cutorch#560]
Hi,

I've been looking through the similar question before and did what was suggested and still didn't solve the issue. here are the steps I've followed:

1) installed torch from scratch:
git clone https://github.com/torch/distro.git /data/mulga/oanuru/torch --recursive
cd torch
./install.sh
source ~/.bashrc

2) downloaded cuDNN 5.1 for CUDA 7.5 from [website](https://developer.nvidia.com/cudnn)
export LD_LIBRARY_PATH=<path_to_cuda>:$LD_LIBRARY_PATH

3)luarocks install cutorch
luarocks install cudnn
luarocks install cunn

I had no error for these, but when I run: luajit -l libcutorch
THCudaCheck FAIL file=/data/whip/oanuru/torch/extra/cutorch/lib/THC/THCGeneral.c line=108 error=38 : no CUDA-capable device is detected

Any idea how to solve this? Thanks!

**Comment by soumith** [comment]
1. what's the output of installing cutorch
2. what's the output of nvidia-smi

**Comment by OanaCamburu** [comment]
luarocks install cutorch gave no error. here is last part of the logs:
_cd build
Updating manifest for /data/mulga/oana/torch/install/lib/luarocks/rocks
cutorch scm-1 is now built and installed in /data/mulga/oana/torch/install/ (license: BSD)_

I have 7 GPUs I can see with nvidia-smi
+------------------------------------------------------+                       
| NVIDIA-SMI 361.42     Driver Version: 361.42         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  On   | 0000:04:00.0     Off |                  N/A |
| 22%   39C    P8    16W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  On   | 0000:05:00.0     Off |                  N/A |
| 22%   37C    P8    16W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  On   | 0000:08:00.0     Off |                  N/A |
| 23%   63C    P2   101W / 250W |  11240MiB / 12287MiB |     64%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  On   | 0000:09:00.0     Off |                  N/A |
| 30%   70C    P2    98W / 250W |  12012MiB / 12287MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX TIT...  On   | 0000:85:00.0     Off |                  N/A |
| 28%   67C    P2    98W / 250W |  11240MiB / 12287MiB |     35%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX TIT...  On   | 0000:89:00.0     Off |                  N/A |
| 28%   68C    P2   125W / 250W |  11240MiB / 12287MiB |     70%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX TIT...  On   | 0000:8A:00.0     Off |                  N/A |
| 29%   70C    P2   115W / 250W |  11240MiB / 12287MiB |     36%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by OanaCamburu** [comment]
Sorry, my bad, didn't put the CUDA_VISIBLE_DEVICES ups
