### ISSUE TITLE
GPU occupation problem

### ISSUE THREAD

**Issue by fanlamda** [torch/cutorch#563]
I have serveral GPUs，only want use some of these, but when I require 'cutorch', there is 142  MB occupation on every GPU. How can I shutdown some of these?
![qq 20161025080227](https://cloud.githubusercontent.com/assets/22806530/19668330/9f645e64-9a89-11e6-9223-24e5eb89989d.png)

**Comment by soumith** [comment]
you can control it by using the environment variable CUDA_VISIBLE_DEVICES before starting th.
For example:

CUDA_VISIBLE_DEVICES=0 th [yourscript.lua]

will only have the first GPU to be visible to torch
