### ISSUE TITLE
stack smashing detected upon `require cutorch`

### ISSUE THREAD

**Issue by nhynes** [torch/cutorch#570]
After upgrading to CUDA 8 and reinstalling Torch, I'm unable to `require cutorch` and receive the following error:

```
*** stack smashing detected ***: ~/nhynes/torch/install/bin/luajit terminated
```

Opening it up in GDB doesn't yield much insight:

```
[New Thread 0x7fdae4800700 (LWP 16253)]
[New Thread 0x7fdae3f7e700 (LWP 16254)]
[New Thread 0x7fdae377d700 (LWP 16255)]

Program received signal SIGABRT, Aborted.
0x00007fdb64365c37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
```

This happens on machines containing Pascal GPUs, but I don't think that this is the issue since CUDA 7 was [almost] working fine on them.

Oh, it might also help to mention that I symlinked the `cu*.so.7.0` files that `cutorch` required to the 8 (and then old 7) versions. I'd be that this is the problem (to which I also don't have a solution).  The cmake output doesn't suggest why it might be linking against the nonexistent 7.0 libs.

```
 -- Autodetected CUDA architecture(s): 6.1 6.1 6.1 6.1 6.1 6.1 6.1 6.1
-- got cuda version 8.0
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- CUDA_NVCC_FLAGS: -gencode;arch=compute_61,code=sm_61;-DCUDA_HAS_FP16=1
```

Thanks for any help with resolving this!

**Comment by nhynes** [comment]
Huh, reinstalling torch from scratch seemed to do the trick...

**Comment by soumith** [comment]
i've been using cuda8 and cutorch for quite a bit without problems. I dont think you should symlink the .7.0 files like that.
Have you tried simply installing a clean new torch?

**Comment by nhynes** [comment]
It turns out that the old libs were pulled in with an old version of MAGMA. Everything is working fine now, thanks!
