### ISSUE TITLE
no suitable conversion function from "half" to "float" exists

### ISSUE THREAD

**Issue by zelle-github** [torch/cutorch#584]
Hi,
when installing cutorch using `luarocks install cutorch` I get the following error:

`[  9%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
/tmp/luarocks_cutorch-scm-1-5975/cutorch/lib/THC/THCBlas.cu(68): error: no suitable conversion function from "half" to "float" exists

1 error detected in the compilation of "/tmp/tmpxft_00007c86_00000000-7_THCBlas.cpp1.ii".
CMake Error at THC_generated_THCBlas.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-5975/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:70: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:172: recipe for target 'lib/THC/CMakeFiles/THC.dir/all' failed
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.`

I am using Ubuntu 16.10 64bit with Cuda 8, cuDNN installed as well as Torch 7. I was able to install these packages: image, tds, cjson, nnx, optim, inn, cunn, cudnn.

Has anyone an idea whats going wrong here?

**Comment by soumith** [comment]
this should be fixed now.

**Comment by zelle-github** [comment]
Thanks a lot for the fast help!

**Comment by ChijunZhang** [comment]
I meet error: no suitable conversion function from "half" to "double" exists
