### ISSUE TITLE
How to install cutorch with CUDA7.5?

### ISSUE THREAD

**Issue by nutee000** [torch/cutorch#585]
Dear all,
I'm using Ubuntu 14.04, CUDA7.5, the gpu card is nvidia Titan X. 
There occurs nvcc fatal : Unsupported gpu architecture 'compute_61' when install cutorch.
I know that intalling CUDA8.0 can solve the problem, but this causes other problems in other libs I am using(it doesn't occur with CUDA7.5). 
So, is there any way to use cutorch with CUDA7.5?
Thanks!

**Comment by soumith** [comment]
you seem to have a Pascal card installed on your system. The only way to have any CUDA code work on that particular card is with CUDA 8.0

**Comment by nutee000** [comment]
yes, a Pascal card. Got it. Thanks!
