### ISSUE TITLE
:csub does not exist

### ISSUE THREAD

**Issue by soumith** [torch/cutorch#60]
subtraction

**Comment by Kaixhin** [comment]
Has this somehow been removed? I just got `attempt to call method 'csub' (a nil value)` on a CudaTensor in my program, and can't see the method in the interpreter when I create a CudaTensor. Other tensor types are fine.

**Comment by soumith** [comment]
hmm, weird you are right, csub seems to have been removed somewhere in between. taking a look

**Comment by soumith** [comment]
actually, turns out csub wasn't in that PR, I might've wrongly closed it.

**Comment by daranday** [comment]
I'm experiencing the same issue. Pulled the latest version. February 15, 2016

**Comment by soumith** [comment]
fixed via #351
