### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by bargoti** [torch/cutorch#606]
While installing cutorch using luarocks I'm getting following error:

Warning: unmatched variable LUALIB

jopts=$(getconf _NPROCESSORS_CONF)

echo "Building on $jopts cores"
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/ubuntu/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/ubuntu/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$jopts install

Building on 8 cores
-- Found Torch7 in /home/ubuntu/torch/install
-- MAGMA not found. Compiling without MAGMA support
-- Autodetected CUDA architecture(s): 3.0
-- got cuda version 7.0
-- Could not find CUDA with FP16 support, compiling without torch.CudaHalfTensor
-- CUDA_NVCC_FLAGS: -gencode;arch=compute_30,code=sm_30
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/cutorch/build
[  3%] [  3%] [  3%] [  4%] [  6%] [  7%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorSort.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorSortByte.cu.o
[  8%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathCompareTByte.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorTypeUtils.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorRandom.cu.o
[  9%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathPointwiseByte.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathCompareByte.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathReduceByte.cu.o
/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(221): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(221): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(221): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(225): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(225): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(225): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(229): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(229): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(229): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(233): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(233): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/THCTensorRandom.cu(233): error: identifier "half" is undefined

/home/ubuntu/cutorch/lib/THC/generic/THCTensorRandom.cu(17): error: more than one instance of overloaded function "generate_uniform" matches the argument list:
            function "generate_uniform(curandStateMtgp32 *, int, float *, double, double)"
            function "generate_uniform(curandStateMtgp32 *, int, <error-type> *, double, double)"
            argument types are: (curandStateMtgp32 *, ptrdiff_t, float *, double, double)

/home/ubuntu/cutorch/lib/THC/generic/THCTensorRandom.cu(31): error: more than one instance of overloaded function "generate_normal" matches the argument list:
            function "generate_normal(curandStateMtgp32 *, int, float *, double, double)"
            function "generate_normal(curandStateMtgp32 *, int, <error-type> *, double, double)"
            argument types are: (curandStateMtgp32 *, ptrdiff_t, float *, double, double)

/home/ubuntu/cutorch/lib/THC/generic/THCTensorRandom.cu(62): error: more than one instance of overloaded function "generate_exponential" matches the argument list:
            function "generate_exponential(curandStateMtgp32 *, int, float *, double)"
            function "generate_exponential(curandStateMtgp32 *, int, <error-type> *, double)"
            argument types are: (curandStateMtgp32 *, ptrdiff_t, float *, double)

/home/ubuntu/cutorch/lib/THC/generic/THCTensorRandom.cu(77): error: more than one instance of overloaded function "generate_cauchy" matches the argument list:
            function "generate_cauchy(curandStateMtgp32 *, int, float *, double, double)"
            function "generate_cauchy(curandStateMtgp32 *, int, <error-type> *, double, double)"
            argument types are: (curandStateMtgp32 *, ptrdiff_t, float *, double, double)

/home/ubuntu/cutorch/lib/THC/generic/THCTensorRandom.cu(17): error: more than one instance of overloaded function "generate_uniform" matches the argument list:
            function "generate_uniform(curandStateMtgp32 *, int, double *, double, double)"
            function "generate_uniform(curandStateMtgp32 *, int, <error-type> *, double, double)"
            argument types are: (curandStateMtgp32 *, ptrdiff_t, double *, double, double)

/home/ubuntu/cutorch/lib/THC/generic/THCTensorRandom.cu(31): error: more than one instance of overloaded function "generate_normal" matches the argument list:
            function "generate_normal(curandStateMtgp32 *, int, double *, double, double)"
            function "generate_normal(curandStateMtgp32 *, int, <error-type> *, double, double)"
            argument types are: (curandStateMtgp32 *, ptrdiff_t, double *, double, double)

/home/ubuntu/cutorch/lib/THC/generic/THCTensorRandom.cu(62): error: more than one instance of overloaded function "generate_exponential" matches the argument list:
            function "generate_exponential(curandStateMtgp32 *, int, double *, double)"
            function "generate_exponential(curandStateMtgp32 *, int, <error-type> *, double)"
            argument types are: (curandStateMtgp32 *, ptrdiff_t, double *, double)

/home/ubuntu/cutorch/lib/THC/generic/THCTensorRandom.cu(77): error: more than one instance of overloaded function "generate_cauchy" matches the argument list:
            function "generate_cauchy(curandStateMtgp32 *, int, double *, double, double)"
            function "generate_cauchy(curandStateMtgp32 *, int, <error-type> *, double, double)"
            argument types are: (curandStateMtgp32 *, ptrdiff_t, double *, double, double)

20 errors detected in the compilation of "/tmp/tmpxft_00003fd4_00000000-7_THCTensorRandom.cpp1.ii".
CMake Error at THC_generated_THCTensorRandom.cu.o.cmake:267 (message):
  Error generating file
  /home/ubuntu/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorRandom.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorRandom.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
^Cmake[2]: *** [lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathPointwiseByte.cu.o] Interrupt
make[2]: *** [lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorSortByte.cu.o] Interrupt
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Interrupt
make: *** [all] Interrupt

Error: Build error: Failed building.

Please help.

**Comment by gooshan** [comment]
I have the same problem. I've tried out a few of the previous commits and the one from Nov 9th works for me (d41e2fdbfb).

**Comment by soumith** [comment]
this should be a simple fix, we need to add guards around HALF random stuff for cuda 7.0.
cc: @killeent can you fix this.
