### ISSUE TITLE
Tensor / Storage copy bugs

### ISSUE THREAD

**Issue by colesbury** [torch/cutorch#612]
We have a number of tensor/storage copy bugs, which we should fix:

1. Copies of non-contiguous tensors from GPU to host create a contiguous copy on the **current** device. It should create the contiguous copy on the same device as the original tensor. Otherwise, this can entail a p2p copy (or worse, a host mediated copy).

2. The above issue exists with CUDA half -> CPU float copies (even contiguous ones)

3. Cross-device storage copies do not insert the correct synchronizations (unlike cross-device tensor copies).

4. Float <-> Half storage copies between devices require P2P access, but does not check for it (as opposed to cudaMemcpy which falls back to host mediated copies)

Our copy code is duplicated and spread over a number of places. Storage copies are implemented separately from Tensor copies, even though storage copies are a (simple) special case of tensor copies. We should combine the implementations to reduce duplicate code and add tests for all type conversions, including cross-GPU type conversions.

**Comment by borisfom** [comment]
We'd have much less of those copies if my HalfTensor PRs: https://github.com/torch/torch7/pull/826 and https://github.com/torch/cutorch/pull/578 were merged, too!

**Comment by soumith** [comment]
these bugs are solved now, thanks to @colesbury 's PRs.
