### ISSUE TITLE
too many resources requested for launch

### ISSUE THREAD

**Issue by xwgeng** [torch/cutorch#624]
Hi,
    I write seq2seq model with attention, and it works well on GPU. but after I update to cuda 8.0, I get a following error

 
THCudaCheck FAIL file=/users1/xwgeng/torch/extra/cutorch/lib/THC/generated/../generic/THCTensorSort.cu line=153 error=7 : too many resources requested for launch
/users1/xwgeng/torch/install/bin/luajit: /users1/xwgeng/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (7) : too many resources requested for launch at /users1/xwgeng/torch/extra/cutorch/lib/THC/generated/../generic/THCTensorSort.cu:153
stack traceback:  
        [C]: in function 'v'  
        /users1/xwgeng/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'LookupTable_accGradParameters'  
        ...s1/xwgeng/torch/install/share/lua/5.1/nn/LookupTable.lua:111: in function 'accGradParameters'  
        /users1/xwgeng/torch/install/share/lua/5.1/nn/Module.lua:32: in function 'backward'  
        ./seq2seq.lua:263: in function 'opfunc'  
        /users1/xwgeng/torch/install/share/lua/5.1/optim/adam.lua:37: in function  </users1/xwgeng/torch/install/share/lua/5.1/optim/adam.lua:24>
        ./trainer.lua:37: in function 'train'
        ./trainer.lua:102: in function 'run'
        main.lua:116: in main chunk
        [C]: in function 'dofile'
        ...geng/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004064f0

The GPU is Tesla K40m, and the code is available at: https://github.com/xwgeng/s2s-attn

**Comment by fmassa** [comment]
I think this has been fixed in https://github.com/torch/cutorch/pull/657

**Comment by xwgeng** [comment]
ok, it works well. Thanks
