### ISSUE TITLE
Cannot build cutorch on Windows

### ISSUE THREAD

**Issue by MrZoidberg** [torch/cutorch#629]
I was trying to install cutorch using luarocks according the instruction on [torch7 wiki](https://github.com/torch/torch7/wiki/Windows#appendix-installing-cutorch). 

I've unpacked cutorch using `luarocks unpack cutorch`, removed -j from rockspec, configured and generated make file using CMake GUI ([here is my config](https://dl.dropboxusercontent.com/u/3905973/Screenshot%202016-12-13%2018.30.08.png)). Then I tried several times to make cutorch using 'luarocks make' with the same error during linking:

```
[ 90%] Linking CXX shared library ..\..\THC.dll
   Creating library THC.lib and object THC.exp
THCGeneral.c.obj : error LNK2019: unresolved external symbol THCCachingHostAllocator referenced in function THCudaShutdown
..\..\THC.dll : fatal error LNK1120: 1 unresolved externals
LINK failed. with 1120
NMAKE : fatal error U1077: 'C:\tools\CMake\bin\cmake.exe' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.

Error: Build error: Failed building.
```

OS: Windows 10 x64
Lua version: 5.1
Visual Studio 2015 Pro + Windows SDK 10

Installed rocks:
----------------

argcheck
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

cudnn
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

cunn
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

cwrap
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

dok
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

env
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

gnuplot
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

graph
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

image
   1.1.alpha-0 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

lua-cjson
   2.1devel-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

luaffi
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

luafilesystem
   1.6.3-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

nn
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

nngraph
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

nnx
   0.1-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

optim
   1.0.5-0 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

paths
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

penlight
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

qtlua
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

qttorch
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

sundown
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

sys
   1.1-0 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

threads
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

torch
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

trepl
   scm-1 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

xlua
   1.0-0 (installed) - C:/tools/torch/luarocks/systree/lib/luarocks/rocks

[Here is the full build log](https://dl.dropboxusercontent.com/u/3905973/cutorch%20build%20log.txt)

**Comment by BTNC** [comment]
Simply run `luarocks make rocks\cutorch-scm-1.rockspec` under cutorch\ is sufficient to install cutorch with vs2015 on win10. I can successfully install latest cutorch. That wiki is out of date. You can try again clean install.

**Comment by MrZoidberg** [comment]
@BTNC thanks. it works!
