### ISSUE TITLE
error: no suitable conversion function from "__half" to "double" exists

### ISSUE THREAD

**Issue by ChijunZhang** [torch/cutorch#643]
When building cutorch,
[ 15%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathPairwise.cu.o
/tmp/luarocks_cutorch-scm-1-8088/cutorch/lib/THC/THCTensorMathPointwise.cuh(457): error: operand types are incompatible ("__half" and "float")

/tmp/luarocks_cutorch-scm-1-8088/cutorch/lib/THC/THCTensorMathPointwise.cuh(467): error: operand types are incompatible ("__half" and "float")

/tmp/luarocks_cutorch-scm-1-8088/cutorch/lib/THC/THCTensorMathPointwise.cuh(514): error: no suitable conversion function from "__half" to "double" exists

3 errors detected in the compilation of "/tmp/tmpxft_00000df4_00000000-7_THCTensorMath2.cpp1.ii".
CMake Error at THC_generated_THCTensorMath2.cu.o.cmake:267 (message):
  Error generating file

my cuda version: cuda8.0
cudnn version:cuDNN5.1

**Comment by xgastaldi** [comment]
Same issue here

**Comment by soumith** [comment]
i fixed this by reverting the PR. things should work now. sorry for that.

**Comment by ChijunZhang** [comment]
Thanks a lot
