### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by ArghyaPal** [torch/cutorch#647]
Hi @soumith, I got the error:
While running **th> require "cutorch"**
`/home/arghya/torch/install/bin/luajit: symbol lookup error: /home/arghya/torch/install/lib/libTHC.so: undefined symbol: _ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`

I tried:
1. rm -rf ~/.cache/luarocks
2. A fresh re-installation of all (luarocks install {cutorch,cunn})

but no luck.. :-(

Can you please help me to overcome this.

Regards,
Arghya

**Comment by pavanky** [comment]
@ArghyaPal Can you run ldd on `libTHC.so` ?

**Comment by ArghyaPal** [comment]
Hi @pavanky, thank you for your prompt reply.. :-) 

I am getting the following output, after `ldd libTHC.so` on the said location,

(i.e. 
>> cd /home/arghya/torch/install/lib/
>> ls 
>> libluajit.so  libluaT.so  libluaT.so.0  libqlua.so  libqtlua.so  libTHC.so  libthreadsmain.so  libTH.so  libTH.so.0  lua  luarocks
>> ldd libTHC.so):

`linux-vdso.so.1 =>  (0x00007fffda5e4000)
	libopenblas.so.0 => /opt/OpenBLAS/lib/libopenblas.so.0 (0x00007f950ab75000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f950a950000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f950a64a000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f950a43b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f950a21c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9509e57000)
	/lib64/ld-linux-x86-64.so.2 (0x0000562663876000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f9509b3d000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f9509900000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f95096ea000)
`

**Comment by ArghyaPal** [comment]
And, 

`ldd luajit` at `/home/arghya/torch/install/bin` this location:

(i.e. 
>> cd /home/arghya/torch/install/bin
>> ls 
json2lua  lua2json  luajit  luarocks  luarocks-admin  mdcat  qlua  th  torch-activate
>> ld luajit
)

`
linux-vdso.so.1 =>  (0x00007ffe0711c000)
	libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007f3835496000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3835292000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3834f8b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3834d6d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3834b57000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3834791000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f3834568000)
	/lib64/ld-linux-x86-64.so.2 (0x0000555ce6898000)

`

**Comment by pavanky** [comment]
Did you  (or the distro) upgrade yourcompiler recently ? I am not entirely sure where the error is coming from, but it looks like there has been an ABI incompatibility between two libraries in your setup.

**Comment by ArghyaPal** [comment]
I get your point @pavanky. Yes, its an ABI problem. Let me try as per your direction.

Regards,
Arghya.
