### ISSUE TITLE
Compiling on Jetson TX1 missing symbols like "THHalfTensor"

### ISSUE THREAD

**Issue by ZahlGraf** [torch/cutorch#658]
Hello,

I'm currently trying to compile cutorch for Jetson TX1 board. Basically I followed the instructions from here:
http://www.jetsonhacks.com/2015/05/20/torch-7-scientific-computer-framework-with-cudnn-nvidia-jetson-tk1/

However I had to define the following paths to be able to call `sudo luarocks install cutorch`:
```
export CUDA_INC_PATH=/usr/local/cuda-7.0/targets/armv7-linux-gnueabihf/include
export CUDA_LIB_PATH=/usr/local/cuda-7.0/targets/armv7-linux-gnueabihf/lib
``` 

Maybe this is an important information?

During compiling I get the following error:
```
Scanning dependencies of target THC
[ 83%] [ 83%] [ 84%] [ 85%] Building CXX object lib/THC/CMakeFiles/THC.dir/THCCachingHostAllocator.cpp.o
Building C object lib/THC/CMakeFiles/THC.dir/THCGeneral.c.o
Building CXX object lib/THC/CMakeFiles/THC.dir/THCCachingAllocator.cpp.o
Building C object lib/THC/CMakeFiles/THC.dir/THCStorageCopy.c.o
In file included from generic/THCStorageCopy.h:1:0,
                 from /tmp/luarocks_cutorch-scm-1-9648/cutorch/lib/THC/THCGenerateAllTypes.h:17,
                 from /tmp/luarocks_cutorch-scm-1-9648/cutorch/lib/THC/THCStorageCopy.h:9,
                 from /tmp/luarocks_cutorch-scm-1-9648/cutorch/lib/THC/THCStorageCopy.c:1:
/tmp/luarocks_cutorch-scm-1-9648/cutorch/lib/THC/generic/THCStorageCopy.h:16:81: warning: ‘struct THHalfStorage’ declared inside parameter list [enabled by default]
 THC_API void THCStorage_(copyHalf)(THCState *state, THCStorage *storage, struct THHalfStorage *src);
                                                                                 ^
/tmp/luarocks_cutorch-scm-1-9648/cutorch/lib/THC/generic/THCStorageCopy.h:36:73: error: unknown type name ‘THHalfStorage’
 THC_API void TH_CONCAT_2(THHalfStorage_copyCuda, Real)(THCState *state, THHalfStorage *self, struct THCStorage *src);
...
```

The same also happens for THHalfTensor and so on. This is the beginning of the errors.

Does anyone know a solution here?

I wish you a happy new year!

**Comment by soumith** [comment]
Update your CUDA version on the TX1 to 7.5 or above, if possible. Is that possible?

**Comment by ZahlGraf** [comment]
Hi it seems, that CUDA 7.5 is not available for TX1.
But on the Jetson TX1 forum someone from NVIDIA wrote:

> CUDA toolkit 7.0 is provided for Jetson TX1, however features from CUDA 7.5 (like FP16 support) have been backported to JTX1's version of toolkit 7.0.

**Comment by ZahlGraf** [comment]
Hi again,

I decided to flash my Jetson with the latest filesystem provided by JetPack 2.3. It contains CUDA 8.0, thus this should not be any issue here.

So I close this ticket. Thanks for your support :)
