### ISSUE TITLE
Resize gives out of memory when there is still free memory

### ISSUE THREAD

**Issue by JoostvDoorn** [torch/cutorch#669]
It seems when resizing large Tensors out of memory errors occur relatively quickly. The example below is rather superficial, but extends to varying sequence lengths and batch sizes in RNNs when implemented with resize. Since resize does not provide any guarantee for the contents it should be able to allocate the needed memory (up to about n=8 in the example below).
```
1
7868/8104 Mbytes
2
6844/8104 Mbytes
3
5820/8104 Mbytes
4
4796/8104 Mbytes
5
3772/8104 Mbytes
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-9879/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
```
```lua
require 'cutorch'
local a = torch.Tensor(1):cuda()
for n=1,100 do
   print(n)
   cutorch.synchronize()
   local freeMemory, totalMemory = cutorch.getMemoryUsage()
   print(string.format("%d/%d Mbytes", freeMemory/1024/1024, totalMemory/1024/1024))
   a:resize(1024, 262144, n)
end
```
This is not a new issue, I have checked with a version from about 9 months ago.

**Comment by pavanky** [comment]
@JoostvDoorn can you try adding `a:resize(1)` before calling `a:resize(1024, 262144, n)` ?

**Comment by JoostvDoorn** [comment]
@pavanky That doesn't work, but `a:storage():resize(1)` does work.

**Comment by JoostvDoorn** [comment]
Just to elaborate: this issue occurs in different modules for example in cudnn LSTM, where reserve is a really large Tensor. Uncommenting `model:clearState()` will reset the storage every iteration and allow usage of all memory.

```lua
require 'cutorch'
require 'cudnn'
local model = cudnn.LSTM(1024, 1024, 10)
for n=1,100 do
   -- model:clearState()
   local input = torch.Tensor(30,50*n,1024):cuda()
   cutorch.synchronize()
   local freeMemory, totalMemory = cutorch.getMemoryUsage()
   print(string.format("%d: %d/%d Mbytes", n, freeMemory/1024/1024, totalMemory/1024/1024))
   model:forward(input)
end
```
