### ISSUE TITLE
Dependency on Magma -> Atlas prevent install on Laptop due to CPU throttling - related to CUDA acceleration

### ISSUE THREAD

**Issue by archenroot** [torch/cutorch#671]
Hi guys,

I found one older ebuild for cutorch, which didn't depend on magma. But while reading the code of cutorch, it looks like in case of MAGMA library is not found, the CUDA acceleration is not available. 

In my case however MAGMA depends on ATLAS, and as soon as I work on Laptop, I have CPU throtling enabled, which ATLAS detect as NOGO issue.

Did someone fixed this issue, aka disabling cpu throttling. I believe this is something to do to set MIN and MAX frequencies to the same number in general, but not sure.

I work on Gentoo system, so will follow [this guide](https://wiki.gentoo.org/wiki/Power_management/Guide).

Will report here if and how I fixed.

**Comment by archenroot** [comment]
Ok, thanks to 

I created a patch for source of Atlas 3.10.3 (latest stable in time) thanks to [Eric at StackOverflow](http://stackoverflow.com/questions/14592401/atlas-install-really-need-to-get-past-cpu-throttle-check)

The patch in general disable checking of CPU throttling as following:
```
--- ATLAS/CONFIG/src/config.c.orig	2017-01-11 11:46:52.513095621 +0100
+++ ATLAS/CONFIG/src/config.c	2017-01-11 11:48:40.021098026 +0100
@@ -1025,7 +1025,7 @@
    *verb = 0;
    *NoCygwin = 0;
    *NoF77 = 0;
-   *ThrChk = 1;
+   *ThrChk = 0;
    *nthreads = -1;
    *tids = NULL;
    *omp = *AntThr = 0;
```

So I have  now MAGMA with ATLAS ready on my system and could build with full GPU support hopefully :-)

**Comment by archenroot** [comment]
Just info, that I compiled with magma-2.2.0 latest release available.

**Comment by soumith** [comment]
thanks, i'm closing this then.
