### ISSUE TITLE
Strange memory leak in LookUpTable 

### ISSUE THREAD

**Issue by suryabhupa** [torch/cutorch#685]
There's a strange memory leak in LookUpTable that caused the cuda runtime to run out of memory. Updating to the newest cutorch/cunn solved the problem -- does anyone know what this might from?

**Comment by soumith** [comment]
maybe you were hit by https://github.com/torch/cunn/pull/400

**Comment by suryabhupa** [comment]
oh huh, yeah this might be what was causing it. I guess I didn't update cunn since early December...

Thanks for the reference!
