### ISSUE TITLE
Error after installation using MAGMA

### ISSUE THREAD

**Issue by danielle123123** [torch/cutorch#689]
Hello,

I have MAGMA installed and I recently tried installing cutorch on a new machine, installation seems fine but afterwards require 'cutorch' generates an error. The output for the command:
`luajit -l libcutorch`
is:
`luajit: Torch internal problem: cannot find metatable for type <torch.Allocator>
stack traceback:
	[C]: at 0x7f9af8a40e40
	[C]: at 0x0046b7a0
	[C]: at 0x00406670`

I tried reinstalling everything including MAGMA, didn't help.
cutorch 1.0-0 does work, but then I can't use cudnn.

It worked perfectly a few months ago, but I didn't find a way to install an earlier committed version, that would help too.

Thanks!

**Comment by soumith** [comment]
`luajit -l libcutorch` always will give that error.
What are the consequences of doing:
`luajit -lcutorch`?

I suspect that some symbols are missing when linked against magma (especially if magma is a static build and has been built with a CPU BLAS).

Do you use any of cutorch's Magma features like LAPACK functions?
If not, you can do this:

```
git clone https://github.com/torch/cutorch
cd cutorch
# comment this line: https://github.com/torch/cutorch/blob/master/lib/THC/CMakeLists.txt#L31
luarocks make rocks/cutorch-scm-1.rockspec
```

**Comment by danielle123123** [comment]
I see, the output of 
`luajit -lcutorch`
is:
`luajit: ...nielle_ezuz/torch/install/share/lua/5.1/cutorch/init.lua:2: cannot load '/home/danielle_ezuz/torch/install/lib/lua/5.1/libcutorch.so'
stack traceback:

	[C]: in function 'require'

	...nielle_ezuz/torch/install/share/lua/5.1/cutorch/init.lua:2: in main chunk

	[C]: at 0x0046b7a0

	[C]: at 0x00406670
`
and installing after commenting the line produced the same error. 
Does it mean the reason is not MAGMA?

**Comment by danielle123123** [comment]
I managed to install cutorch after reinstalling MAGMA with openBLAS instead of MKL.
Everything works now, but I didn't manage to install the current version of cutorch with MAGMA that was installed with MKL.

Thanks for the tips!
