### ISSUE TITLE
THCCachingHostAllocator can be slow with frequent copyAsync calls

### ISSUE THREAD

**Issue by gchanan** [torch/cutorch#698]
We have a program that has seen ~10-15% performance regression since the THCCachingHostAllocator was made default, due to slow copyAsync calls.  I wrote up a test script that amplifies the issue: https://gist.github.com/gchanan/0fd3d67d06d2dcae57ced77f0545d58e
(this script assumes 2 gpus)

th testcopyasync.txt
timer is	17.701434850693

THC_CACHING_ALLOCATOR=0 th testcopyasync.txt
timer is	8.5085191726685

The issue is essentially that each recordEvent (copyAsync) call runs the slow event loop and all wait on a single mutex, so the cost of processing the event loop isn't amortized.  There are a couple of ways to solve this:

1) Be more conservative about reclaiming blocks
Instead of adding an event per copyAsync call, we just record the stream on which the call was made, then when the ptr is freed, create an event for each stream.  This may be less aggressive about reclaiming blocks, because we only look for available blocks in free/malloc rather than on copyAsync calls, but it's not clear that will make a difference for most executions.  It could potentially be slow if you inverted the frequency of operations, i.e. host free/mallocs were done often but copyAsync calls were rare.  This approach was suggested by @colesbury.

I implemented this here: https://github.com/gchanan/cutorch/tree/conservativeAllocator

2) Add more fine granularity locking
Instead of having a single lock for dealing with the available/used blocks and event processing, we split them into two (detail: there are actually 3 to ensure forward progress is always made).  Also, event processing in copyAsync becomes wait free, i.e. we try to acquire the lock once and if we don't, we skip event processing since some other thread is currently doing it.  We could most likely make malloc wait free as well  (to avoid the potential free/malloc slowness with 1), but I wanted to minimize changes to solve the specific issue at hand.  We also move destroying completed events outside of the event loop, because it is slow.

The downside to this approach is it is more complex, i.e. there are 3 locks instead of 1.

I implemented this here: https://github.com/gchanan/cutorch/tree/aggressiveLocks

Performance numbers:
origin/HEAD                                                     17.701434850693 (seconds)
THC_CACHING_ALLOCATOR=0 origin/head  8.5085191726685
1) (conservative)                                               8.5015590190887
2) (aggressive fine grain locking)                    8.4650809764862

I don't have a strong preference for either approach, if someone lets me know a preference I'd be happy to put up a pull request.

**Comment by soumith** [comment]
(2) sounds like a more forward looking solution. it's not unreasonable to expect rapid malloc/free without copyAsync.

**Comment by colesbury** [comment]
Nice investigation.

I'm ambivalent about (2). I like that pinned memory allocations are ready for re-use earlier than with (1), but the locking and error handling is complicated. It's more likely that this solution has bugs.

I'm also not convinced it'll be faster for other use cases. For one, lots of malloc/frees without copies isn't a real use case. The whole point of pinned memory is for mediating copies between GPU and CPU. It doesn't make sense to malloc/free often without copy (async or otherwise). But it's also not clear that it would be slower in that case anyways: they both also have a exclusive lock in malloc for processEvents which will likely dominate the cost. Also, without a copyAsync there is no cudaEvent to record in free() for the first solution.

**Comment by pavanky** [comment]
> Also, without a copyAsync there is no cudaEvent to record in free() for the first solution.

👍 This makes 1 more elegant too :)

**Comment by soumith** [comment]
ok let's go with (1) then. Greg, open up that PR and we'll merge.

**Comment by gchanan** [comment]
Sounds good, will put up a PR for (1).

**Comment by gchanan** [comment]
https://github.com/torch/cutorch/pull/702
