### ISSUE TITLE
installing for device type no visible at the time of installation

### ISSUE THREAD

**Issue by wangkua1** [torch/cutorch#728]
Hi,

In my work environment, we have multiple gpu servers, some with different board types.  Also, my local directory is mounted to each of the machine when I schedule a job, or ssh into them.  So basically I have 1 torch installation that's used across possibly different GPUs. 
 
I'm having this funny issue where, if torch/cutorch/nn/cunn is installed on 1 machine with say GTX TITAN, it runs fine on that machine.  When I switch to a machine with say TITAN X (Pascal), then I get invalid device error. I know this is widely discussed issue (see here https://github.com/karpathy/neuraltalk2/issues/130, https://github.com/Element-Research/rnn/issues/277).  And I could just reinstall them everytime I run on a different machine, but that's so stupid.  Is there a way that I can manually specify all the types of boards that cutorch might need to work with, even if they are not visible at the time of installation?

Thanks a lot!!
Jackson

**Comment by soumith** [comment]
```
export TORCH_CUDA_ARCH_LIST="All"
luarocks install cutorch
luarocks install cunn
```

that'll make it a universal install

**Comment by wangkua1** [comment]
Thanks Soumith!  That's exactly what I needed.
