### ISSUE TITLE
Will this library support `range()`?

### ISSUE THREAD

**Issue by anoidgit** [torch/cutorch#738]
I have not found this funtion in [issue 70](https://github.com/torch/cutorch/issues/70), but it was available for `torch.LongTensor`, I have to call this on CPU and put the tensor to GPU with `cudaLong()` now. It's better if there is a GPU version, and It was useful when apply negtive sample.

**Comment by shenxiul** [comment]
Yes, it's recently merged. See pull request #729 .

**Comment by anoidgit** [comment]
That is very good, I will update my cutorch installation. @shenxiul
