### ISSUE TITLE
luajit cannot load libcutorch

### ISSUE THREAD

**Issue by mtobeiyf** [torch/cutorch#740]
Ubuntu 14.04  CUDA 7.5

When I run ``$ luajit -l libcutorch`` 
it gives me an **error** like this:

    luajit: Torch internal problem: cannot find metatable for type <torch.Allocator>
    stack traceback:
	    [C]: at 0x7f5385349620
	    [C]: at 0x0046b7a0
	    [C]: at 0x00406670

I used MATLAB to call torch, but error occurs:

    /home/fing/torch/install/bin/luajit: /home/fing/torch/install/share/lua/5.1/trepl/init.lua:389: /home/fing/torch/install/share/lua/5.1/trepl/init.lua:389: /home/fing/torch/install/share/lua/5.1/cutorch/init.lua:2: cannot load '/home/fing/torch/install/lib/lua/5.1/libcutorch.so'
    stack traceback:
	    [C]: in function 'error'
	    /home/fing/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	    deep_aesthetics.lua:2: in main chunk
	    [C]: in function 'dofile'
	    ...fing/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	    [C]: at 0x00406670

It says luajit cannot load libcutorch.so
but the file exists and this problem seems similar to the first one
I don't know why...

However, when I run ``th> require 'cutorch'``, it seems fine:

```
{
  createCudaUVATensor : function: 0x40de6060
  getPeerToPeerAccess : function: 0x40bb57c0
  getStream : function: 0x40bb5c58
  isCachingAllocatorEnabled : function: 0x40bb5b08
  getDeviceCount : function: 0x40bb5f30
  isManaged : function: 0x40de60c0
  setHeapTracking : function: 0x40bb8608
  manualSeedAll : function: 0x40bb84f8
  streamWaitFor : function: 0x40bb5d00
  toCudaUVATensor : function: 0x40de60a0
  toFloatUVATensor : function: 0x40de6080
  setKernelPeerToPeerAccess : function: 0x40bb5900
  reserveBlasHandles : function: 0x40bb5798
  manualSeed : function: 0x40bb84a8
  hasHalfInstructions : function: 0x40bb8830
  getBlasHandle : function: 0x40bb5990
  hasFastHalfInstructions : function: 0x40bb8888
  setDefaultStream : function: 0x40bb5cb0
  getMemoryUsage : function: 0x40bb87d8
  createCudaHostIntTensor : function: 0x40de9100
  streamBarrier : function: 0x40bb5db0
  createCudaHostLongTensor : function: 0x40de73d8
  seedAll : function: 0x40bb8900
  createCudaHostHalfTensor : function: 0x40de74a0
  driverVersion : 8000
  CudaUVAAllocator : torch.Allocator
  synchronize : function: 0x40bb5180
  createCudaHostByteTensor : function: 0x40de7458
  reserveStreams : function: 0x40bb59e0
  createCudaHostDoubleTensor : function: 0x40de9088
  getDevice : function: 0x40bb5e90
  createCudaHostFloatTensor : function: 0x40de9020
  withDevice : function: 0x40dea380
  seed : function: 0x40bb88d8
  test : function: 0x40dea318
  _stategc : userdata: 0x41aebf50
  getNumStreams : function: 0x40bb5a30
  getRuntimeVersion : function: 0x40bb5bb8
  deviceReset : function: 0x40bb5ee0
  Event : {...}
  CudaHostAllocator : torch.Allocator
  isManagedPtr : function: 0x40bb8630
  getState : function: 0x40bb85e0
  setRNGState : function: 0x40bb8590
  synchronizeAll : function: 0x40bb5208
  initialSeed : function: 0x40bb8480
  getDeviceProperties : function: 0x40bb5b60
  getRNGState : function: 0x40bb8568
  getNumBlasHandles : function: 0x40bb5828
  _sleep : function: 0x40bb8540
  setStream : function: 0x40bb5a80
  getKernelPeerToPeerAccess : function: 0x40bb5aa8
  createFloatUVATensor : function: 0x40de6020
  createCudaHostTensor : function: 0x40de9020
  getDriverVersion : function: 0x40bb8788
  streamSynchronize : function: 0x40bb5e68
  streamWaitForMultiDevice : function: 0x40bb5d60
  setDevice : function: 0x40bb88b0
  setPeerToPeerAccess : function: 0x40bb58a0
  hasHalf : true
  streamBarrierMultiDevice : function: 0x40bb5e10
  setBlasHandle : function: 0x40bb5878
  _state : userdata: 0x02753f00
}
```
I updated cmake to 3.2
then tried reinstalling torch and cutorch/cudnn  for several times
still no luck

What may cause this problem? torch itself, CUDA or PATH or something else?

Any solutions? Please help! 

Thank you so much

**Comment by albanD** [comment]
Hi,
Why do you try to require 'libcutorch' directly? You should juste require 'cutorch'.

The error you see when running 'luajit -l libcutorch' is actually because 'torch' should be required before requiring 'libcutorch'. Which is what 'cutorch' does properly when you require it.

The problem you see in matlab is that for some reason the 'libcutorch.so' file is not found when trying to load a shared library. Matlab may have changed some env variables given to the lua process changing the way it loads shared libraries.

**Comment by Mikeraka** [comment]
@mtobeiyf Hello, I have run into the same problem, Could you please give me a help? how you solved it? Thank you very much

**Comment by imfing** [comment]
@Mikeraka I cannot clearly remember. 
Perhaps just follow the answer above. Require 'cutorch' rather than the shared library 'libcutorch'.
