### ISSUE TITLE
I am trying to get this working on my machine.

### ISSUE THREAD

**Issue by BrighamM** [torch/cutorch#771]
----------Contents of .lua file---------------
a = torch.Tensor(5,3)
a = torch.rand(5,3)
print(a)

b = torch.rand(3,4)
print("**********************")
print(b)
c = torch.Tensor(5,4) 
c:mm(a,b)
print("*****************")
print(c)

print("CUDA CORES!")

require 'cutorch';
a = a:cuda()
b = b:cuda()
c = c:cuda()
c:mm(a,b)
-------------End of .lua file----------------

I try to run it with:
th testfile.lua 

and this is my output:
--------------Beginning of output-------------
 0.2654  0.3682  0.5336
 0.5982  0.4208  0.6277
 0.8369  0.9426  0.7470
 0.5394  0.9749  0.0903
 0.8083  0.6023  0.9460
[torch.DoubleTensor of size 5x3]

**********************	
 0.1211  0.9366  0.6104  0.1555
 0.8324  0.6474  0.9534  0.0824
 0.6218  0.7357  0.9679  0.5285
[torch.DoubleTensor of size 3x4]

*****************	
 0.6704  0.8795  1.0295  0.3536
 0.8131  1.2945  1.3739  0.4594
 1.3505  1.9437  2.1326  0.6026
 0.9330  1.2028  1.3461  0.2120
 1.1875  1.8430  1.9832  0.6753
[torch.DoubleTensor of size 5x4]

CUDA CORES!	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-8564/cutorch/lib/THC/THCGeneral.c line=66 error=30 : unknown error
/home/author/torch/install/bin/luajit: /home/author/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (30) : unknown error at /tmp/luarocks_cutorch-scm-1-8564/cutorch/lib/THC/THCGeneral.c:66
stack traceback:
	[C]: in function 'error'
	/home/author/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	testfile.lua:15: in main chunk
	[C]: in function 'dofile'
	...thor/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
----------------End of output----------------

Here is some more info....
When I run this command:
author@author-HP-ZBook-17 ~/Desktop $ luajit -l libcutorch

I get the following:

THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-8564/cutorch/lib/THC/THCGeneral.c line=66 error=30 : unknown error
$ Error: cuda runtime error (30) : unknown error at /tmp/luarocks_cutorch-scm-1-8564/cutorch/lib/THC/THCGeneral.c:66

Thanks for any help or comments.

**Comment by BrighamM** [comment]
btw this is on Linux Mint 18.1

**Comment by pavanky** [comment]
@BrighamM Can you verify if you can run any other cuda samples (outside of cutorch) on your machine ?

**Comment by BrighamM** [comment]
@pavanky  Thank you very much.  I wasn't sure what you meant at first but once I installed the nvcc toolkit it started working.
