### ISSUE TITLE
error: implicit declaration of function ‘THLongStorage_calculateExpandGeometry’

### ISSUE THREAD

**Issue by TonyChouZJU** [torch/cutorch#773]
#757 
[https://github.com/torch/cutorch/issues/757](url)
The previous error has been fixed. But a new error has arisen.

> 
[ 85%] [ 85%] [ 85%] [ 86%] [ 87%] [ 89%] [ 89%] Building CXX object lib/THC/CMakeFiles/THC.dir/THCCachingHostAllocator.cpp.o
Building CXX object lib/THC/CMakeFiles/THC.dir/THCCachingAllocator.cpp.o
[ 90%] Building C object lib/THC/CMakeFiles/THC.dir/THCGeneral.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCTensorCopy.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCStorageCopy.c.o
Building CXX object lib/THC/CMakeFiles/THC.dir/THCStream.cpp.o
Building C object lib/THC/CMakeFiles/THC.dir/THCTensor.c.o
Building CXX object lib/THC/CMakeFiles/THC.dir/THCTensorRandom.cpp.o
In file included from generic/THCTensor.c:1:0,
                 from /tmp/luarocks_cutorch-scm-1-4258/cutorch/lib/THC/THCGenerateAllTypes.h:17,
                 from /tmp/luarocks_cutorch-scm-1-4258/cutorch/lib/THC/THCTensor.c:7:
/tmp/luarocks_cutorch-scm-1-4258/cutorch/lib/THC/generic/THCTensor.c: In function ‘THCudaByteTensor_newExpand’:
/tmp/luarocks_cutorch-scm-1-4258/cutorch/lib/THC/generic/THCTensor.c:304:3: **error: implicit declaration of function ‘THLongStorage_calculateExpandGeometry’ [-Werror=implicit-function-declaration]
   THLongStorage_calculateExpandGeometry(tensor->size,
   ^**
cc1: some warnings being treated as errors
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THCTensor.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

> 

Thanks again!

**Comment by sidney1505** [comment]
i have exactly the same error but also no clue how to solve it

**Comment by soumith** [comment]
luarocks install torch
luarocks install cutorch
