### ISSUE TITLE
error: too few arguments while installing cutorch with luarocks in function THCudaTensor_varall

### ISSUE THREAD

**Issue by jay98** [torch/cutorch#789]
I'm trying to install cutorch using luarocks.
I ran the command `luarocks install cutorch`
 I get the following error at 96% 

`/tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c:90174:8: error: too few arguments to function ‘THCudaTensor_varall’
 arg2 = THCudaTensor_varall(default_arg1,arg1);
        ^
In file included from /tmp/luarocks_cutorch-scm-1-9417/cutorch/build/lib/THC/THCGeneral.h:4:0,
                 from /tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THC.h:4,
                 from /tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c:3:
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THCTensor.h:9:40: note: declared here
 #define THCTensor_(NAME)   TH_CONCAT_4(TH,CReal,Tensor_,NAME)
                                        ^
/home/jay/torch/install/include/TH/THGeneral.h:115:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THCTensor.h:9:28: note: in expansion of macro ‘TH_CONCAT_4’
 #define THCTensor_(NAME)   TH_CONCAT_4(TH,CReal,Tensor_,NAME)
                            ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/generic/THCTensorMathReduce.h:14:17: note: in expansion of macro ‘THCTensor_’
 THC_API accreal THCTensor_(varall)(THCState *state, THCTensor *self, int biased
                 ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c: In function ‘cutorch_CudaTensor_std’:
/tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c:90262:8: error: too few arguments to function ‘THCudaTensor_stdall’
 arg2 = THCudaTensor_stdall(default_arg1,arg1);
        ^
In file included from /tmp/luarocks_cutorch-scm-1-9417/cutorch/build/lib/THC/THCGeneral.h:4:0,
                 from /tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THC.h:4,
                 from /tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c:3:
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THCTensor.h:9:40: note: declared here
 #define THCTensor_(NAME)   TH_CONCAT_4(TH,CReal,Tensor_,NAME)
                                        ^
/home/jay/torch/install/include/TH/THGeneral.h:115:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THCTensor.h:9:28: note: in expansion of macro ‘TH_CONCAT_4’
 #define THCTensor_(NAME)   TH_CONCAT_4(TH,CReal,Tensor_,NAME)
                            ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/generic/THCTensorMathReduce.h:12:17: note: in expansion of macro ‘THCTensor_’
 THC_API accreal THCTensor_(stdall)(THCState *state, THCTensor *self, int biased
                 ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c: In function ‘m_cutorch_CudaTensor_var’:
/tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c:98322:8: error: too few arguments to function ‘THCudaTensor_varall’
 arg2 = THCudaTensor_varall(default_arg1,arg1);
        ^
In file included from /tmp/luarocks_cutorch-scm-1-9417/cutorch/build/lib/THC/THCGeneral.h:4:0,
                 from /tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THC.h:4,
                 from /tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c:3:
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THCTensor.h:9:40: note: declared here
 #define THCTensor_(NAME)   TH_CONCAT_4(TH,CReal,Tensor_,NAME)
                                        ^
/home/jay/torch/install/include/TH/THGeneral.h:115:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THCTensor.h:9:28: note: in expansion of macro ‘TH_CONCAT_4’
 #define THCTensor_(NAME)   TH_CONCAT_4(TH,CReal,Tensor_,NAME)
                            ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/generic/THCTensorMathReduce.h:14:17: note: in expansion of macro ‘THCTensor_’
 THC_API accreal THCTensor_(varall)(THCState *state, THCTensor *self, int biased
                 ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c: In function ‘m_cutorch_CudaTensor_std’:
/tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c:98410:8: error: too few arguments to function ‘THCudaTensor_stdall’
 arg2 = THCudaTensor_stdall(default_arg1,arg1);
        ^
In file included from /tmp/luarocks_cutorch-scm-1-9417/cutorch/build/lib/THC/THCGeneral.h:4:0,
                 from /tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THC.h:4,
                 from /tmp/luarocks_cutorch-scm-1-9417/cutorch/build/TensorMath.c:3:
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THCTensor.h:9:40: note: declared here
 #define THCTensor_(NAME)   TH_CONCAT_4(TH,CReal,Tensor_,NAME)
                                        ^
/home/jay/torch/install/include/TH/THGeneral.h:115:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/THCTensor.h:9:28: note: in expansion of macro ‘TH_CONCAT_4’
 #define THCTensor_(NAME)   TH_CONCAT_4(TH,CReal,Tensor_,NAME)
                            ^
/tmp/luarocks_cutorch-scm-1-9417/cutorch/lib/THC/generic/THCTensorMathReduce.h:12:17: note: in expansion of macro ‘THCTensor_’
 THC_API accreal THCTensor_(stdall)(THCState *state, THCTensor *self, int biased
`

I tried to look online and couldn't find a solution, I would really appreciate if you would reply asap, as I have to present a demo in 3 days.

Thank You

**Comment by jay98** [comment]
It's the same issue as [#788](https://github.com/torch/cutorch/issues/788)

**Comment by soumith** [comment]
this is now fixed on master. rerunning the command will fix it. Thanks a lot for reporting.

**Comment by jay98** [comment]
Thanks a lot !!! @soumith
