### ISSUE TITLE
Model faster in GeForce GTX 1060 6 GB compared to Google cloud K80 12 GB, missing something?

### ISSUE THREAD

**Issue by rremani** [torch/cutorch#795]
Hi @ezyang @soumith @szagoruyko , 
A typical resnet, model forward is taking 31ms for 0.2 data points in my home 6gb pc, but the same model forward is taking 51 ms for the same data on GCP k80 12GB. I am confused, missing something.

While I was training, only 644mb is used out of 12 gb:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.51                 Driver Version: 375.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:00:04.0     Off |                    0 |
| N/A   41C    P0   108W / 149W |    644MiB / 11439MiB |     84%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      3957    C   /usr/local/torch/install/bin/luajit            642MiB |
+-----------------------------------------------------------------------------+

Thanks

**Comment by soumith** [comment]
not missing anything. stop double posting and tagging people.

**Comment by rremani** [comment]
Apologies for that but I didn't double post on the same channel. 
Can you explain me the reason why it is faster on 6gb and slower on 12 gb.
Thanks

**Comment by albanD** [comment]
Hi,
You open two identical issues on two different torch repos, I think that counts as double posting...
The memory size is not the main factor (and a quite marginal one) wrt speed of execution on GPU.
There are plenty of materials online explaining how GPU works. In your case, for DL workload, I would say that the difference is mainly due to the fact that the K80 is a Kepler card, while the 1060 is a Pascal card (two generations newer).

**Comment by rremani** [comment]
Thanks @albanD, that's interesting, I never thought in those terms, just checked it out and it seems google would be launching p100's by early 2018. Anyways, this was what I needed.
