### ISSUE TITLE
Segmentation fault (core dumped) when I run 'cutorch.synchronizeAll()'

### ISSUE THREAD

**Issue by zerchen** [torch/cutorch#827]
The environment is ubuntu16.04, CUDA 8, cudnn 6,  GPU is Nvidia Tesla P100
I run the torch in nvidia docker container. However, when I run 'require cudnn ‘ or  'cutorch.synchronizeAll()'
, it returns 'Segmentation fault (core dumped)'
I analyze it with the help of gdb and the output is: 
 
th> require 'cutorch'
[New Thread 0x7ffe4c232700 (LWP 160)]
th> cutorch.synchronizeAll()
[New Thread 0x7ffe48231700 (LWP 161)]
[New Thread 0x7ffe3ffff700 (LWP 162)]

Thread 67 "luajit" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe3ffff700 (LWP 162)]
0x00007ffe525868df in ?? () from /usr/local/nvidia/lib64/libcuda.so.1
(gdb) bt
#0  0x00007ffe525868df in ?? () from /usr/local/nvidia/lib64/libcuda.so.1
#1  0x00007ffe526e1014 in ?? () from /usr/local/nvidia/lib64/libcuda.so.1
#2  0x00007ffe5267a468 in ?? () from /usr/local/nvidia/lib64/libcuda.so.1
#3  0x00007ffff746e6ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007ffff6f8e82d in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by ROC-Zerui** [comment]
The problem really drives me nuts. Thank you in advance.
