### ISSUE TITLE
Getting "cublasSgetrsBatched" is undefined on compile

### ISSUE THREAD

**Issue by jsankovitch** [torch/cutorch#832]
Getting the following errors when trying to compile (luarocks install cutorch).  I'm trying to get everything running on an Nvidia TK1 using [this guide](https://www.jetsonhacks.com/2015/05/20/torch-7-scientific-computer-framework-with-cudnn-nvidia-jetson-tk1).  I'm on CUDA 6.5 as that's the latest this hardware can support.  Thanks in advance.

  | [  4%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o
-- | --
  | /tmp/luarocks_cutorch-scm-1-702/cutorch/lib/THC/THCBlas.cu(464): error: identifier "cublasSgetrsBatched" is undefined
  | {1}
  | /tmp/luarocks_cutorch-scm-1-702/cutorch/lib/THC/THCBlas.cu(481): error: identifier "cublasDgetrsBatched" is undefined
  | {1}
  | 2 errors detected in the compilation of "/tmp/tmpxft_000025bb_00000000-6_THCBlas.cpp1.ii".
  | CMake Error at THC_generated_THCBlas.cu.o.Release.cmake:282 (message):
  | Error generating file
  | /tmp/luarocks_cutorch-scm-1-702/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
  | {1}
  | {1}
  | make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
  | make[2]: *** Waiting for unfinished jobs....
  | /tmp/luarocks_cutorch-scm-1-702/cutorch/lib/THC/generated/../THCReduce.cuh(316): error: more than one instance of overloaded function "min" matches the argument list:
  | function "min(int, int)"
  | function "min(unsigned int, unsigned int)"
  | function "min(int, unsigned int)"
  | function "min(unsigned int, int)"
  | function "min(long long, long long)"
  | function "min(unsigned long long, unsigned long long)"
  | function "min(long long, unsigned long long)"
  | function "min(unsigned long long, long long)"
  | function "min(float, float)"
  | function "min(double, double)"
  | function "min(float, double)"
  | function "min(double, float)"
  | argument types are: (unsigned long, unsigned long)
  | {1}
  | /tmp/luarocks_cutorch-scm-1-702/cutorch/lib/THC/generated/../THCReduce.cuh(324): error: no instance of function template "THCCeilDiv" matches the argument list
  | argument types are: (ptrdiff_t, long)
  | {1}
  | 2 errors detected in the compilation of "/tmp/tmpxft_000025dc_00000000-4_THCTensorMaskedDouble.cpp4.ii".
  | CMake Error at THC_generated_THCTensorMaskedDouble.cu.o.Release.cmake:282 (message):
  | Error generating file
  | /tmp/luarocks_cutorch-scm-1-702/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMaskedDouble.cu.o
  | {1}
  | {1}
  | make[2]: *** [lib/THC/CMakeFiles/THC.dir/generated/THC_generated_THCTensorMaskedDouble.cu.o] Error 1
  | make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
  | make: *** [all] Error 2
  | {1}
  | Error: Build error: Failed building.

**Comment by BananaNeil** [comment]
I'm also having this issue.
