### ISSUE TITLE
Installing error, the unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by pablodalma93** [torch/cutorch#853]
I'm getting this error when installing cutorch with 

luarocks install --server=https://luarocks.org/dev cutorch or 
luarocks install cutorch

Installing error, the unauthenticated git protocol on port 9418 is no longer supported

Error: failed cloning git repository

**Comment by varshinees** [comment]
This worked for me! Run this in the terminal and try `luarocks install cutorch` again

`git config --global url."https://github.com/".insteadOf git://github.com/`
