### ISSUE TITLE
illegal memory access asserted

### ISSUE THREAD

**Issue by russellfei** [torch/cutorch#87]
Two weeks ago, I installed `cudnn` and changed convolution operations from `cunn` to `cudnn`.
while the first time I typped `require 'cutorch'` in `th` there comes message like:

``` bash
th> require 'cudnn'
Error in CuDNN. Status Code:    6   
true    
```

Well, till this morning my code keeps running even with `6 status`,
however, when I start new code this evening, this errrors assert  at `test()` function

The code errors with 

``` bash
Error in CuDNN. Status Code:       7
Error in CuDNN. Status Code:       8
```

@soumith , I've checked the torch7 group, someone met something like this before,
but I still have no idea how to handle this, would you help me figure out this?
Also welcome for help from who's currently using this lib.

**Comment by russellfei** [comment]
@soumith Happy new year~
Thankfully, this bug could be located. And I should pay more time on understanding the framework of torch, then I'll be able to catch that bug by myself, haha;-)

**Comment by russellfei** [comment]
@soumith @szagoruyko  I've got a email notification that NVIDIA released another CuDNN version-RC2, what about this issue this time?
I'll have a try and update result here. ;-)

**Comment by soumith** [comment]
Yes you can try the R2RC2 branch in cudnn.torch, the new release fixed all the bugs in RC1

**Comment by ffmpbgrnn** [comment]
Hey guys, I met the same problem with:
```
/home/archy/torch/bin/luajit: cuda runtime error (77) : an illegal memory access was encountered at /tmp/luarocks_cutorch-scm-1-1025/cutorch/lib/THC/THCStorage.c:113
```
I used the lastest `cutorch`, `cudnn` and `cunn`. And I found that this error is occurred randomly.
Any idea? Thanks. :-)

**Comment by shuzi** [comment]
Hi all,

I have similar issue with unit testing 
th -lcutorch -e "cutorch.test{'multi_gpu_copy_noncontig'}"
seed:   1436207704
Running 1 tests
|  ==> multi_gpu_copy_noncontig/u/mfeng/torch/extra/cutorch/lib/THC/THCStorage.c(113) : cuda runtime error (77) : an illegal memory access was encountered at /u/mfeng/torch/extra/cutorch/lib/THC/THCGeneral.c:241

**Comment by russellfei** [comment]
Hi, @ffmpbgrnn! Could you provide more info about your code and model?
Various cases can lead to this issue.

**Comment by russellfei** [comment]
@shuzi Didn't catch same error on my torch system.
According to documentation of cutorch, directly usage of API from this package is not recommended unless you are equivalent to core developers/"That Facebook Guy".

However, you can provide more info about your hardware such as detailed GPU parameters.
Good Luck!

**Comment by shuzi** [comment]
@russellfei     is it possible that you run the unit test for package cutorch under an environment that P2P GPU communication is not available?

**Comment by shuzi** [comment]
@russellfei 

![image](https://cloud.githubusercontent.com/assets/6613848/8537573/ef4793c4-242e-11e5-9ae5-433873fee9ff.png)

**Comment by russellfei** [comment]
@shuzi Wow, multi-GPUs, sounds great! Well, currently I only have access to one GPU for my net training. 
Data transfer between GPUs is essential for this case.
What about this copy just using CPU/memory?

**Comment by shuzi** [comment]
CPU has no problem  runs well
I am running some common network
![image](https://cloud.githubusercontent.com/assets/6613848/8537866/912194b2-2432-11e5-9745-dafc7cbafbe9.png)


![image](https://cloud.githubusercontent.com/assets/6613848/8537856/76d9ea64-2432-11e5-8de1-9931a9a67ccd.png)

from the above figure seems both GPUs are working or not?
I do not get any speed up by using GPU,  speed is same as before

**Comment by russellfei** [comment]
@shuzi Sometimes, the acceleration of computation is quite negeletivie due to the simplicity of your model - simple models seems slower on GPU than CPU as the main time cost is data transfer between host and device while CPU version just leaves that out, thus in simple model cases, CPU version is more competitive.

However, when model is complex enough, for example, 10 layers and above, GPU computation is blazzing fast ;-p

**Comment by eriche2016** [comment]
hi, guys, same issue here, can any one give some help

**Comment by eriche2016** [comment]
in case others will fall in the same trap like me,  I fix the problem by trying to make the varibales in my code occupy the same memory space every iterations , such that that GPU will not need to allocate and deallocate the memoy of the local variables. I think this is the bugs that cutorch has, because making the variable's memory space can vary at each iterations of my code  is my real need to solve my problems.

**Comment by qyouurcs** [comment]
Hello guys, 

I also have the similar issue.
```
an illegal memory access was encountered at /tmp/luarocks_cutorch-scm-1-196/cutorch/lib/THC/THCStorage.c:137```

@eriche2016 I think my problem is similar to yours. At iteration, the size of the local variable may change.

**Comment by xiao1228** [comment]
@eriche2016 Hi could you tell me how to set a variable that occupy the same memory space in each iterations in lua? Because I have met the same problem. Thank you so much.

**Comment by afrozalm** [comment]
Have replaced all local variables to global to do this?

**Comment by eriche2016** [comment]
yes, you can here, above all, you should create variables that will hold the same size of content instead of variable size of content at every iterations.
