### ISSUE TITLE
reshape, view, resize differences

### ISSUE THREAD

**Issue by szagoruyko** [torch/cutorch#98]
Could someone please clear the differences between THCudaTensor_resize(n)d and :view, :reshape? In which cases resize doesn't copy memory, and is there an equivalent of view in TH? Does reshape call resize? For example this is surprising:
```c++
THCudaTensor_resize2d(tensor, oH, oW);
THCudaTensor_resize3d(tensor, 1, oH, oW); // no copy
THCudaTensor_resize2d(tensor, 1, oH*oW); // copy!
```

I've tried looking into TH and THC source code but it is still unclear to me. Thanks!

**Comment by soumith** [comment]
resize never copies memory.
reshape always copies memory.
view never copies memory.

resize literally resizes the tensor. if a tensor's underlying storage is too small, it calls realloc to expand the storage to an appropriate size: https://github.com/torch/torch7/blob/master/lib/TH/generic/THTensor.c#L687
How realloc does the mallocing (i.e. whether it expands the memory in-place or allocates completely new memory) is handled at the system level. You should not rely on resize keeping the same memory if you ever change nElement of the tensor

reshape creates a new tensor and always copies over the memory of src tensor over.

view never copies, ever. worst case it errors out.
view does not have an exact implementation in TH, but view's closest equivalent is this constructor:
https://github.com/torch/torch7/blob/master/lib/TH/generic/THTensor.h#L42

**Comment by szagoruyko** [comment]
thanks Soumith, got it now!
